### ISSUE TITLE
gcp_cloud_storage error logging masks actual errors

### ISSUE THREAD

**Issue by disintegrator** [Jeffail/benthos#1000]
Given this snippet:

```yaml
output:
  fallback:
    - gcp_cloud_storage:
        bucket: "redacted"
        path: outputs/batch-${! meta("batch_hash") }.csv
        content_type: text/csv
        collision_mode: error-if-exists  # the interesting bit
```

I'm getting an error as follows:

```
"Failed to send message to gcp_cloud_storage: file at path already exists: outputs/batch-3132303439373536313238363539343839333232.csv"
```

When I check my bucket I don't see an object with this path. I think the way benthos is logging errors is masking the actual error message: https://github.com/Jeffail/benthos/blob/d61d275d43d64c72a0bac1b0f9532c33404d0462/internal/impl/gcp/output_cloud_storage.go#L215-L221

I rebuilt benthos with some error logging and found the actual error is:
```
Get "https://storage.googleapis.com/storage/v1/b/redacted/o/outputs%2Fbatch-3132303439373536313238363539343839333232.csv?alt=json&prettyPrint=false&projection=full": context canceled
```
