### ISSUE TITLE
Fan-in processor?

### ISSUE THREAD

**Issue by andytruong** [Jeffail/benthos#101]
Hi there,

I am going to use benthos to build a data pipeline that aggregate 1000 messages to process publish to my consumer. But in my can, I need in 5 seconds, the messages being in buffered should be processed — I need messages should be processed if one of two of these conditions pass:

1. Buffer reach 1000
2. Tick interval reach 5s.

I am using this configuration:

```
input:
  type: amqp
  amqp:
    bindings_declare: []
    consumer_tag: benthos-consumer
    prefetch_count: 1000
    prefetch_size: 0
    queue: benthos-queue
    queue_declare:
      durable: true
      enabled: false
    url: amqp://go1:go1@rabbitmq:5672/
pipeline:
  processors:
  - type: combine
    combine:
      parts: 7
  - type: throttle
    throttle:
      period: 1000us
output:
  type: http_client
  http_client:
    backoff_on:
    - 429
    drop_on: []
    headers:
      Content-Type: application/json
    max_retry_backoff_ms: 300000
    retries: 3
    retry_period_ms: 1000
    timeout_ms: 5000
    url: http://requestbin.fullcontact.com/v6onirv6
    verb: POST
```

Thanks for supporting.

**Comment by Jeffail** [comment]
Hey @andytruong, I think I understand your problem. You might be better off using the [`batch`](https://github.com/Jeffail/benthos/tree/master/docs/processors#batch) processor instead of `combine`, it would let you batch messages on either:

- The batch size reaching a limit (in this case you would be measuring in bytes, not messages)
- A time period is reached (5s)

This differs from your requirements as it doesn't allow you to set an explicit message count. If I were to add that ability to the `batch` processor would it satisfy your needs?

**Comment by andytruong** [comment]
Awesome. Thanks so much Jeff (:

**Comment by Jeffail** [comment]
@drushman, the `batch` processor only checks the conditions of its send on the event of a message being received. If you set up an AMQP queue with messages totaling less than 1000 bytes and Benthos reads the entire queue within 10ms then your example won't display any output.

If you want to see your example work you need to feed it a continuous stream of data. Alternatively you could fake it by simulating a slow feed with a `throttle` processor:

``` yaml
input:
  type: amqp
  amqp:
    bindings_declare: []
    consumer_tag: benthos-consumer
    prefetch_count: 1
    prefetch_size: 0
    queue: benthos-queue
    queue_declare:
      durable: true
      enabled: false
    url: amqp://root:root@192.168.1.7:5672/
  processors:
  - type: throttle
    throttle:
      period: 3ms
  - type: batch
    batch:
      byte_size: 1000
      period_ms: 10
output:
  type: stdout
  stdout:
    delimiter: "\n"
```

This will limit the stream from AMQP to one message per 3ms, and since your batches are every 10ms you should see roughly three messages per output batch. It'll be hard to detect that by looking at the output so maybe also try increasing the batch `period_ms` to `500` and the throttle `period` to `100ms`.
