### ISSUE TITLE
CSV input with `batch_count` set to greater than one generates empty output lines after each batch. 

### ISSUE THREAD

**Issue by heikkilamarko** [Jeffail/benthos#1016]
I'm using `csv` input with `batch_count` set to greater than one. In the resulting output file, there is an empty line after each batch.

If I set `batch_count` to `1`, there are no empty lines.

## Benthos Version

```
$ benthos -v
Version: 3.60.1
Date: 2021-12-03T23:28:21Z
```

### config.yaml

```yaml
input:
  csv:
    paths:
      - in.csv
    parse_header_row: true
    delimiter: ","
    batch_count: 3 # <-- SEE HERE

output:
  file:
    path: out.csv
    codec: lines
```

### in.csv:

```csv
foo,bar,baz
demo,demo,demo
demo,demo,demo
demo,demo,demo
demo,demo,demo
demo,demo,demo
demo,demo,demo
demo,demo,demo
demo,demo,demo
demo,demo,demo
demo,demo,demo
```

### out.csv

```csv
{"bar":"demo","baz":"demo","foo":"demo"}
{"bar":"demo","baz":"demo","foo":"demo"}
{"bar":"demo","baz":"demo","foo":"demo"}

{"bar":"demo","baz":"demo","foo":"demo"}
{"bar":"demo","baz":"demo","foo":"demo"}
{"bar":"demo","baz":"demo","foo":"demo"}

{"bar":"demo","baz":"demo","foo":"demo"}
{"bar":"demo","baz":"demo","foo":"demo"}
{"bar":"demo","baz":"demo","foo":"demo"}

{"bar":"demo","baz":"demo","foo":"demo"}
```

**Comment by Jeffail** [comment]
Hey @heikkilamarko, this is actually behaviour of the output, looks like the docs aren't clear for the `files` output but it behaves the same as the `stdout` output:


> When writing multipart (batched) messages using the lines codec the last message ends with double delimiters. E.g. the messages "foo", "bar" and "baz" would be written as:
> 
> ```
> foo\n
> bar\n
> baz\n
> ```
> 
> Whereas a multipart message `[ "foo", "bar", "baz" ]` would be written as:
> 
> ```
> foo\n
> bar\n
> baz\n\n
> ```

The reason it does this is so that you could potentially reproduce the batches downstream in the pipeline if their grouping is important. If you don't want it to do that but you still want batching at the input level then add a split processor (https://www.benthos.dev/docs/components/processors/split) before messages reach the output and it'll stop adding those empty lines:

```yaml
input:
  csv:
    paths:
      - in.csv
    parse_header_row: true
    delimiter: ","
    batch_count: 3 # <-- SEE HERE

output:
  file:
    path: out.csv
    codec: lines
  processors:
    - split: {}
```
