### ISSUE TITLE
Choosing from multiple inputs

### ISSUE THREAD

**Issue by dcmoura** [Jeffail/benthos#1026]
Let's say I have a pipeline but I want to use it either to process data from kafka or from s3. The processing and outputting are the same, the only difference is that in some deployments I would read json data from files while in other deployments I would read json data from kafka. These options are mutually exclusive, I would not read from both s3 and kafka at the same time. 

Is there any option to have a "conditional" input, for instance, based on some env variable? 
I am trying to avoid duplicating the configuration yaml... maybe having the logic in a separate file that can be imported by both pipes? What option would you think it is best?

Thanks!

**Comment by Jeffail** [comment]
Hey @dcmoura, you can use resources for this: https://www.benthos.dev/docs/configuration/resources

Specifically I'd recommend using import toggles: https://www.benthos.dev/docs/configuration/resources#with-imports as that would allow you to define two separate files:

foo_input_kafka.yaml:
```yaml
input_resources:
  - label: foo_input
    kafka:
      addresses: [ TODO ]
      topics: [ TODO ]
```

foo_input_s3.yaml:
```yaml
input_resources:
  - label: foo_input
    aws_s3:
      bucket: TODO
```

And a main config file:

```yaml
input:
  resource: foo_input

pipeline:
  processors:
    - bloblang: |
        root = this
        root.meow = "woof"

output:
  file:
    path: ./out.jsonl
```

And then run it using the resources flag (`-r`) to import the one that you want:

```sh
benthos -r ./foo_input_kafka.yaml -c ./main.yaml
```

```sh
benthos -r ./foo_input_s3.yaml -c ./main.yaml
```
