### ISSUE TITLE
Streams mode issue .. it's me not you .. help! :)

### ISSUE THREAD

**Issue by DavidDattner-nbcuni** [Jeffail/benthos#1027]
running:

benthoshugsetl.exe -r ./streamresource/staticfhir_resource.yaml streams ./streamconf/staticfhir_conf.yaml

getting:

Configuration file read error: ./streamresource/staticfhir_resource.yaml: line 21: unable to infer processor type, multiple candidates 'branch' and 'log'

Attached my 2 files thanks!

David.

[staticfhir_resource.zip](https://github.com/Jeffail/benthos/files/7774860/staticfhir_resource.zip)

**Comment by Jeffail** [comment]
Hey @DavidDattner-nbcuni, in your resources file you have:

```yaml
processor_resources:
  - label: staticfhir_proc  
  - branch:
        processors:
          - http:
              url: https://try.smilecdr.com/baseR4/${! json("resourceType") }
              verb: POST
              headers:
                  Content-Type: application/fhir+json
              basic_auth:
                enabled: true
                username: ${SMILE_USERNAME}
                password: ${SMILE_PASSWORD}
              tls:
                  enabled: true
                  skip_cert_verify: true
        result_map:  root.smileresp = this
    log:
      level: DEBUG
      message: ${! json("smileresp") }
```

Which has a couple of issues, the first being `- label: staticfhir_proc` is it's own element, the second is that `log` config needs to be its own element if you want it somewhere, right now it's inside the same processor config as your `branch`, I'm assuming you want this:

```yaml
processor_resources:
  - label: staticfhir_proc  
    branch:
        processors:
          - http:
              url: https://try.smilecdr.com/baseR4/${! json("resourceType") }
              verb: POST
              headers:
                  Content-Type: application/fhir+json
              basic_auth:
                enabled: true
                username: ${SMILE_USERNAME}
                password: ${SMILE_PASSWORD}
              tls:
                  enabled: true
                  skip_cert_verify: true
        result_map:  root.smileresp = this
```

I'm a bit concerned that the project issues are becomming noisy with questions, would appreciate if you could keep questions like this (especially when it's YAML stuff) either in the social channels or maybe open a discussion instead.
