### ISSUE TITLE
How to merge multiple files into one file ?

### ISSUE THREAD

**Issue by togettoyou** [Jeffail/benthos#1028]
I have multiple files on SFTP, but I want to merge them into one file and output them. How can I do this?

**Comment by Jeffail** [comment]
Hey @togettoyou, you can consume multiple files by listing more than one in the paths field, and also by specifying a glob pattern to capture any number of matching paths:

```yaml
input:
  label: ""
  sftp:
    address: TODO
    paths: [ foo.txt, bar.txt, ./things/*.txt ]
    codec: all-bytes
```

But the concept of "merge" depends on what type of data is in there, what does the data within each file look like and what do you need your output stream to look like?

**Comment by togettoyou** [comment]
Thank you for your answer !

It looks something like this :

`foo.csv` :
```
id|number|update_time
1|123|2021-11-01 18:00:00
2|345|2021-11-01 18:00:00
3|567|2021-11-01 18:00:00
```

`bar.csv` :
```
id|name
1|hello
2|hai
3|fff
```

`output.csv` :
```
id|name|number|update_time
1|hello|123|2021-11-01 18:00:00
2|hai|345|2021-11-01 18:00:00
3|fff|567|2021-11-01 18:00:00
```

**Comment by Jeffail** [comment]
Can it be assumed that the ordering of the rows is incremental (sorted by id) in all input files? And how large are these files expected to be? There's a few different ways of performing a join like this each with their own trade offs so ideally you'd want one tailored for the workload.

**Comment by togettoyou** [comment]
> Can it be assumed that the ordering of the rows is incremental (sorted by id) in all input files? 

It is not.

Here's what happens: I have a CSV dictionary file of about 100,000 lines with ids and other information. Then there are several CSV files (within 100,000 lines each) that also have ids and other information in them. I need to use the ID key to match the corresponding records in the CSV dictionary file and merge them into the current CSV file.

These CSV files (CSV Dictionary files and several CSV files to merge) are on SFTP.

**Comment by togettoyou** [comment]
`foo.csv` can be understood as a dictionary file.

`bar.csv` have more than one, such as `bar1.csv` and `bar2.csv`.

I need to :

`bar1.csv` + `foo.csv` = `output.csv`

`bar2.csv` + `foo.csv` = `output.csv`

**Comment by Jeffail** [comment]
Okay cool, since `foo.csv` is a dictionary you can use a sequence input to use it to populate a cache first, then only consume the `bar.csv` files when that dictionary is populated. Then you use a branch processor to merge the lookup from the dictionary with rows matched by id. An abridged config might look like this:

```yaml
input:
  sequence:
    inputs:
      - sftp:
          address: TODO
          paths:
            - ./foo.csv
          codec: csv:|
        processors:
          - cache:
              resource: foo
              operator: set
              key: ${! json("id") }
              value: ${! content() }
          - bloblang: |-
              # We only need the rows in our cache, so delete them after they're added
              root = deleted()

      - sftp:
          address: TODO
          paths:
            - ./*/bar.csv
          codec: csv:|
        processors:
          - branch:
              processors:
                - cache:
                    resource: foo
                    operator: get
                    key: ${! json("id") }
                    value: ""
              result_map: root.foo_data = this

cache_resources:
  - label: foo
    memory:
      ttl: 900
      compaction_interval: 60s
```

With that config each time you run Benthos it'll start by re-reading `foo.csv`, and only afterwards does it start consuming the other files. One thing to note is that the `codec` for the sftp inputs needs to be `csv:|` as your files look like they use pipe delimiters, I have literally only just added this so if you run that example you'll need the latest version of benthos (https://github.com/Jeffail/benthos/releases/tag/v3.61.0).

After the branch processor I've dumped the result of the cache into a new field `foo_data`, if you wanted to flatten those fields back into the original structure then add a new mapping with something like `root = this.without("foo_data").merge(this.foo_data)`.

As for outputting a csv file you will need to transform the structured results back into a csv form. There's a few ways of doing this as well but a very crude example is to use another bloblang mapping like  `root = this.values().join("|")`, but you'll likely also need to cover cases where the values may contain pipe characters.

**Comment by togettoyou** [comment]
@Jeffail Thank you very much for your help. It really helped me.

I would eventually like to import the resulting CSV file into ClickHouse via HTTP.

Like this:

```
cat output.csv | curl 'http://127.0.0.1:8123/?user=xxx&password=xxx&database=test&format_csv_delimiter=%7C&query=INSERT%20INTO%20footable%20FORMAT%20CSVWithNames' --data-binary @-
```

But I can't find the final output structure into a CSV file functions, as well as on the https://www.benthos.dev/docs/components/outputs/http_client seems to be no option to transfer files?

**Comment by togettoyou** [comment]
Because my Clickhouse has a lot of fields, it's too much information to fill in query and args_mapping directly through your SQL Output, so I want to import the final merged CSV directly into the table via clickhouse's HTTP interface.

**Comment by togettoyou** [comment]
https://www.benthos.dev/docs/components/outputs/file Can support CSV as well.

Like this:
```
output:
  file:
    path: "./out.csv"
    codec: csv:|
```

**Comment by togettoyou** [comment]
I would like to know how to convert json results back to CSV format.

**Comment by Jeffail** [comment]
hey @togettoyou, I'd recommend adding a bloblang processor to do the csv conversion. The main reason we don't have an output csv codec right now is because there are lots of different ways of handling errors and there isn't a clear winner as it depends on the use case, there's also edge cases around whether we should add header rows when the codec is instanciated but being appended onto an existing stream (appended file, new socket connection, etc).

Instead we recommend formatting the documents into csv using processors followed by a lines codec. The advantage here is that you can customize exactly when header rows are created and whether to add any logic around capturing documents that don't match a specific number of keys (implying the join failed).

Here's an example that should get you started, I've also added a processor that flattens the object after adding your foo fields:

```yaml
input:
  sequence:
    inputs:
      - sftp:
          address: TODO
          paths:
            - ./foo.csv
          codec: csv:|
        processors:
          - cache:
              resource: foo
              operator: set
              key: ${! json("id") }
              value: ${! content() }
          - bloblang: |-
              # We only need the rows in our cache, so delete them after they're added
              root = deleted()
      - sftp:
          address: TODO
          paths:
            - ./*/bar.csv
          codec: csv:|
        processors:
          - branch:
              processors:
                - cache:
                    resource: foo
                    operator: get
                    key: ${! json("id") }
                    value: ""
              result_map: root.foo_data = this
          - bloblang: |
              # Flatten our resulting object by merging the foo fields
              # into the root of our object.
              root = this.without("foo_data").merge(this.foo_data)
pipeline:
  processors:
    - bloblang: |
        map escape_psv {
          root = if this.re_match("[\"\n|]+") {
            "\"" + this.replace("\"", "\"\"") + "\""
          } else {
            this
          }
        }

        # Extract key/value pairs as an array and sort by the key
        let kvs = this.key_values().sort_by(v -> v.key)

        # Create a header prefix for our output only on the first row
        let header = if count("rows_in_file") == 1 {
          $kvs.map_each(kv -> kv.key.apply("escape_psv")).join("|") + "\n"
        } else { "" }

        root = $header + $kvs.map_each(kv -> kv.value.string().apply("escape_psv")).join("|")
output:
  file:
    path: ./result.csv
    codec: lines
cache_resources:
  - label: foo
    memory:
      ttl: 900
      compaction_interval: 60s
```

**Comment by togettoyou** [comment]
Thank you for your help. I have successfully completed my functional requirements. BTW, your project is really great, especially bloblang's design, hahaha. Thank you! 😁 @Jeffail

**Comment by togettoyou** [comment]
Sorry to disturb you again. I wanted the final output to be HTTP_client, but now http_client will send the request as soon as it receives the message. I would like to ask if it is possible to wait until the final CSV merge is complete before making http_client requests.

**Comment by togettoyou** [comment]
Since the CSV file I ended up generating would have to be imported into ClickHouse via HTTP, I'm doing it twice manually, trying to do it in one.

**Comment by togettoyou** [comment]
```
output:
  file:
    path: ./result.csv
    codec: lines
```

Is there a way to do something like this : 

```
output:
  http_client:
    url: http://127.0.0.1:8123/?user=xxx&password=xxx&database=test&format_csv_delimiter=%7C&query=INSERT%20INTO%20test%20FORMAT%20CSVWithNames
    verb: POST
    headers:
      Content-Type: application/octet-stream
    codec: all-bytes
```

Make it send the request only once by adding `codec: all-bytes`
