### ISSUE TITLE
Support NewInputField/NewOutputField config fields

### ISSUE THREAD

**Issue by disintegrator** [Jeffail/benthos#1031]
The current plugin API does not expose a way of defining input and output config fields. This functionality can be used to build input/output wrapper plugins like broker, read_until and so on.

## Use case

I'd like to build a `debounce` input plugin that can observe one input and trigger a second one after some inactivity timeout. There is currently no way to define the `observe` and `trigger` config fields as far as I can tell.

```yaml
input:
  debounce:
    timeout: 1s
    # after 1s of no messages from the following input...
    observe:
      gcp_pubsub:
        project: blah
        subscription: blah
    # ... read one message from the following input and emit it
    trigger:
      generate:
        mapping: |
          meta batch_signal = true

output:
  gcp_cloud_storage:
    bucket: blah
    batching:
      byte_size: 10_000_000
      check: meta("batch_signal") == true
      processors:
        - bloblang: |
            root = if meta("batch_signal") == true {
              deleted()
            }
```
