### ISSUE TITLE
Running streams with `--no-api` clobbers the overall readiness endpoint

### ISSUE THREAD

**Issue by difabion** [Jeffail/benthos#1043]
State: `benthos streams --no-api /streams/*.yaml`

Expected behavior:  `/ready` is available and works as defined [here](https://www.benthos.dev/docs/guides/streams_mode/streams_api#get-ready)

It appears that disabling the streams API clobbers that endpoint.  The individual stream ready endpoints are still available though.

Example streams configs (in K8s configMap form):
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: benthos-streams
data:
  hello.yaml: |
    input:
      generate:
        mapping: root = "hello"
        interval: 5s
        count: 0
    output:
      stdout:
        codec: lines
  aaaaa.yaml: |
    input:
      generate:
        mapping: root = "AAAAAAAAAA"
        interval: 2s
        count: 0
    output:
      stdout:
        codec: lines
```
with a benthos config of
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-benthos-config
  namespace: default
  labels:
    helm.sh/chart: benthos-0.4.0
    app.kubernetes.io/name: benthos
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "3.61.0"
    app.kubernetes.io/managed-by: Helm
data:
  benthos.yaml: |
    http:
      enabled: true
      debug_endpoints: true
```
produces these endpoints as seen from an nginx container:
```json
% kubectl exec -it nginx-588469f6d6-86wjj -- /bin/sh -c "curl http://test-benthos/endpoints" | jq .
{
  "/aaaaa/ready": "Returns 200 OK if all inputs and outputs are connected, otherwise a 503 is returned.",
  "/endpoints": "Returns this map of endpoints.",
  "/hello/ready": "Returns 200 OK if all inputs and outputs are connected, otherwise a 503 is returned.",
  "/metrics": "Returns a JSON object of service metrics.",
  "/ping": "Ping me.",
  "/stats": "Returns a JSON object of service metrics.",
  "/version": "Returns the service version."
}
```
With the API enabled:
```json
% kubectl exec -it nginx-588469f6d6-86wjj -- /bin/sh -c "curl http://test-benthos/endpoints" | jq .
{
  "/aaaaa/ready": "Returns 200 OK if all inputs and outputs are connected, otherwise a 503 is returned.",
  "/endpoints": "Returns this map of endpoints.",
  "/hello/ready": "Returns 200 OK if all inputs and outputs are connected, otherwise a 503 is returned.",
  "/metrics": "Returns a JSON object of service metrics.",
  "/ping": "Ping me.",
  "/ready": "Returns 200 OK if the inputs and outputs of all running streams are connected, otherwise a 503 is returned. If there are no active streams 200 is returned.",
  "/resources/{type}/{id}": "POST: Create or replace a given resource configuration of a specified type. Types supported are `cache`, `input`, `output`, `processor` and `rate_limit`.",
  "/stats": "Returns a JSON object of service metrics.",
  "/streams": "GET: List all streams along with their status and uptimes. POST: Post an object of stream ids to stream configs, all streams will be replaced by this new set.",
  "/streams/{id}": "Perform CRUD operations on streams, supporting POST (Create), GET (Read), PUT (Update), PATCH (Patch update) and DELETE (Delete).",
  "/streams/{id}/stats": "GET a structured JSON object containing metrics for the stream.",
  "/version": "Returns the service version."
}
```
