### ISSUE TITLE
Raw output for jq processor

### ISSUE THREAD

**Issue by disintegrator** [Jeffail/benthos#1045]
**Given:**

```json
{"id":"1054fe28-a59e-4878-84f0-43b6fa41c2fb","msg":"sample \"log\" message","ts":1641393111}
```

```jq
[.ts, .id, .msg] | @csv
```

See this pipeline for reproduction: https://studio.benthos.dev/app/view/s/session-2733fe6c-d2b1-43eb-a9e1-b4aabc8f6689/gh-1045.yaml/graph

```yaml
input:
  label: sample_message
  generate:
    mapping: root = {"id":"1054fe28-a59e-4878-84f0-43b6fa41c2fc","msg":"sample \"log\" message","ts":1641393111}
    interval: "0"
    count: 1
pipeline:
  processors:
    - label: to_csv
      jq:
        query: '[.ts,.id,.msg] | @csv'
output:
  stdout:
    codec: lines

```

**Actual output:**

```
"1641393111,\"1054fe28-a59e-4878-84f0-43b6fa41c2fb\",\"sample \"\"log\"\" message\""
```

**Desired output:**

```
1641393111,"1054fe28-a59e-4878-84f0-43b6fa41c2fb","sample ""log"" message"
```

With pure `jq` this is possible with using a `--raw-output` output flag ([playground](https://jqplay.org/s/YBFbo0z3pi))

**Comment by Jeffail** [comment]
Okay this is going to look odd and needs some explanation but adding a bloblang mapping `root = this` afterwards will escape the raw string:

```yaml
input:
  label: sample_message
  generate:
    mapping: root = {"id":"1054fe28-a59e-4878-84f0-43b6fa41c2fc","msg":"sample \"log\" message","ts":1641393111}
    interval: "0"
    count: 1
pipeline:
  processors:
    - label: to_csv
      jq:
        query: '[.ts,.id,.msg] | @csv'
    - bloblang: root = this
output:
  stdout:
    codec: lines
```

What happens there is that the result of the `jq` processor is a valid JSON string, which is itself a valid JSON document so bloblang is happy to gobble it up and reference `this` as a string value. When you assign `root` to a string value (or []byte type) the resulting message assumes the raw value (you can think of bloblang as `--raw-output` by default, so you'd need to `this.quote()` to get the same output as jq is giving).
