### ISSUE TITLE
paths supports look-up by scope size

### ISSUE THREAD

**Issue by togettoyou** [Jeffail/benthos#1047]
Hi !

I would like to ask if paths can support lookups by scope size, such as using bloblang?

My folder looks something like this :
```
$ ls
2021122321  2021122322  2021122323  2021122400  2021122401
```

Format equivalent: `2006010215`

Now I want to traverse only the folders in the range `2021122321` to `2021122400` .

I tried to `delete()` on `switch` by checking `meta("sftp_path")` to filter extra files.

But is there a better way to do it, to do it without having to read the file.

That's my guess:

```
input:
  label: ""
  sftp:
    address: TODO
    paths: [ /root/${! content() > 2021122321 && content() < 2021122400 }/*.csv ]
    codec: all-bytes
```
