### ISSUE TITLE
azure blob storage input with chunker codec limited to 16kb chunk size

### ISSUE THREAD

**Issue by lfjoreteg** [Jeffail/benthos#1050]
Hello,
I've been experimenting with using Benthos for my job, trying to see how well it can handle transferring large files (on the order of 100mb to gigabytes) between Azure Blob Storage containers, and I'm running into some odd behavior that _appears_ to be a bug: **When using a chunker codec with an azure_blob_storage input, I am unable to set a chunker size that is greater than 16384 bytes.**

This appears to be some combination effect of both a **azure_blob_storage input** with the **chunker codec**, because without a codec the azure_blob_storage can handle pretty large files, and the chunker codec with a file input can be set to very large chunks (like 4mb) and working as expected.

Here is my benthos configuration YAML used in my test, where I attempt to set the chunk size to 4000000 bytes:
```
input:
  azure_blob_storage:
    storage_connection_string: ${AZURE_INPUT_CONNECTION_STRING}
    container: ${AZURE_INPUT_CONTAINER}
    codec: "chunker:4000000"
    prefix: ${AZURE_INPUT_PREFIX:""}
pipeline:
  processors:
    - for_each:
        - log:
            level: INFO
            message: Copying chunk - content length ${!content().length()}
    - noop: {}
output:
  azure_blob_storage:
    storage_connection_string: ${AZURE_OUTPUT_CONNECTION_STRING}
    container: ${AZURE_OUTPUT_CONTAINER}
    path: ${!meta("blob_storage_key")} # Retains the same blob name from the source
    blob_type: "APPEND"
```
When run I get this log output, where the length of each chunk is 16384 (16kb exactly):
```
{"@timestamp":"2022-01-05T22:41:02Z","@service":"benthos","component":"benthos.pipeline.processor.0.0","level":"INFO","message":"Copying chunk - content length 16384"}
{"@timestamp":"2022-01-05T22:41:02Z","@service":"benthos","component":"benthos.pipeline.processor.0.0","level":"INFO","message":"Copying chunk - content length 16384"}
{"@timestamp":"2022-01-05T22:41:02Z","@service":"benthos","component":"benthos.pipeline.processor.0.0","level":"INFO","message":"Copying chunk - content length 16384"}
...(repeated)...
```
However - if I modify the chunk size to something **_less_** than 16384 like 16000, I get this log output:
```
{"@timestamp":"2022-01-06T00:52:18Z","@service":"benthos","component":"benthos.pipeline.processor.0.0","level":"INFO","message":"Copying chunk - content length 16000"}
{"@timestamp":"2022-01-06T00:52:18Z","@service":"benthos","component":"benthos.pipeline.processor.0.0","level":"INFO","message":"Copying chunk - content length 384"}
{"@timestamp":"2022-01-06T00:52:18Z","@service":"benthos","component":"benthos.pipeline.processor.0.0","level":"INFO","message":"Copying chunk - content length 16000"}
{"@timestamp":"2022-01-06T00:52:18Z","@service":"benthos","component":"benthos.pipeline.processor.0.0","level":"INFO","message":"Copying chunk - content length 384"}
{"@timestamp":"2022-01-06T00:52:18Z","@service":"benthos","component":"benthos.pipeline.processor.0.0","level":"INFO","message":"Copying chunk - content length 16000"}
{"@timestamp":"2022-01-06T00:52:18Z","@service":"benthos","component":"benthos.pipeline.processor.0.0","level":"INFO","message":"Copying chunk - content length 384"}
...(repeated)...
```
...Which is very interesting. It _appears_ to pre-chunk everything to 16384/16kb, and **then** run it through the chunker.

This does not appear to be intentional, and I could not find a way to work around it. Or am I perhaps doing something wrong?
Thanks!
