### ISSUE TITLE
root is recreated when setting fields in a new bloblang processor

### ISSUE THREAD

**Issue by wirtsi** [Jeffail/benthos#1051]
Hey

I just came across some weird bloblang behavior which I don't fully understand

With input being `{"message": "input message"}`
```
pipeline:
  processors:
  - bloblang: |
      root.foo.bar = this.message
      root.foo."buz me".baz = "I like mapping"
```
I get back the expected

`{"foo":{"bar":"input message","buz me":{"baz":"I like mapping"}}}`

But this pipeline

```
pipeline:
  processors:
  - bloblang: |
      root.foo.bar = this.message
  - bloblang: |
      root.foo."buz me".baz = "I like mapping"
```
gives `{"foo":{"buz me":{"baz":"I like mapping"}}}`

Not sure why `root` seems to be recreated on the latter?

Bests & thanks

**Comment by Jeffail** [comment]
Hey @wirtsi, with the `bloblang` processor a mapping expresses how to create a new document by extracting data from an existing input document (https://www.benthos.dev/docs/guides/bloblang/about#assignment), which means when you assign fields to `root` you start off with an empty object. If you want to start off with all the existing fields by default then start your mapping with `root = this`:

```yaml
pipeline:
  processors:
  - bloblang: |
      root.foo.bar = this.message
  - bloblang: |
      root = this
      root.foo."buz me".baz = "I like mapping"
```
