### ISSUE TITLE
Suggestion: an output resource for multiple types, "dispenser"

### ISSUE THREAD

**Issue by Tapuzi** [Jeffail/benthos#1055]
Hey

# Motive
In some flows it may be useful to do the processing for a number of messages in the pipeline, and so it can be useful to split them to different outputs later.
I have stumbled upon some use cases that can benefit from this, including my own latest project.
This is a suggestion to add a component that does that in a neat way, named "dispenser" for this thread.

# Description
The output of a message to be filtered by a dispenser according to its label, allowing less nested documents and easy reference and editing.

# Use case and example
A feed is generating a metric and has some metadata.
For example, the temperature for a specific location is a metric and the sensor type is the metadata.
A Benthos may look something like this:
  
## Before
```
input:
  http:
    url: http://weatherwatch.com/sensors/moon_core
    verb: GET
  
pipeline:
  noop: {}

output:
  switch:
    cases:
      - output:
          label: metadata
          processors:
            - bloblang: |
                source = "weatherwatch"
                sensor_model = this.sensor.model
                id = wwatch1
          output:
            kafka:
              addresses: [ localhost:9092 ]
              topic: sensors_metadata
        continue: true
      - output:
          label: data
          processors:
            - bloblang: |
                temp = this.temperature
                id = wwatch1
          output:
            kafka:
              addresses: [ localhost:9092 ]
              topic: weather_data
        continue: true
```
    
With the proposed component, the following is possible:
  

## After
```
input:
  http:
    url: http://weatherwatch.com/sensors/moon_center
    verb: GET
  
pipeline:
  processors:
    - label: metadata
      bloblang: |
        source = "weatherwatch"
        sensor_model = this.sensor.model
        id = wwatch1
      
    - label: data
      bloblang: |
        temp = this.temperature
        id = wwatch1

output:
	dispenser:
	  - message_labels: [ metadata ]
	    kafka:
	      addresses: [ localhost:9092 ]
	      topic: sensors_metadata
	  - message_labels: [ data ]
	    kafka:
	      addresses: [ localhost:9092 ]
	      topic: weather_data
```

![image](https://user-images.githubusercontent.com/5293751/148891915-ceff9e44-af5b-4e40-b770-6e689f2007d1.png) -> ![image](https://user-images.githubusercontent.com/5293751/148891925-b415ccc9-e113-402a-9bc7-ef9ef4a8538c.png)

## Additional uses and considerations
* Since the dispenser logic allows already implementable logic, it should be considered to be maybe one tool too many for the job.
* Dispenser possibly allows to use the same bloblang processing step to generate a single message containing two or more sub-messages.
This can benefit simple common processing logic scenarios.
Something like:
```
	- bloblang: |
		metadata.source = "weatherwatch"
		metadata.sensor_model = this.sensor.model
		data.value = this.temperature
		data.id = metadata.id = wwatch1
...
dispenser:
- message_labels: [ metadata ]
	kafka:
		addresses: [ localhost:9092 ]
		topic: sensors_metadata
		bloblang: root = this.metadata
- message_labels: [ data ]
	kafka:
		addresses: [ localhost:9092 ]
		topic: weather_data
		bloblang: root = this.data
```
