### ISSUE TITLE
Redis output: support Hash object type

### ISSUE THREAD

**Issue by drushman** [Jeffail/benthos#106]
May we consider to support Redis hashes data type(https://redis.io/commands#hash)? That's really helpful when we want enrichment/parse data in processor then cache it in Redis.

**Comment by Jeffail** [comment]
Hey @drushman, it would be possible. We could create an output type where the `id` of each entry is interpolated similar to how the `files`, `hdfs` and `s3` outputs work. How would you imagine the hash type would be constructed? Would you expect to specify the key/value pairs with interpolation, something like this:

``` yaml
redis_hash:
  table:
    foo: ${!json_field:foo.bar}
    baz: ${!json_field:foo.baz}
```

Or would you expect the JSON structure to automatically be serialised into a hash type? In which case how would you expect nested JSON objects to be stored?
