### ISSUE TITLE
Enhancement Request - Add option to generate message on start

### ISSUE THREAD

**Issue by bhoriuchi** [Jeffail/benthos#1062]
When using the generate input, there are certain use cases where the polling interval should be long but an initial pass on start of the stream is useful to trigger the initial message. 

To summarize, the proposal is to add a configuration field to the generate input that generates a one-time initial message at startup.

Example
```yaml
input:
  label: ""
  generate:
    mapping: ""
    interval: 1s
    generate_initial: true
    count: 0
```

**Comment by Jeffail** [comment]
Hey @bhoriuchi, what is the interval you're running in your use case? With an `interval` that's set to a discrete duration string you should be seeing an event generated immediately, the exception here is when the `interval` is a cron expression. It's possible that there's a bug here.

**Comment by bhoriuchi** [comment]
I will do some additional testing to verify that the initial message isnt being lost somewhere in processing, but I actually do have a use case for sending an initial message and using cron expressions. I would like to de-dupe generated messages based on timestamp so that if there are multiple benthos instances generating messages on a cron schedule. Having talked this out, i think i can actually accomplish this with something like

```yaml
input:
  broker:
    inputs:
    # once
    - generate:
         mapping: "bloblang here"
         interval: 1s
         count: 1
    - generate:
         mapping: "bloblang here"
         interval: "cron expression"
```

I'll test this out but i think it will meet the requirement.
