### ISSUE TITLE
Intermittent "EmptyValue" error fixed on retry

### ISSUE THREAD

**Issue by akhalina** [Jeffail/benthos#1070]
Hello!

I'm working on a service that uses benthos and we're having a bit of a weird issue. We are using an http input to SQS output and occasionally we'll get this error:

```
Failed to send message to aws_sqs: record failed with code: EmptyValue, message: No Value Found for SendMessageBatchRequestEntry.1.MessageBody.
```

The weird thing about it is that a retry would fix it, meaning on a second attempt for whatever reason the message body isn't empty anymore. Furthermore, when we print out the actual messages and re-run them through we can't reproduce the same error. We have a very high traffic service that uses this, and while a retry will fix it, we are still a bit concerned by this issue. 

This is our config:
```
input:
  type: http_server
  http_server:
    address: "0.0.0.0:${PORTS_BENTHOS_OUTPUT}"
    path: /publish
    timeout: 10s
output:
  sqs:
    url: ${SQS_OUTPUT_QUEUE_URL}
    endpoint: ${SQS_OUTPUT_QUEUE_URL}
    region: ${SQS_OUTPUT_QUEUE_REGION}
    max_retries: 1
    backoff:
      max_elapsed_time: 9s
logger:
  prefix: benthos
  level: INFO
  add_timestamp: true
  json_format: true
```
We are using benthos `v3.43.1`

Do you have any ideas on why this issue would occur? We've only started seeing it in the last 2 months or so.
