### ISSUE TITLE
Verbose mode for echo to expand templates used.

### ISSUE THREAD

**Issue by r-franke** [Jeffail/benthos#1074]
Right now `echo` is treating used templates as first-class components. 

This means that the output of:

`benthos -t "./templates/*.yaml" -c ./config.yaml echo`

does not show the values that where used from the template. So when following the example on the [templating page](https://www.benthos.dev/docs/configuration/templating) the output of:

`benthos -t "./templates/*.yaml" -c ./config.yaml echo`

is:

```
input:
  label: ""
  aws_sqs_list:
    urls:
      - https://sqs.us-east-2.amazonaws.com/123456789012/MyQueue1
      - https://sqs.us-east-2.amazonaws.com/123456789012/MyQueue2
  ```

It would help with writing complex templates to add `echo_verbose` or another method so that the output of the above command would be: 

```
input:
  broker:
    inputs:
      - aws_sqs:
          url: https://sqs.us-east-2.amazonaws.com/123456789012/MyQueue1
          region: us-east-1
      - aws_sqs:
          url: https://sqs.us-east-2.amazonaws.com/123456789012/MyQueue2
          region: us-east-1
```

Currently the only way to see if your template is working is by running the config, that is not always desirable.
