### ISSUE TITLE
Using BigQuery to enrich and transform messages

### ISSUE THREAD

**Issue by disintegrator** [Jeffail/benthos#1096]
This is a proposal for `gcp_bigquery_select` proccessor similar to the input implemented in #1091. The purpose of this processor will to get enrichment data from bigquery and combine it with incoming messages - e.g. using `branch` - before forwarding downstream.

## Sample usage

Here's an example of a simple pipeline that enriches messages using BigQuery:

```yaml
input:
  generate:
    mapping: root = {"term":"the","id":uuid_v4()}
    count: 1
    interval: ""

pipeline:
  processors:
    - branch:
        processors:
          - gcp_bigquery_select:
              project: test-project
              table: bigquery-public-data.samples.shakespeare
              columns:
                - word
                - sum(word_count) as total_count
              where: word = ?
              suffix: |
                GROUP BY word
                ORDER BY total_count DESC
                LIMIT 10
              args_mapping: root = [ this.term ]
        result_map: |
          root.count = this.get("0.total_count")

output:
  stdout:
    codec: lines
```

This will output the following:

```jsonl
{"@timestamp":"2022-02-03T02:46:22Z","@service":"benthos","component":"benthos","level":"INFO","message":"Launching a benthos instance, use CTRL+C to close."}
{"@timestamp":"2022-02-03T02:46:22Z","@service":"benthos","component":"benthos","level":"INFO","message":"Listening for HTTP requests at: http://0.0.0.0:4195"}
{"count":25568,"id":"893a8f3e-b134-4de6-898b-836a86898553","term":"the"}
{"@timestamp":"2022-02-03T02:46:29Z","@service":"benthos","component":"benthos.input","level":"DEBUG","message":"Waiting for pending acks to resolve before shutting down."}
{"@timestamp":"2022-02-03T02:46:29Z","@service":"benthos","component":"benthos.input","level":"DEBUG","message":"Pending acks resolved."}
{"@timestamp":"2022-02-03T02:46:29Z","@service":"benthos","component":"benthos","level":"INFO","message":"Pipeline has terminated. Shutting down the service."}
```
