### ISSUE TITLE
Allow histogram buckets to be specified

### ISSUE THREAD

**Issue by mccricardo** [Jeffail/benthos#1097]
Following the creation of `use_histogram_timing` it would be helpful to enable the specification of histogram buckets when `use_histogram_timing: true`.

Example:
```yaml
metrics:
  prometheus:
    prefix: benthos
    use_histogram_timing: true
    histogram_buckets:
      - 5
      - 10
      - 15
      - 20
```

Metric:
```
# HELP benthos_example__metric Benthos Timing metric
# TYPE benthos_example__metric histogram
benthos_example__metric_bucket{le="5"} 0
benthos_example__metric_bucket{le="10"} 0
benthos_example__metric_bucket{le="15"} 0
benthos_example__metric_bucket{le="20"} 0
benthos_example__metric_bucket{le="+Inf"} 8
benthos_example__metric_sum 2.475379e+06
benthos_example__metric_count 8
```
