### ISSUE TITLE
Tests for processor_resources

### ISSUE THREAD

**Issue by vryazanov** [Jeffail/benthos#1101]
Hey,
is there a way to test resources from `processor_resources`?

I expected that the following stuff would work:
```
parallel: true
tests:
  - name: test something
    target_processors: '/processor_resources'
```

**Comment by Jeffail** [comment]
Hey @vryazanov, you can define tests within the file containing resources, so something like this should work:

```yaml
processor_resources:
  - label: prefix
    bloblang: 'root = "foo " + content()'

  - label: upper
    bloblang: 'root = content().uppercase()'

tests:
  - name: run all resources
    target_processors: '/processor_resources'
    input_batch:
      - content: 'example content'
    output_batches:
      -
        - content_equals: FOO EXAMPLE CONTENT
```

And you can also target resources from a test file that's associated with the file containing the resources, so if the resources are defined in `foo.yaml` you could add tests to a file `foo_benthos_test.yaml` containing something like:

```yaml
tests:
  - name: run all resources
    target_processors: '/processor_resources'
    input_batch:
      - content: 'example content'
    output_batches:
      -
        - content_equals: FOO EXAMPLE CONTENT
```

And that should work. However, what's not possible right now is to target resources that are imported with the `-r` flag directly, so if you're running `benthos -r ./foo.yaml test ./tests/*.yaml` then you can't define a `target_processors` to aim for things within `./foo.yaml`. For that you'd need to use mocking or some other mechanism.

There's an open issue for allowing the targetting of resources by the label name that would enable this: https://github.com/Jeffail/benthos/issues/1057
