### ISSUE TITLE
Consider clearing errors at the beginning of a try block, or showing a linting error

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#1121]
Right now nested `try` blocks within `catch` will never trigger:

```yaml
pipeline:
  processors:
    - try:
      - resource: foo
    - catch:
      - try:
        - resource: bar
        - resource: baz
```

So if `foo` fails neither `bar` nor `baz` would execute. This is because the error context is carried into the processors of the catch block and aren't cleared until the end so that the error message can be referrenced. A work around is to add a nested catch before the try block:

```yaml
pipeline:
  processors:
    - try:
      - resource: foo
    - catch:
      - catch: []
      - try:
        - resource: bar
        - resource: baz
```

This clears the error before the `try` block but looks odd and ugly.
