### ISSUE TITLE
Add linting hint for nested try/catch blocks

### ISSUE THREAD

**Issue by r-franke** [Jeffail/benthos#1122]
Even though the [docs](https://www.benthos.dev/docs/configuration/error_handling/#recover-failed-messages) show that an error isn't cleared until after the `catch` block it might lead to confusion.

In this example one might have expected the described behavior:

```yaml
input:
  generate:
    mapping: root = "I'M NOT A JSON!"

pipeline:
  processors:
    - try:
        - bloblang: root = this
    - catch:
      - try: 
        - log:
            message: 'This should print'
      - catch:
        - log:
            message: 'This should NOT print'
  
output:
  stdout:
    codec: lines
```
However the first `try` block in the outermost `catch` block will never hit because the previous error is still present leading to a no op.

Could be clarified by adding a linting message ie: "A try block immediately following a catch block will lead to a no op of the try block contents."

**Comment by Jeffail** [comment]
Okay so I've done a couple of things here: https://github.com/Jeffail/benthos/commit/648221569a7033a5491b2dadd0f26f0ac6de01a5

1. I've fixed it so that placing a `catch` within a `catch` doesn't result in skipped processors, that allows us to do:

```yaml
pipeline:
  processors:
    - try:
        - resource: foo
    - catch:
      - catch: []
      - try: 
        - resource: bar
        - resource: baz
```

2. I've updated the docs to clarify the behaviour of `try` and explain how to effectively nest it within a `catch` block
3. I've added a linting rule so that in cases where a `try` is placed within a `catch` where it hasn't been protected by a preceeding `catch` you get a warning that points you to the relevant docs
