### ISSUE TITLE
[Feature] Splunk Output Component

### ISSUE THREAD

**Issue by piclemx** [Jeffail/benthos#1133]
Hey 👋 ,

I really like your project. Do you think we could have the change to add an output component to send things inside Spunk?

I was looking at other project like `fluent-bit`.

https://docs.fluentbit.io/manual/pipeline/outputs/splunk

This could be a great addition imo 😄

**Comment by Jeffail** [comment]
Hey @piclemx, yeah absolutely, it's streamed over HTTP (I think) so it should be fairly easy to implement as we already have more generic versions of the same thing.

**Comment by piclemx** [comment]
If you have any example on how to produce this inside benthos. I can try to do it.
Or I can let someone else do it 😄

**Comment by Jeffail** [comment]
Sure, a good example output to copy from might be https://github.com/Jeffail/benthos/blob/master/internal/impl/nats/output_jetstream.go as it uses most of the new stuff, the plugin api docs can be found at: https://pkg.go.dev/github.com/Jeffail/benthos/v3@master/public/service

I'm happy to review an early draft PR if you need some guidance at any stage.

**Comment by mhite** [comment]
I've experimented a bit with the following generic `http_client` configuration. Seems to work okay but admittedly it needs some real world testing outside of my lab tests. Obviously a lot of tunable config bits you have to experiment with (batch size, period, etc.)

```
output_resources:
  - label: splunk_hec
    http_client:
      url: https://<YOUR-HOST>:8088/services/collector/event
      verb: POST
      headers:
        Content-Type: application/json
        Content-Encoding: gzip
        Authorization: Splunk <HEC_TOKEN>
      batching:
        count: 4
        period: 2s
        byte_size: 838860800
        processors:
          - archive:
              format: lines
      tls:
        enabled: true
#        skip_cert_verify: true
    processors:
      - compress:
          algorithm: gzip
```

**Comment by mhite** [comment]
I forgot to mention that you would need a processor (probably `bloblang`) to massage the data into a HEC-format JSON payload for the aforementioned `http_client` to POST. So that means `event`, `sourcetype`, `source`, `host`, and `time` fields.

**Comment by piclemx** [comment]
I was able to do it also with the http_client just less interesting to do it with that. Abstract the configuration of it.

**Comment by mhite** [comment]
Gotcha. I do wonder if there is existing art for inputs being a configuration facade over `http_client`.

**Comment by mihaitodor** [comment]
@mhite I guess you can use [templates](https://www.benthos.dev/docs/configuration/templating). There are some examples [here](https://github.com/benthosdev/benthos/tree/main/template/inputs) which get picked up automatically by `make docs` and end up listed as input components on https://benthos.dev.

**Comment by mhite** [comment]
@mihaitodor - Cool! I've been playing around a bit with this. Here's what I came up with based upon the snippet above.

```
name: splunk_hec
type: output
status: experimental
categories: [ ]
summary: Writes messages to a Splunk HTTP Endpoint Collector.
description: |
  This output POSTs messages to a Splunk HTTP Endpoint Collector using token based authentication. The format of the message must be a valid event JSON.
fields:
  - name: url
    description: Full HTTP Endpoint Collector (HEC) URL, ie. https://http-inputs-scv-shw-b438c561bd81c5.stg.splunkcloud.com/services/collector/event
    type: string

  - name: token
    description: A bot token used for authentication.
    type: string

  - name: gzip
    description: Enable gzip compression
    type: bool
    default: false

  - name: batching_count
    description:
    type: int
    default: 100

  - name: batching_period
    description:
    type: string
    default: "2s"

  - name: batching_byte_size
    description:
    type: int
    default: 838860800

  - name: rate_limit
    description: An optional rate limit resource to restrict API requests with.
    type: string
    default: ""
    advanced: true

  - name: max_in_flight
    description: The maximum number of parallel message batches to have in flight at any given time.
    type: int
    default: 64
    advanced: true

  - name: skip_cert_verify
    description: Whether to skip server side certificate verification.
    type: bool
    default: false
    advanced: true

mapping: |
  root.http_client.url = this.url
  root.http_client.rate_limit = this.rate_limit
  root.http_client.verb = "POST"
  root.http_client.headers."Content-Type" = "application/json"
  root.http_client.headers.Authorization = "Splunk " + this.token
  root.http_client.headers."Content-Encoding" = if this.gzip { "gzip"}
  root.http_client.max_in_flight = this.max_in_flight
  root.http_client.batch_as_multipart = false
  root.http_client.batching.count = this.batching_count
  root.http_client.batching.period = this.batching_period
  root.http_client.batching.byte_size = this.batching_byte_size
  root.http_client.batching.processors = []
  root.http_client.batching.processors."-".archive = { "format": "lines" }
  root.http_client.batching.processors."-".compress = if this.gzip {{ "algorithm": "gzip" }}
  root.http_client.tls.skip_cert_verify = this.skip_cert_verify

tests:
  - name: Basic fields
    config:
      url: https://foobar.splunkcloud.com/services/collector/event
      token: e0e7adc3-abcd-444e-8d0e-1650358891c7
      rate_limit: foolimit
      max_in_flight: 64
      gzip: false

    expected:
      http_client:
        url: https://foobar.splunkcloud.com/services/collector/event
        verb: POST
        headers:
          Content-Type: application/json
          Authorization: Splunk e0e7adc3-abcd-444e-8d0e-1650358891c7
        rate_limit: foolimit
        batch_as_multipart: false
        max_in_flight: 64
        batching:
          count: 100
          period: 2s
          byte_size: 838860800
          processors:
            - archive:
                format: lines
        tls:
          skip_cert_verify: false

  - name: gzip
    config:
      url: https://foobar.splunkcloud.com/services/collector/event
      token: footoken
      rate_limit: foolimit
      max_in_flight: 64
      gzip: true

    expected:
      http_client:
        url: https://foobar.splunkcloud.com/services/collector/event
        verb: POST
        headers:
          Content-Type: application/json
          Authorization: Splunk footoken
          Content-Encoding: gzip
        rate_limit: foolimit
        batch_as_multipart: false
        max_in_flight: 64
        batching:
          count: 100
          period: 2s
          byte_size: 838860800
          processors:
            - archive:
                format: lines
            - compress:
                algorithm: gzip
        tls:
          skip_cert_verify: false
```
