### ISSUE TITLE
Issue with `if` statement in bloblang function interpolation

### ISSUE THREAD

**Issue by george-koulouris-form3** [Jeffail/benthos#1134]
Hi there!

I'm trying to add the following metric (_example is purely for illustration purposes_):

```
...
pipeline:
  processors:
    - metric:
        type: counter_by
        name: message.missing.after.data
        value:  ${! if true { 1 } }
...
```

However, I get the following error message:

```
level=info msg="/benthos.yaml: line 16: line 1 char 17: required: expected }
```

I'm wondering if I have the syntax wrong... Could you give some hints as to how to include an if statement in a bloblang function interpolation?

**Comment by Jeffail** [comment]
Hey @george-koulouris-form3, unfortunately interpolation functions don't support the full breadth of bloblang expressions yet, so `if` and `match` statements won't parse. This is due to be fixed in the next major version release (https://github.com/Jeffail/benthos/issues/1071) and is because interpolation strings share a parser with an older (now deprecated) language.

An alternative would be to perform the expressions in a prior processor and store the result in a metadata field, if you don't want that field to persist after the `metric` processor you could place it within a `branch` and the temporary metadata field will be discarded. It'd look something like this:

```yaml
pipeline:
  processors:
    - branch:
        request_map: |
         meta foo = if this.bar.baz == "meow" {
           "woof"
         } else {
           "quack"
         }
    - metric:
        type: counter_by
        name: message.missing.after.data
        value:  ${! meta("foo") }
```
