### ISSUE TITLE
http_server headers to JSON KV

### ISSUE THREAD

**Issue by orakle** [Jeffail/benthos#1135]
Hi @Jeffail ,

Sorry about asking a noob question, very new to Benthos and truly amazed at the problem it solves. 

Just put my hands-on to implement a simple processing, which basically dumps the HTTP Header and Body from **http_server** to **sql_insert**, but actually failed to dump all the received headers as JSON (key-val) into col_1. 

`
input:
  label: ""
  http_server:
    address: ""
    path: /post
    allowed_verbs:
      - POST

output:
  sql_insert:
    driver: mysql
    dsn: foouser:foopassword@tcp(localhost:3306)/foodb
    table: footable
    columns:
      - col_1
      - col_2
    args_mapping: root = [  meta("http_server_headers"), this.string() ]
`

Wondering what I'm missing.

Thanks in advance Jeff.

**Comment by Jeffail** [comment]
Hey @orakle, there's no individual `http_server_headers` metadata field from that input as the header keys are taken as-is, so for example if you receive a header `Foo-Bar: baz` then there'll be a metadata field accessible under `meta("Foo-Bar")`. If you want to insert a JSON object of all headers the way to do that is to call `meta()` without an argument, so it'd be something like:

```yaml
output:
  sql_insert:
  driver: mysql
  dsn: foouser:foopassword@tcp(localhost:3306)/foodb
  table: footable
  columns:
    - col_1
    - col_2
  args_mapping: root = [ meta(), this.string() ]
```

However, that will also include metadata that wasn't originated from HTTP request headers (full list is here: https://www.benthos.dev/docs/components/inputs/http_server#metadata). Unfortunately there's no general way to distinguish between query parameters, cookies, and header values, but you can purge the benthos generated metadata values like `http_server_verb` with a bloblang mapping like this:

```yaml
pipeline:
  processors:
    - bloblang: 'meta = meta().filter(item -> !item.key.has_prefix("http_server_"))'

output:
  sql_insert:
  driver: mysql
  dsn: foouser:foopassword@tcp(localhost:3306)/foodb
  table: footable
  columns:
    - col_1
    - col_2
  args_mapping: root = [ meta(), this.string() ]
```
