### ISSUE TITLE
Support plugin spec with map interpolated string field.

### ISSUE THREAD

**Issue by alecrubin** [Jeffail/benthos#1141]
It would be very nice if we could support a map interpolated string field in the plugin spec to enable something like this with custom plugins:
```yaml
  - type: my_awesome_plugin
    plugin:
      attributes:
        something: "with-${! meta("some_meta_key") }"
        another: "also-${! json("value.in.body" }"
        also: "something-without-interpolation"
```
