### ISSUE TITLE
Influx line protocol output (or reformat?)

### ISSUE THREAD

**Issue by nwest1** [Jeffail/benthos#117]
Looking for some advice/direction as to how to reformat an existing message (probably json) into ILP. I'm hesitant to think of this as an output - it seems as though it might fit into a processor that would reformat a message into a single line, possibly taking into account the metadata tags as well. 

Sample benthos config:
```
type: jsonilp
jsonilp:
  value: "weather,location=${!metadata.location} temperature=${!json.value} ${!timestamp_unixnano}"
```

ILP format:
```
weather,location=us-midwest temperature=82 1465839830100400200
  |    -------------------- --------------  |
  |             |             |             |
  |             |             |             |
+-----------+--------+-+---------+-+---------+
|measurement|,tag_set| |field_set| |timestamp|
+-----------+--------+-+---------+-+---------+
```

**Comment by Jeffail** [comment]
Hey @nwest1, yeah that looks like something that should be implemented as a processor. From the example you showed this could actually be done with the `insert_part` processor since the `content` field uses config interpolation:

``` yaml
type: process_batch
process_batch:
- type: insert_part
  insert_part:
    content: "weather,location=${!json_field:location} temperature=${!json_field:temperature} ${!timestamp_unix_nano}"
    index: -1
- type: select_parts
  select_parts:
    parts: [-1]
```

The `process_batch` part means this would be safe to use even when you are batching messages together.
