### ISSUE TITLE
JSON processor with YAML config can't handle arrays

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#121]
I think this will reproduce the issue:

``` yaml
type: json
json:
  operator: set
  path: .
  value:
    foo:
    - bar: baz
```

Basically when the raw structure gets converted into a valid JSON object we walk it to make sure any `map[interface{}]interface{}` types are converted to `map[string]interface{}`. Currently the maps are walked correctly but arrays aren't.
