### ISSUE TITLE
Unclear behaviour of json processor with set operator

### ISSUE THREAD

**Issue by patrobinson** [Jeffail/benthos#140]
If you have a string or number value for `value` when using the json set operator it adds the value to the object:

```
type: json
  json:
    operator: set
    key: foo
    value: bar
```

Input:
```
{"a": "b"}
```

Output:
```
{"a": "b", "foo": "bar"}
```

If you set value to an object though, it over-writes the existing object:

```
type: json
  json:
    operator: set
    key: foo
    value:
      foo: bar
```

Input:
```
{"a": "b"}
```

Output:
```
{"foo": "bar"}
```

Note the behaviour is the same even if you do not specify the `key` field.

This is surprising. I would expect this to create a nested value and output `{"a":"b", "foo": {"foo":"bar"}}`

While this does fit my use case it took me a while to discover this because I was expecting it to behave differently.

**Comment by Jeffail** [comment]
Hey @patrobinson, the field name for specifying the target path is `path`, not `key`. I suspect you might have interchanged between the two during your tests. If you change your second example to:

``` yaml
type: json
  json:
    operator: set
    path: foo
    value:
      bar: baz
```

You should see: `{"a":"b","foo":{"bar":"baz"}}` on the output.
