### ISSUE TITLE
Metric white/blacklisting

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#146]
It's possible to create a metric target type that shields a child metric target type with a whitelist of blacklist of metric prefixes. It would look in config something similar to this:

```
type: whitelist
whitelist:
  prefixes:
  - pipeline.processor
  child:
    type: statsd
    statsd:
      ...
```

This would result in only metrics with the path prefix `pipeline.processor` being sent to statsd. This would make it a lot easier to prevent the flooding of metric aggregators for when cost is a constraint.

**Comment by danrubenstein** [comment]
Hi @Jeffail!

I've started to take this on - you can see an initial cut of the whitelist version of this [here](https://github.com/danrubenstein/benthos/commit/50d5d6b2ef9424e9fc1f8ab92e9cbc7c47d83632). It's not ready to go yet, there's still yet more to do with blacklist and the configuration management.

One scope question that I have for this is whether or not you'd be willing to accept regular expressions as a mode for white or blacklist - e.g., 

```
type: whitelist
   prefixes:
   - output.broker.outputs.*.output
   - ...
   mode: regex|direct
   child:
     ...
```
This would help with things like broker / switch etc outputs, where you might want to keep some but not all of the metrics in a sub-output or input.

Let me know what you think here - thanks!
