### ISSUE TITLE
how to add multiple input streams into one archive

### ISSUE THREAD

**Issue by bertpersyn** [Jeffail/benthos#147]
**Config**

Below my benthos config (I used plugins):

```
input:
  type: extended_s3
  plugin:
    bucket: "files"
    content_type: application/octet-stream
    credentials:
      id: "foo"
      role: ""
      role_external_id: "foo"
      secret: "foo"
      token: "foo"
    endpoint: "http://ls-s3:5000"
    region: eu-west-1
    force_path_style: true
    delete_objects: false
    download_manager:
      enabled: false
    prefix: ${S3_PREFIX}/
    retries: 10
    timeout: 5s

pipeline:
  threads: 4 # Try to match the number of available logical CPU cores
  processors:
  - type: metadata
    metadata:
      key: group
      operator: set
      parts: []
      value: ${S3_PREFIX}
  - type: group_by_value
    group_by_value:
      value: ${!metadata:group}
  - type: archive
    archive:
      format: tar
  - type: compress
    compress:
      algorithm: gzip

output:
  type: extended_s3
  plugin:
    bucket: "files"
    content_type: application/octet-stream
    credentials:
      id: "foo"
      role: ""
      role_external_id: "foo"
      secret: "foo"
      token: "foo"
    endpoint: "http://ls-s3:5000"
    force_path_style: true
    path: ${S3_PREFIX}/onecompressedarchive.tar.gz
    region: eu-west-1
    timeout: 5s
```

**Problem**

I have a S3 compat. API where I have my bucket and some files
As you can see, I use the prefix so I only fetch certain files (backup strat)

I want all the files the input downloads to be archived in one archive (tar) and ofc, the tar should get compressed.

**Question**
Can anyone show me how this can be done, or give me some clues on how this can be done?

**Comment by Jeffail** [comment]
Hey @bertpersyn, the `archive` processor acts across a batch of messages, so in your case you would want to create a batch containing the entire bucket. You could either do that programmatically in your custom consumer or use the [batch processor](https://github.com/Jeffail/benthos/blob/master/docs/processors/README.md#batch).

Using `batch` with a condition would allow you to only complete the batch once a condition has been satisfied, the condition will need to check for the final message in the bucket.

Since this is a plugin consumer you could programmatically add your own metadata to the final message of the bucket, something like `last_of_bucket` and then batch based on the presence of that metadata field.

**Comment by bertpersyn** [comment]
Thanks for the quick response, I'll try it and give my feedback.

PS:
I can make a PR for the `force_path_style: true`, because I use Ceph and don't want to use s3://subdomain.domain.com

**Comment by bertpersyn** [comment]
Jeffail, I can't seem to use the key `${!metadata:s3_key}` when naming the tar parts:

```
pipeline:
  processors:
  - type: batch
    batch:
      count: 4
  - type: archive
    archive:
      format: tar
      path: ${!metadata:s3_key}
  - type: compress
    compress:
      algorithm: gzip
```

Every part (4, as you see), get the name of the first message.

Any ideas?

**Comment by Jeffail** [comment]
Hey @bertpersyn, that's a bug, it should be interpolating the path per message of the batch (otherwise it's pretty pointless for this use case). I've pushed a fix in v1.1.3.

**Comment by bertpersyn** [comment]
And it works!

To know the last message I can use some funky logic I suppose.

The case is: I need to archive all files for one day. The last file will have a S3 key with yyyy.mm.dd-hh-mm-ss in it. 

If I find the condition, I'll post it here

**Comment by bertpersyn** [comment]
Hi, this is what I ended up with:

```
pipeline:
  processors:
  - type: batch
    batch:
      condition:
        type: metadata
        metadata:
          operator: equals
          part: 0
          key: last_key
          arg: true
  - type: archive
    archive:
      format: tar
      path: ${!metadata:s3_key}
  - type: compress
    compress:
      algorithm: gzip
```
After S3 received all keys, I've put `true` on the last element of the `targetKeys` array.

And when creating the message, I just put the key on the meta, like you instructed:

`meta.Set("last_key", strconv.FormatBool(target.lastKey)) `

Thanks!
