### ISSUE TITLE
How to split single json object into mutliple parts

### ISSUE THREAD

**Issue by MilanJaro** [Jeffail/benthos#149]
Hey benthos gurus,

I am touching the tool for the first time and cannot figure out how to split single json object into mutliple parts.

Use case:
* input: http_server
* output: kafka
* pipeline: should split top level json list and generate single json objects into kafka topic

Sample json: {"object-list": [{"object": "first object"}, {"object": "second object"}]}

From this json I want to send to kafka topic the two separate messages:
msg1: {“object”:”first object”}
msg2: {“object”:”second object”}
```
pipeline:
  threads: 1
  processors:
  - type: process_map
    process_map:
      premap:
        .: object-list
      processors:
      - type: split
        split:
          size: 1
```
As a result I am still getting single message in the kafka … like this one -> “[{"object ": "first object "}, {" object ": "second object "}]”

Can you advise how to make proper pipeline?

Thanks,
Milan

**Comment by Jeffail** [comment]
Hey @MilanJaro, you can solve this by duplicating the message with `select_parts`, then you extract the part of the payload you're interested in with two `jmespath` queries:

``` yaml
pipeline:
  processors:
  - type: select_parts
    select_parts:
      parts: [0,0]
  - type: jmespath
    jmespath:
      parts: [0]
      query: '"object-list"[0]'
  - type: jmespath
    jmespath:
      parts: [1]
      query: '"object-list"[1]'
  - type: split
```

The `select_parts` processor creates a message batch of size two which is why we're able to target the `jmespath` processors at specific messages by their index. I follow up here with a `split` processor in order to break the batch back into individual messages, but since the destination is Kafka you can probably skip this stage as it's safe to send messages to Kafka as a batch.

**Comment by MilanJaro** [comment]
Thanks a lot for quick reply. My mistake, the description of the problem was not good. I didn't mention that I don't know in advance how many objects will be in object-list. So proper definition of the object-list is something like:

{"object-list": [{"object": "object 1"}, {"object": "object 2"}, ..., {"object": "object N "}]}

So I need to implement some kind of generic loop, which will iterate over all objects in the object-list. Is this solvable?

Thanks,
Milan

**Comment by Jeffail** [comment]
Ah that makes it more interesting! There wasn't a particularly nice way of doing this so I've added a `json_array` format to the archive and unarchive processors: https://github.com/Jeffail/benthos/commit/b1dd2a784ee1b0feb1cffaae8c991beeaa1e22a0

Which means you can now solve your problem with this config:

``` yaml
pipeline:
  processors:
  - type: json
    json:
      operator: select
      path: object-list
  - type: unarchive
    unarchive:
      format: json_array
  - type: split
```
