### ISSUE TITLE
Broker output is unable to parse plugin

### ISSUE THREAD

**Issue by asiragusa** [Jeffail/benthos#154]
I tried to use the `broker` output with a custom plugin but, instead of the correct struct, I receive a `map[interface{}]interface{}`. Digging into the code, I found out that it's due to https://github.com/Jeffail/benthos/blob/master/lib/output/broker_out_common.go#L84

The following config structure might fix the issue (even if it is a BC):
```yaml
output:
  type: broker
  broker:
    pattern: fan_out
    outputs:
    - output:
        type: foo
        foo:
          foo_field_1: value1
    - output:
        type: bar
        bar:
          bar_field_1: value2
          bar_field_2: value3
    - output:
        type: baz
        baz:
          baz_field_1: value4
      processors:
      - type: baz_processor
  processors:
  - type: some_processor
```
