### ISSUE TITLE
Allow for switch operator to be non-blocking

### ISSUE THREAD

**Issue by danrubenstein** [Jeffail/benthos#163]
Hi!

According to the [docs](https://github.com/Jeffail/benthos/tree/master/docs/outputs#switch), for an output that is the child of the `switch` output:
>  if an output fails to send a message, it will be retried continuously until completion or service shut down.

I can see how this would make sense if you don't want to pass through a bunch of messages only to have them error out, and thus keep the inputs from being read off of. However, in the case where a single misconfigured record enters the stream, it can prevent potentially good records behind it from being processed, especially if the output relies on, say, the `json_field`operator to pull something out of the message, and the errant (or perhaps missing) data.

This would be especially valuable in the case where one could wrap a `switch` operator with a `try`, and would hope that the switch would return back the error. (Yes, admittedly, one can already put a `try` inside a `switch`, but it does feel like both should be possible).

The proposal here is for the switch configuration to accept a `blocking` configuration (naming is subject to change) that is a boolean for whether or not suboutputs of a switch will return a transaction back as an error. The defaults here would stay the same (e.g., the child output would continue to block).

One complicating factor here - 

In the case where the `fallthrough` configuration is used, and the message goes to multiple outputs, one output could fail, while the other could succeed. Should this count as a failure (and the response channel should be passed back to with `response.NewError`) or success (`response.NewAck`). Alternatively, I could imagine a three part configuration with "none", "all", or "any".

Let me know what you think - thanks!

**Comment by Jeffail** [comment]
Hey @danrubenstein, seems sensible. I think it would be sufficient to add a boolean config value per output of the `switch`, not sure what I would call it, maybe something like `abandon_on_error`. The idea being you could then choose whether a specific output has its own dead letter queue by having a nested try broker, uses a general dead letter queue outside the `switch`, or none at all.

**Comment by Jeffail** [comment]
Hey @danrubenstein, trying out a different approach. Got a branch here with a `drop_on_error` output type that wraps a child, if the child output fails to dispatch a message then it is simply dropped, as if it were successful.

**Comment by Jeffail** [comment]
So the new `drop_on_error` output solves one problem, which is "I want to output to foo and bar, but if foo fails then I don't want to block forever":

``` yaml
output:
  type: switch
  switch:
    outputs:
    - condition:
        type: jmespath
        jmespath:
          query: "foo.bar == 'baz'"
      fallthrough: true
      output:
        type: drop_on_error
        drop_on_error:
          type: retry
          retry:
            max_retries: 2
            output:
              type: foo
    - output:
        type: bar
```
Next is to solve for "I want to output to foo and bar, but if either fails then i want to fallback to baz", in order to do that you would need to configure a try broker for both foo and bar outputs with a duplicate config for baz. I'll add a field to the `switch` output to exit immediately out of errors which would solve this.
