### ISSUE TITLE
Configuration from environment variable

### ISSUE THREAD

**Issue by asiragusa** [Jeffail/benthos#177]
Hi Jeff, I would be able to read the whole configuration file via an environment variable, it can be useful for local testing with docker-compose. 

Is it be possible to add an option to use benthos like this:

```
yaml
  benthos:
    image: jeffail/benthos
    environment:
      YAML_CONFIG: |-
        input:
          type: http_server
          http_server:
            address: "0.0.0.0:8080"
        output:
          type: stdout
```

Thanks!

**Comment by Jeffail** [comment]
Hey @asiragusa, you can kind of achieve this by having a config file (maybe called `env.yaml`) with the contents `${YAML_CONFIG}`. Place that config file in your docker-compose directory and then add it as a volume:

``` yaml
benthos:
  image: jeffail/benthos
  volumes:
    - ./env.yaml:/benthos.yaml
  environment:
    YAML_CONFIG: |-
      input:
        type: http_server
        http_server:
          address: "0.0.0.0:8080"
      output:
        type: stdout
```

Would that work for you?
