### ISSUE TITLE
abort on failure

### ISSUE THREAD

**Issue by jhgx** [Jeffail/benthos#178]
Is there a recommended method of aborting a benthos stream when a processor fails?  The intent would be to block inputs from progressing when non-recoverable processing errors occur.

The [error handling](https://github.com/Jeffail/benthos/blob/master/docs/error_handling.md) docs address ignoring, handling, or rerouting processor errors, but all of these options will allow inputs to continue with reads/acknowledgements.

It may be possible to use a `catch` to forward to a `sleep` processor with a very large duration, effectively stopping the processor. Probably not ideal though, as the processor would still be alive but in a defunct state.

**Comment by Jeffail** [comment]
Hey @jhgx, you could make a hacky version of this by routing failed messages to an output that can never succeed. For example:

``` yaml
```

**Comment by Jeffail** [comment]
I think a 'proper' solution for this kind of behaviour would be to introduce some sort of `do_while` processor, where whilst a condition is true a list of child processors will continue to be executed. That would enable you to configure something like this:

``` yaml
- type: do_while
  do_while:
    processors:
    - type: catch
    - type: foo
    condition:
      type: any
      any:
        type: processor_failed
```

With something like this the pipeline will block and reattempt your processor for as long as it fails. Would that solve your use case?

**Comment by jhgx** [comment]
In my case, if the processor fails once then it will always fail, so there's no need to reattempt processing.

Would something like this work?

```
processors:
- type: foo
- type: bar
- type: catch
  catch:
  - type: log    # log the failures
  - type: abort  # kill the processor
```

If `foo` or `bar` run into any processing errors, a new `abort` processor is triggered which (somehow) kills the processor.  All is takes is one bad message/part to take the whole thing down.  The message is not ack'd and the input never progresses.

I can't decide if it makes sense for the entire pipeline to shutdown when a processor aborts, or if it should keep on running without the processor.  It may be nice if this behavior could be driven via the abort processor's config.

**Comment by Jeffail** [comment]
Hey @jhgx, I've just added a new `while` processor in v1.10.0 that allows you to do this:

``` yaml
  - type: processor_that_might_fail
  - type: catch
    catch:
    - type: log
      log:
        message: "Message failed with error: ${!metadata:benthos_processing_failed}, content: '${!content}', blocking pipeline"
    - type: while
      while:
        condition:
          type: static
          static: true
        processors:
        - type: sleep
          sleep:
            duration: 1m
```

**Comment by jhgx** [comment]
Nice!  That looks like a good way to do a general purpose retry.  To (practically) avoid retries I could set the sleep to a huge duration.

Maybe the idea of a total abort doesn't make sense if benthos prefers to keep itself running in the face of failure.  However, I see that it is possible for inputs to give up and die.  For example:

https://github.com/Jeffail/benthos/blob/c91d44bcdf4179c1b9142ca14e8259e8d5b417ec/lib/input/reader.go#L147

and:

https://github.com/Jeffail/benthos/blob/c91d44bcdf4179c1b9142ca14e8259e8d5b417ec/lib/input/reader.go#L175

IIUC the effect of this depends on your configuration: if you only have a single input and it dies, this will take down the whole pipeline.  If you have two inputs under a broker and one of the two inputs dies, the pipeline will keep running in a degraded state.

One more idea to throw out there: would it make sense to allow inputs to be configured to respond to failures:

```
input:
  type: ...
  stop_on_error: true
```

Here if the input gets back an error response from anything downstream, it can optionally stop producing and exit.  And maybe a global setting could control if the entire pipeline gets shutdown when any input stops on error.

For my case, I'd then need a way to send an error response to the input on processor failure:

```
processors:
- type: foo
- type: bar
- type: catch
  catch:
  - type: log    # log the failures
  - type: error  # a new processor that returns an error response
```

This is similar to what I proposed before, except that the input is responsible for controlling when it stops, and downstream processors always just do their work and return a result.  I think this probably fits into the transaction model better.

I may have gone off in the weeds a bit so feel free to close.

And thank you for your help and nice work.
