### ISSUE TITLE
Support for S3 Sync in S3 output processor

### ISSUE THREAD

**Issue by orsigiorgio** [Jeffail/benthos#181]
I'd like to have an option to specify whether I want the S3 output processor to overwrite an existing object or not. Basically I'd like to have a way to simulate an S3 sync.

maybe something like this.

```
- type: s3
  s3:
    method: [cp|sync]
    region:
    bucket:
    path:
    timeout:
    credentials:
      id: 
      secret:
  processors:
    ...
```
