### ISSUE TITLE
Lambda distribution of Benthos

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#185]
If we were to deploy a Benthos instance as an AWS lambda function, where invocations result in a message batch being propagated down a configured Benthos pipeline, what would be the ideal way to package such a Benthos instance?

## Lambda Input Type

PR https://github.com/Jeffail/benthos/pull/184 is a good example of having invocations represented as a configured input, which allows a a standard Benthos binary to be deployed as a lamba. However, there are some possibilities with this setup which could cause confusion or broken behaviour. For example, what happens when you combine a broker with this input type and deploy it?

``` yaml
type: broker
broker:
  inputs:
  - type: lambda
  - type: kafka_balanced
    kafka_balanced:
      ...
```

Would something like the above function as we might expect as a lambda function?

``` yaml
type: broker
broker:
  copies: 10
  inputs:
  - type: lambda
```

What would we expect to happen here?

## Separate Distribution

Alternatively, we could distribute a separate binary to normal Benthos that is specifically designed to work as a lambda function. In which case we would not expect an input section to be configured at all, and the way in which configuration is provided to this distribution would be more convenient for lambda deployments.
