### ISSUE TITLE
Proposal: Notifications when an output is written

### ISSUE THREAD

**Issue by huttotw** [Jeffail/benthos#195]
We are using the S3 output, and it is working great. We are interested in receiving some sort of signal when a file is uploaded to S3, maybe to then trigger a load into Redshift.

I am not sure that this fits into outputs as they are defined today, perhaps there can be a new top level key introduced to `outputs`, for instance:

```yaml
output:
  type: foo
  foo:
    bar: baz
  processors:
  - type: qux
  notifications:
  - type: http
    http:
      url: http://localhost:3000/v1/webhooks/benthos
```

The delivered payload may look something like:
```json
{
   "status": "finished",
   "output": {
       "type": "s3",
       "filename": "this/is/my/file.txt"
   } 
}
```

Of course in the AWS use cases this can probably be accomplished by some version of Lambda craziness, but the ease of running Benthos locally really attracts me to this method.

Excited to hear other's opinions, or if there is a way to accomplish this with the existing core concepts!

**Comment by Jeffail** [comment]
Hey @huttotw,

You caught me at a good time so I've got three juicy options for you to salivate over.

## Solution 1: Pure Benthos but with caveats

You can partially solve this (with caveats) using a [`broker`](https://docs.benthos.dev/outputs/#broker) output with the `fan_out` pattern:

``` yaml
output:
  type: broker
  broker:
    pattern: fan_out
    outputs:
    - type: foo
      foo:
        bar: baz
      processors:
      - type: qux
    - type: http
      http:
        url: http://localhost:3000/v1/webhooks/benthos
      procesors:
      - type: text
        text:
          operator: set
          value: '{"status":"finished","output":{"filename":"${!metadata:filename}"}}'
```

Each message will get sent to both outputs, which are your bucket and notification webhook. The output specific processors allow you to modify the payload to become the notification format. However, there are two caveats with this approach.

Firstly, if an output of a `fan_out` broker fails to deliver a message then it is reattempted indefinitely until success (or Benthos is shut down), during this retry loop the input message is not acknowledged.

This behavior is in order to prevent wider retry loops where messages will be sent multiple times to an output of the broker that is healthy. In your case this means your pipeline will block and Benthos will apply back pressure if your webhook target goes offline (this also might be the behavior you desire, depending on your requirements.)

Secondly, the broker dispatches the messages to outputs in parallel, so it's possible that your notification might be received before the payload has finished uploading to S3, this problem is amplified if there are also connectivity or access problems with the bucket.

You could potentially mitigate this problem on the webhook side by returning a bad status code (maybe 404?) when the bucket item isn't found. This would create a loop where Benthos resends the notification until your service finds it in the bucket. However, it also means blocking the request on your bucket download, which might not be feasible depending on your throughput and latency requirements as it would apply back pressure to Benthos (which gets propagated to the input source).

## Solution 2: Use SQS

Another solution, which is probably the one I would recommend for most use cases, would be to hook SQS notifications to your S3 bucket directly (a guide can be found here: https://docs.aws.amazon.com/AmazonS3/latest/dev/ways-to-add-notification-config-to-bucket.html), this has the following advantages:

- Your notifications are stored in a queue
- The connection Between Benthos and the S3 bucket is isolated and therefore can't be frustrated by the notification pipeline
- AWS components are probably in a better position to tell you exactly when an item in a bucket is both uploaded and ready to consume

If you need the notifications to come via a webhook then you can always deploy a Benthos pipeline that writes SQS messages to an HTTP output. However, this is yet more components to manage so once again it comes down to your personal requirements.

## Solution 3: Solution 1 with modifications

I can pretty quickly add a new broker pattern called something like `fan_out_sequential` that blocks for each output in sequence until success before moving onto the next. This would prevent notification messages reaching your webhook until the bucket is successfully populated. Let me know if you want to try that out and I'll get it added.
