### ISSUE TITLE
Support fragmenting configs with JSON references

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#198]
It's possible for Benthos configs to become huge and unmanageable. Although this can be solved with third party tooling it would be nice to eliminate that step by adding native support to Benthos either for [JSON references](https://json-spec.readthedocs.io/reference.html) or something similar.

There are libraries for doing this already that can be slotted in: https://github.com/lestrrat-go/jsref. However, since this spec is so large I would be more comfortable starting off with a much more restricted version where only file paths are permitted, we can expand to support the whole spec later on.

I'm therefore proposing the following stages:

1. Add experimental support for limited JSON ref functionality (only supporting file paths)
2. Get feedback over a few weeks. If generally positive move onto 3., otherwise 4.
3. Discuss the need for adding full spec
4. Discuss alternative solutions

Once we've implemented 1. it would be possible to create a snippet config called something like `foo.yaml`:

``` yaml
type: process_map
process_map:
  premap:
    id: foo
    content: .
  processors:
  - type: parallel
    parallel:
      processors:
      - type: cache
        cache:
          operator: add
          key: ${!json_field:id}
          value: ${!content}
          cache: objects
  postmap:
    ignored: throw.result.away
```

And embed it within a larger config like this:

``` yaml
input:
  type: foo
  foo: {}

pipeline:
  processors:
  - type: decompress
    decompress:
      algorithm: gzip
 
  - type: unarchive
    unarchive:
      format: tar

  - "$ref": "./foo.yaml"

output:
  type: bar
  bar: {}

resources:
  caches:
    objects:
      type: baz
      baz: {}
```

which would expand to:

``` yaml
input:
  type: foo
  foo: {}

pipeline:
  processors:
  - type: decompress
    decompress:
      algorithm: gzip
 
  - type: unarchive
    unarchive:
      format: tar

  - type: process_map
    process_map:
      premap:
        id: foo
        content: .
      processors:
      - type: parallel
        parallel:
          processors:
          - type: cache
            cache:
              operator: add
              key: ${!json_field:id}
              value: ${!content}
              cache: objects
      postmap:
        ignored: throw.result.away

output:
  type: bar
  bar: {}

resources:
  caches:
    objects:
      type: baz
      baz: {}
```

Which I believe gets us most of the way.

**Comment by Jeffail** [comment]
Working off a branch: https://github.com/Jeffail/benthos/tree/feature/json-refs

**Comment by Jeffail** [comment]
Looks good so far, need to test:

- Interactions between YAML anchors and references
- Env var interpolation

Need to implement:

- Protection against reference loops

**Comment by Jeffail** [comment]
After playing with my initial POC I decided that fragments are going to be necessary so I've implemented them. This also means that it's possible to reference fields within the same document, similar to YAML anchors. I'm not a huge fan of having two ways of achieving the same goal but I believe it'll make working with fragmented files much easier as it allows you to have a fully functioning snippet:

``` yaml
pipeline:
  processors:
  - type: foo
    foo:
      bar: baz
```

Which is testable on its own, but can also be included in a larger configuration file:

``` yaml
input:
  type: qux

pipeline:
  processors:
  - $ref: ./foo.yaml#/pipeline/processors/0

output:
  type: quz
```
