### ISSUE TITLE
Support dynamic content type and encoding for s3 output

### ISSUE THREAD

**Issue by razor-x** [Jeffail/benthos#203]
Looking for something like 

```yaml
input:
  type: s3
  s3:
    bucket: ${SOURCE_BUCKET}
    sqs_url: ${SOURCE_QUEUE}
    sqs_body_path: Records.s3.object.key
    sqs_bucket_path: Records.s3.object.bucket
    sqs_max_messages: 10
    timeout: 15s
    download_manager:
      enabled: false

output:
  type: s3
  s3:
    bucket: ${SINK_BUCKET}
    path: ${!metadata:s3_key}
    # Add this part below
    content_type: ${!metadata:s3_content_type}
    content_encoding: ${!metadata:s3_content_encoding}
```
