### ISSUE TITLE
Write entire JSON to DynamoDb

### ISSUE THREAD

**Issue by razor-x** [Jeffail/benthos#204]
Given

```yaml
    outputs:
      - type: dynamodb
        dynamodb:
          table: ${DB_TABLE}
          string_columns: 
            foo: ${!json_field:bar}
```

I want to write all fields, not just `foo`, as a proper nested structure to the DB without needing to enumerate them, for example

```yaml
    outputs:
      - type: dynamodb
        dynamodb:
          table: ${DB_TABLE}
          string_columns: ${!merge_all_json_fields} # ??
```

**Comment by Jeffail** [comment]
Got this on a branch, needs testing: https://github.com/Jeffail/benthos/tree/feature/json-map-columns.

And will allow you to configure like this:

``` yaml
    outputs:
      - type: dynamodb
        dynamodb:
          table: ${DB_TABLE}
          json_map_columns:
            "": .
```

Which walks the root of the JSON document and writes fields to the root of the dynamo item. This also allows you to specify column names for mixing explicit column values:

``` yaml
    outputs:
      - type: dynamodb
        dynamodb:
          table: ${DB_TABLE}
          string_columns:
            id: ${!metadata:id}
          json_map_columns:
            document: .
```

**Comment by Jeffail** [comment]
Implemented: https://github.com/Jeffail/benthos/commit/3b389a253165167dbd6f8a602cce5ae59e33daf7
Released: https://github.com/Jeffail/benthos/releases/tag/v1.19.0

**Comment by mclark4386** [comment]
If this is bad form let me know and I'll make a separate issue, but I was wondering about doing more or less the same thing with the metadata. Basically I have a message in the content and then I have all the attributes in the metadata, so for outputting it to dynamodb I want to have the structure look a bit like this:
```
outputs:
      - type: dynamodb
        dynamodb:
          table: ${DB_TABLE}
          string_columns:
            full_content: ${!content}
          json_map_columns:
            .: metadata_json_object
```

That way if the attributes change it will unfold them as well instead of having to update the config everytime with update the schema.

**Comment by Jeffail** [comment]
Hey @mclark4386, have you considered building the metadata fields into a JSON payload first? It would go something like:

```yaml
  - jmespath:
      query: |
        {
          content: @,
          metadata_json_object: "temporary"
        }

  - process_field:
      path: metadata_json_object
      result_type: object
      processors:
      - text:
          operator: set
          value: ${!metadata_json_object}

output:
  dynamodb:
    string_columns:
      full_content: ${!json_field:content}
    json_map_columns:
      .: metadata_json_object
 
```
