### ISSUE TITLE
Config type inference

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#209]
I'm working on a branch that implements type inference for all native Benthos components (everything except plugins). It's quickest to illiustrate with an example, the following valid config:

``` yaml
input:
  type: kafka_balanced
  kafka_balanced:
    addresses: [ "localhost:6379" ]
    topics: [ "foo" ]

pipeline:
  processors:
  - type: process_batch
    process_batch:
    - type: jmespath
      jmespath:
        query: 'foo'

output:
  type: file
  file:
    path: foo.txt
```

Can now also be written more concisely as:

``` yaml
input:
  kafka_balanced:
    addresses: [ "localhost:6379" ]
    topics: [ "foo" ]

pipeline:
  processors:
  - process_batch:
    - jmespath:
        query: 'foo'

output:
  file:
    path: foo.txt
```

Both config snippets will be considered valid. However, the longer form including explicit `type` fields will always be the true 'normalised' schema and will therefore be printed in documentation, `--print-yaml` and `--print-json` calls.

The implementation involves scanning config objects for keys that are valid types, thus if more than one valid type is present this causes an error. For example, running the following config:

``` yaml
input:
  stdin:
    multipart: true
  kafka_balanced:
    topics: [ "foo" ]
```
Gives this:
``` sh
$ benthos -c ./abovesnippet.yaml
Configuration file read error: unable to infer type, multiple candidates 'kafka_balanced' and 'stdin'
```

Note that due to the `yaml.v2` package not exposing enough info in our marshal override we can't report the line number/column where the problem occurs. This information is available in the new `yaml.v3` package.  I'm currently torn between releasing this with `yaml.v2` and exposing this poor error message or moving to the new `yaml.v3` API with the risk of regressions.

**Comment by Jeffail** [comment]
Branch: https://github.com/Jeffail/benthos/tree/feature/type-inference

**Comment by Jeffail** [comment]
I've taken a stab at updating examples, would be interested to hear whether or not people think they are clear enough with inference?

https://github.com/Jeffail/benthos/blob/feature/type-inference/docs/cookbooks

**Comment by Jeffail** [comment]
TODO optional extras:
- Upgrade to `yaml.v3`
- Update more snippets in docs to use inference

**Comment by Jeffail** [comment]
CALL FOR TESTERS

I've moved development to a beta branch https://github.com/Jeffail/benthos/tree/beta, which kicks off docker builds with the tag [`beta`](https://cloud.docker.com/repository/docker/jeffail/benthos/tags).

So far it's looking good based on my own testing but it would be great to have others trying this build out. If you intend to do so please let me know.

**Comment by kconwayatlassian** [comment]
> thus if more than one valid type is present this causes an error

Does the parsing switch into a "simple mode" when there is no explicit `type` definition? How can we detect the difference between a `type` not given and someone relying on the default `type` for a given section?

I'm mostly curious about something like https://github.com/Jeffail/benthos/blob/master/config/env/default.yaml. Does this configuration become invalid?

**Comment by Jeffail** [comment]
@kconwayatlassian, the environment config will be fine as it has an explicit `type` field, in which case the parser will always go with whatever that field declares.

If an existing config contains an empty object (no `type` value and also no config fields) like this:

``` yaml
pipeline:
  processors:
  - {}
```

Then it remains as it was, Benthos interprets this as a `bounds_check` processor with default field values.

There is one possible regression which is if a user has concocted something like this:

``` yaml
pipeline:
  processors:
  - # type: text
    text:
      operator: set
      value: "delete all your content"
```

And has deployed it, relying on the fact that a `processor` defaults at type `bounds_check`, but for some reason leaving the artifact of an unused component in their config. I would consider this a broken configuration file, but since it's also currently accepted by Benthos I can't rule out that it exists in the wild.

I'm not sure if this should be a major version bump, I'd rather avoid forcing users to scan the changelog for a migration path for a change that really shouldn't impact anyone.
