### ISSUE TITLE
Escape/Unescape json

### ISSUE THREAD

**Issue by donaherc** [Jeffail/benthos#218]
Hello! Is there currently a mechanism to escape or unescape json strings embedded inside JSON within either benthos or JMESPath? I dug into both the source and the docs but couldn't find a place where that functionality is provided. I'm willing to submit a PR to either the `json` or `text` processors to provided this functionality if it currently doesn't exist and you think it'd be valuable.

**Comment by donaherc** [comment]
Oh! For future reference, the `text` operator `unquote` can be used to unescape json, then message can be passed to subsequent processors. For example:

```
- type: jmespath
    jmespath:
      parts: []
      query: "message"
  - type: text
    text:
      operator: unquote
      parts: []
  - type: jmespath
    jmespath:
      parts: []
      query: "eventType"
```
This is actually fairly common inside AWS Event types like Kinesis Events or CloudwatchLogEvents if passed via lambda.

Thanks for writing such a flexible tool!
