### ISSUE TITLE
PSA: Broker types (fan_in, fan_out, round_robin) are changing.

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#23]
Broker types are going to be merged into a single `broker` input and output type, where the pattern will be specified as a field. There are a number of reasons for this change, mostly related to making documentation and config discovery simpler.

Pull request: https://github.com/Jeffail/benthos/pull/22

## Updating your configs

Wherever you were using the `fan_in` type simply swap it with `broker`:

``` yaml
type: fan_in
fan_in:
  inputs:
```

To:

``` yaml
type: broker
broker:
  inputs:
```

Wherever you were using `fan_out` or `round_robin` you do the same, but must also specify the pattern of the broker as there are multiple options:

``` yaml
type: fan_out
fan_out:
  outputs:
```

To:

``` yaml
type: broker
broker:
  pattern: fan_out
  outputs:
```
