### ISSUE TITLE
Storing response codes from HTTP requests in metadata

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#233]
You can kind of hack yourself a response code check when you use an `http` processor:

```yaml
- http:
    parallel: true
    request:
        url: "TODO"
        verb: GET
- for_each:
    - conditional:
        condition:
        check_interpolation:
            value: ${!error}
            condition:
            text:
                operator: contains
                arg: "(404)"
```

However, this is pretty nasty and prone to long term problems. It's also exclusive to the `http` processor, but it would also be nice to store response codes from the `http_client` output and perhaps more output destinations. This would allow us to build DLQ output destinations based on the _cause_ of the failure at our chosen output.
