### ISSUE TITLE
Kafka Input only gets the topic messages, does not get keys

### ISSUE THREAD

**Issue by chris-vest** [Jeffail/benthos#236]
Currently the input of type Kafka will only get the message from a given topic, is there any plan to enable also getting the keys?

My use case is very simply that I need to back up the `_schemas` topic, but then in order to restore I need to be able to produce those messages with the same key they were originally produced with.

Would you accept a PR for this?

**Comment by Jeffail** [comment]
Hey @chris-vest, messages consumed via Kafka have the key stored in the metadata field `kafka_key`. Where are you storing the backup? Depending on where you're putting the data we can work out how best to store/retrieve the keys.

**Comment by chris-vest** [comment]
@Jeffail Thanks for the quick response! The backups are currently going to s3, which is working very nicely. It's the restore process which is causing issues. Can I just reference `kafka_key` in the `key` config of the restore process? Something like this:

```
data:
  benthos.yaml: |
    input:
      type: s3
      s3:
        bucket: "schemas-backup"
        delete_objects: false
        download_manager:
          enabled: true
        force_path_style_urls: false
        max_batch_count: 1
        prefix: "benthos/_schemas"
        region: eu-west-1
        retries: 3
        timeout: 5s
    output:
      type: kafka
      kafka:
        addresses:
        - broker:9092
        client_id: schemas-restore
        compression: none
        key: "$kafka_key"
        topic: schemas-restore
        max_msg_bytes: 1e+06
        target_version: 2.1.0
```

**Comment by Jeffail** [comment]
Yeah, that's it. The metadata value `kafka_key` should automatically get set on the documents as they are uploaded to your bucket. In the S3 UI it should be listed as something like `x-amz-meta-kafka_key`.

However, when downloading items from your bucket using the download manager these fields aren't retrieved, so for your use case you also need to disable it with:

```yaml
    input:
      type: s3
      s3:
        download_manager:
          enabled: false
```

Then you're able to access it in your output with `${!metadata:kafka_key}`.

**Comment by chris-vest** [comment]
Great, thanks for explaining that! 

I'm now getting this:

```
Failed to send message to kafka: failed to send 1 parts from message: kafka server: Message contents does not match its CRC.
```

I've enabled `logger: level: ALL`, but am not getting any more information than that. Any idea about how I can drill down to the actual issue?

**Comment by Jeffail** [comment]
Is it possible that your payloads are larger than your max size? That's an unfortunately cryptic error message from kafka, found this thread: https://github.com/Shopify/sarama/issues/810

**Comment by chris-vest** [comment]
@Jeffail I was looking into that the other day, could well be the case. Maybe there'll be some more information from the broker logs.

**Comment by chris-vest** [comment]
@Jeffail Really appreciate your help this morning. 

It turned out that the Topic Operator I am using was falsely reporting having set the `max.message.bytes` on the topic I was restoring to, so in fact it was exactly what you said - simply the messages were too big!

**Comment by chris-vest** [comment]
@Jeffail Hi again! 

Just a quick question for you, I was running into the CRC error again: `Message contents does not match its CRC.` I was wondering, when you use s3 as a source and Kafka as a sink, what happens to the metadata attached to the s3 object if you do not reference it in your output configuration??

I.e. I'm only using the `kafka_key` metadata value for the Kafka message key value, but ignoring all the other ones - are those metadata values included somewhere in the message anyway?

Asking simply because when I try to "restore" from the s3 source to a new Kafka cluster, and the topic name does not match the `kafka_topic` metadata value, that is when I see the CRC error.

**Comment by Jeffail** [comment]
Hey @chris-vest, yeah any metadata attached to the message should get copied to the new bucket item. You should be able to access the `kafka_topic` metadata field whilst consuming from your `s3` source.

**Comment by chris-vest** [comment]
Thanks! So the pipeline looks like this -

Backup: Kafka --> s3
Restore: s3 --> Kafka

During the restore process, it seems like Benthos adds a number of headers to the message - can you confirm that this is the case?

**Comment by Jeffail** [comment]
Yeah, that'll naturally happen, if you want to clear your headers you can do a prefix based deletion of metadata like this:

``` yaml
metadata:
  operator: delete_prefix
  key: s3_
```

That'll remove all S3 headers added by Benthos, you can also remove the `kafka_*` headers which are remnants from the original `kafka -> s3` pipeline. However, that'll also remove `kafka_key`, which you are probably relying on.

**Comment by chris-vest** [comment]
In my example then, I'm adding that to the restore process. Something like this?

```
    input:
      type: s3
      s3:
        bucket: "super-secret"
        delete_objects: false
        download_manager:
          enabled: false
        force_path_style_urls: false
        max_batch_count: 1
        prefix: "benthos/_schemas"
        region: eu-west-1
        retries: 3
        timeout: 5s
    pipeline:
      metadata:
        operator: delete_prefix
        key: s3_
    output:
      type: kafka
      kafka:
        addresses:
        - b0:9092
        client_id: benthos-schemas-restore-1
        compression: none
        key: "${!metadata:kafka_key}"
        topic: _schemas
        target_version: 2.1.0

**Comment by Jeffail** [comment]
Here's a version that copies `kafka_key` to `source_key` and deletes all `s3_` and `kafka_` headers. That way you're only adding one extra header from your backup.

```yaml
input:
  type: s3
  s3:
    bucket: "super-secret"
    delete_objects: false
    download_manager:
      enabled: false
    force_path_style_urls: false
    max_batch_count: 1
    prefix: "benthos/_schemas"
    region: eu-west-1
    retries: 3
    timeout: 5s
pipeline:
  processors:
  - metadata:
      operator: set
      key: source_key
      value: ${!metadata:kafka_key}
  - metadata:
      operator: delete_prefix
      key: s3_
  - metadata:
      operator: delete_prefix
      key: kafka_
output:
  type: kafka
  kafka:
    addresses:
    - b0:9092
    client_id: benthos-schemas-restore-1
    compression: none
    key: "${!metadata:source_key}"
    topic: _schemas
    target_version: 2.1.0
```
