### ISSUE TITLE
Question: how to have a conditional based on json array length?

### ISSUE THREAD

**Issue by bkcsfi** [Jeffail/benthos#242]
Hi, I have a DAG/workflow and I need to detect messages that have a json array with length > 0.

based on http://jmespath.org/specification.html#length  and the example jmespath condition `a == 'foo'` I kind of expect this to work:

```yaml
- type: conditional
  conditional:
    condition:
      type: jmespath
      jmespath:
        query: "length(errors) > 0"
```
But this gives a syntax error:
```
Error: failed to create pipeline: failed to create processor 'conditional': failed to compile JMESPath query: SyntaxError: Invalid token: tNumber
```

I've tried many variations but just can't seem to arrive at a solution that will allow me to test the length of an array in a conditional.

Do you have any suggestions?

here's an example on the lab

https://lab.benthos.dev/l/coFwGskH3Uc

Thanks,
