### ISSUE TITLE
Is there a way to use the the group_by_value processor with multiple values?

### ISSUE THREAD

**Issue by meganfeichtel** [Jeffail/benthos#244]
I am trying to write out data into a long term storage S3 bucket location. I want to partition by a `sourceID` and by an `eventType` - is there a way to pass in multiple fields to the group_by_value processor to be able to partition my data by both of those fields?

Here's the processors section of my yaml file for reference. Note that I want to add `eventType` to the group_by_value call below:

```
pipeline:
  processors:
    - type: metadata
      metadata:
        key: source
        operator: set
        parts: []
        value: ${!json_field:source}
    - type: metadata
      metadata:
        key: eventType
        operator: set
        parts: []
        value: ${!json_field:event.event}
    - type: json
      json:
        operator: select
        parts: []
        path: event
    - type: batch
      batch:
        byte_size: 1.28e+8
        period: 5m
    - type: group_by_value
      group_by_value:
        value: ${!metadata:source}
    - type: archive
      archive:
        format: lines
    - type: compress
      compress:
        algorithm: gzip
        level: -1
        parts: []
```

**Comment by Jeffail** [comment]
Hey @meganfeichtel,

The `value` field can have any number of interpolation functions in there, so in your case I would do something like:

```yaml
    - type: group_by_value
      group_by_value:
        value: "${!metadata:source}-${!metadata:eventType}"
```

You could also remove the `metadata` processors and use the `json_field` interpolations directly in `group_by`:

```yaml
    - type: group_by_value
      group_by_value:
        value: "${!json_field:source}-${!json_field:event.event}"
```

**Comment by meganfeichtel** [comment]
thanks for the quick response! I will try that

**Comment by meganfeichtel** [comment]
@Jeffail how would you go about referencing multiple metadata values? above, I tried putting in 2 metadata blocks, but that just ended with the s3 files populating the first value (source) but not the second (eventType)

**Comment by meganfeichtel** [comment]
Also note that the second value is nested-json, so that could be where this is breaking  - ${!json_field:event.event} where there is an event json field that contains a json blob with a nested field also named `event`

**Comment by Jeffail** [comment]
@meganfeichtel, got an example document? You might need to do something like extract the value of the nested field into a metadata value then reference it that way. Maybe something like this:

```yaml
pipeline:
  processors:
    - process_field:
        path: event
        result_type: discard
        processors:
          - metadata:
              operator: set
              key: extracted_event
              value: ${!json_field:event}
    - log:
        message: "Example: ${!json_field:foo}-${!metadata:extracted_event}"
```

**Comment by meganfeichtel** [comment]
@Jeffail Here's an example json snippet of what I'm describing: 

`{ 
   “source”:”123456”,
   “event”:{ 
      “name”:”abc”,
      “id”:”123”,
      "sent":"2019-01-01T23:59:00.535Z"
      },
   "received":"2019-01-01T23:59:00.559Z"
}
`

I want to parse out the files in s3 by the source, event name, and sent. but the "name" and "sent" fields are nested within the "event" json blob.

**Comment by Jeffail** [comment]
Hey @meganfeichtel, the `json_field` function uses dot path notation for accessing nested paths. I would solve that particular part by setting a metadata field with a combination of json interpolations:

```yaml
pipeline:
  processors:
    - metadata:
        operator: set
        key: target_path
        value: "${!json_field:source}/${!json_field:event.name}/${!json_field:event.sent}"
    # Other stuff
output:
  s3:
    bucket: foo
    path: ${!metadata:target_path}
```
