### ISSUE TITLE
Output as CSV?

### ISSUE THREAD

**Issue by epmills** [Jeffail/benthos#247]
Struggling today to find a way to output the result of a pipeline as CSV.
My thought was to use the `awk` processor with a codec of _json_ and the `json_field` function but without luck.
Am I missing something obvious? TiA!

**Comment by Jeffail** [comment]
Hey @epmills,

You could do it with the `text` processor and function interpolations:

```yaml
text:
  operator: set
  value: "${!json_field:foo.bar},${!json_field:baz},${!metadata:bar}"
```

Or, using the `awk` processor, you can use the [`json_get` function](https://docs.benthos.dev/processors/awk_functions/#json-functions):

```yaml
awk:
  codec: none
  program: |
    {
      print json_get("foo.bar")","json_get("baz")","metadata_get("bar")
    }
```

For that function you don't actually need the `json` codec.
