### ISSUE TITLE
question: error handling,  finally and raise (or throw)

### ISSUE THREAD

**Issue by bkcsfi** [Jeffail/benthos#248]
I wish to execute a pipeline step for messages whether or not the processor_failed condition has been set.

Would this work since there's no 'finally' condition?

```
    - for_each:
        - conditional:
            condition:
              or:
                - type: processor_failed
                - type: not
                  not:
                    type: processor_failed
            processors: []
```

After a subprocess has completed, the child pipeline may wish to raise or throw  an error.

Is it possible to set the processor_failed condition through a processor, something like this:

```
type: metadata
metadata:
  key: error
  operator: set
  parts: []
  value: "my error message"
```

**Comment by Jeffail** [comment]
Hey @bkcsfi, not sure I understand what you mean by a "finally" condition in this context, could you explain in more detail?

The other part of your question is possible, if you set the metadata field `benthos_processing_failed` then it'll be interpreted the same as a regular Benthos error.

**Comment by bkcsfi** [comment]
Hi, 

Benthos has processors 'try' and 'catch'. But it seems to be missing a construct similar to 'finally'.

for example in python I might have:

```python
try:
  something_that_might_fail()
except  ValueError: # catch
  report_error()
finally:
   cleanup_resources()
```
where the function `cleanup_resources()` is always executed whether or not an exception occurred in the try statement.

Further, the finally statement does not clear the error condition, so a 'higher up/subsequent' catch processor would still be activated if an error condition had been set in the try statement.

What I'm trying to do is simulate a 'finally' processor by combining a processor_failed condition and a not processor_failed condition in an 'or' clause so that the processor is run for every message, regardless if the error condition is set and also to NOT clear the error condition.

I'm trying this because on the error handling page docs it states that to execute a process when processor_failed is set and to NOT clear the error flag, one must use a for_each with a processor_failed condition.

a specific use-case is related to the config I uploaded in the other issue. I have a dag that creates resources that must be cleaned up. After the dag the cleanup process must run on every message, regardless if there was an error or not. After the cleanup process a later conditional looks for processor_failed to take special action, hence the cleanup process should not clear the error condition on the message.

In a way, this use-case workflow is a bit strange.. a subprocess could 'raise' an exception causing the dag to exit, later the 'finally' condition I'm trying to simulate would carry out the cleanup process, and after that, a catch processor or a processor_failed conditional could handle the error condition on the message.  strange that finally effectively comes between 'try' and 'catch', though in this example I don't actually have a 'try' processor.

**Comment by Jeffail** [comment]
Hey @bkcsfi, any processor you write after the catch block will get executed on payloads regardless of their error status, so you can just do:

```yaml
pipeline:
  processors:
    - try:
         - type: foo
    - catch:
         - type: bar
    - type: baz
```

You can consider the `baz` processor above to be within an imaginary "finally" block.

However, the `catch` processor will remove the error flag from messages, therefore in your case you want to use a `conditional`:

```yaml
pipeline:
  processors:
    - try:
         - type: foo
    - for_each:
         - conditional:
              condition:
                type: processor_failed
              processors:
                - type: bar
    - type: baz
```

**Comment by bkcsfi** [comment]
Thanks for the response Jeff. My issue is I want 'bar' to execute whether or not processor_failed is set, hence my original post about using an 'or' with condition processor_failed | not processor_failed.

Also, it looks like once processor_failed is set, any subsequent try processor will always get skipped. 

e.g. in the example below if the subprocess returns output on stderr, then foo will not get executed. This seems somewhat unexpected because the 'error condition' in this case is not being raised inside the 'try', but rather had been raised earlier in the pipeline. Maybe a little comment in the documentation could help, though I'm not sure exactly how to phrase it.

```yaml
pipeline:
  processors:
    - subprocess:
        # do something here to fail
    - try:
         - type: foo
    - for_each:
         - conditional:
              condition:
                type: processor_failed
              processors:
                - type: bar
    - type: baz
```

**Comment by Jeffail** [comment]
Ah okay I think I get it now, if you want to run bar regardless of whether a processing stage failed then you don't need a conditional statement at all.

The try processor is only required when you want to avoid the underlying processors executing when a prior error has occurred. If that's not the case then simply remove the try completely.

If you want to 'clear' the error flag from processing stages but don't have a specific processor to run for those failed messages you can just have an empty catch block:

```yaml
pipeline:
  processors:
    - subprocess:
        # do something here to fail
    - catch: {} # Clear any existing error flags 
    - try:
         - type: foo
```
