### ISSUE TITLE
SQS endpoint property for S3 component

### ISSUE THREAD

**Issue by zoltan-toth-mw** [Jeffail/benthos#249]
Hey,

Please make the sqs endpoint configurable for the s3 component.
I'd like to test my config locally with localstack but because of that it doesn't work.

Thanks,
Zoltan

**Comment by Jeffail** [comment]
Hey @zoltan-toth-mw, it's possible to do this with a little bit of trickery. You use an SQS input, where you're able to set the endpoint. Then you translate the payloads to extract the item names, then you follow it with a cache processor pointed to an S3 bucket. It'll look something like this:

```yaml
input:
  type: sqs
  sqs:
    endpoint: "http://localhost:4576"
    url: "http://localhost:4576/queue/test-bucket"
    max_number_of_messages: 10
​
pipeline:
  processors:
  # Get an array of records from SQS event
  - type: json
    json:
      operator: select
      path: Records
​
  # Split array of records into a batch of messages
  - type: unarchive
    unarchive:
      format: json_array
​
  # For each record in the batch get its key from the bucket and replace the
  # record with its contents
  - type: cache
    cache:
      cache: bucket
      operator: get
      key: ${!json_field:s3.object.key}
​
  # If we failed to extract the bucket item for any SQS records then we log the
  # error and drop the record from the stream.
  - type: catch
    catch:
    - type: log
      log:
        fields:
          content: "${!content}"
          key: "${!json_field:s3.object.key}"
        message: "Failed to download S3 item due to '${!metadata:benthos_processing_failed}'"
    - type: filter_parts
      filter_parts:
        type: static
        static: false
​
output:
  type: stdout # TODO
​
resources:
  caches:
    bucket:
      type: s3
      s3:
        bucket: test-bucket
        endpoint: "http://localhost:4572"
        sqs_body_path: Records.s3.object.key
```

**Comment by Jeffail** [comment]
Obviously that's a drag so I'll take a look at adding something like an `sqs_endpoint`.

**Comment by zoltan-toth-mw** [comment]
Thanks and for the workaround too.

**Comment by Jeffail** [comment]
Do you need SQS to have separate credentials as well?

**Comment by zoltan-toth-mw** [comment]
No I dont, localstack ignores the credentials.

**Comment by Jeffail** [comment]
Hey @zoltan-toth-mw, in the end I might avoid going down the rabbit hole of adding customised session fields to the s3 input, I feel it is going to add too much bloat and since there's a work around I'd rather keep it in that direction.

Feel free to reopen this ticket if the work around isn't functioning as you needed.

**Comment by zoltan-toth-mw** [comment]
@Jeffail the s3 cache tries to access s3 by http url which does not work.

```
resources:
  caches:
    bucket:
      type: s3
      s3:
        region: "us-west-2"
        bucket: "crawler-quiddity"
        endpoint: "http://localhost:4572"
        sqs_body_path: "s3Key"
        credentials:
          id: "foo"
          secret: "bar"
```

> {"@timestamp":"2019-09-03T09:10:25Z","@service":"crawler-mi-shovel","content":"{\n  \"s3Key\" : \"test-obj\",\n  \"s3Bucket\" : \"crawler-quiddity\"\n}","key":"test-obj","level":"INFO","component":"crawler-mi-shovel.pipeline.processor.1.0","message":"Failed to download S3 item due to 'RequestError: send request failed\ncaused by: Get http://crawler-quiddity.localhost:4572/test-obj: dial tcp: lookup crawler-quiddity.localhost on 192.168.65.1:53: no such host'"}
