### ISSUE TITLE
Text/prepend operator misbehaves

### ISSUE THREAD

**Issue by adamwasila** [Jeffail/benthos#254]
I found this peculiar error where such simplest pipeline fails to deliver proper output. 

First build anything that uses `text` processor with `prepend` operator, eg.:

```
input:
  type: benthos_lab
pipeline:
  processors:
    - type: text
      text:
        operator: prepend
        value: "--"
output:
  type: benthos_lab
```

Then prepare input; remember to keep it under 6 bytes (as total lenght with prefix should not exceed 8 bytes), eg.:

```
aaaaaa
bbbb
cc
```

Observe output:

```
Compiled successfully.
--ccbbaa
--ccbb
--cc
```

Where proper output should be:
```
--aaaaaa
--bbbb
--cc
```

(Lab example can be found here: https://lab.benthos.dev/l/6htCxZXE7z2 )
