### ISSUE TITLE
Messages lost when unarchive is used together with batch

### ISSUE THREAD

**Issue by adamwasila** [Jeffail/benthos#263]
Hi,

I was benchmarking my newly written output and had to prepare batches (multipart messages) that have configurable size. It evolved into pipeline which had `unarchive` processor *before* `batch` and it seems that these two has issues to work together.

Example, stripped down to its bare essentials (so it may look like pure nonsense - in real case there were other processors inbetween):

(BTW, in lab: https://lab.benthos.dev/l/b6rtgOZtF7h )

```
input:
  type: file
  file:
    path: "messages.txt"
    multipart: false
  processors:
    - type: unarchive 
      unarchive:
        format: lines
    - type: batch
      batch:
        count: 3
output:
  type: stdout
  stdout:
    delimiter: "\n"
```

messages.txt:

```
a
b
c
d
e
f
g
```

Expected output would be that all lines will be processed. But actual outcome is that last line "g" is missing. It looks like if batch is not yet full (just 1 message of 3 in buffer) and input is closing, then buffer is simply discarded and some messages are lost.

What I would like to see is:

  * try to do graceful cleanup and process partial batch anyway
  * if that is not possible, at least send some warning in logs about some messages being thrown to trash; it is very kind behaviour of an application to anyone playing around or simply debugging pipelines

And yes, I'm fully aware about batch limitations (as documented) but I'm not sure that it is enough - runtime should also raise some warnings if possible.
