### ISSUE TITLE
Add "redis" processor

### ISSUE THREAD

**Issue by DpoBoceka** [Jeffail/benthos#266]
It would be convenient to have an ability to use various built-in functions of redis API, like Exists, Append etc.

**Comment by DpoBoceka** [comment]
I'm a bit stuck with implementing this.
We have key and value fields which might be interpolated. I see you tend to use these days a specific boolean "interpolate" in a struct and have a function text.ContainsFunctionVariables to calculate whether it has an interpolation in it or not. And if it returns true we use text.ReplaceFunctionVariables to lookup interpolations. And all these functions work with []byte. 
Now, I looked into go-redis package and I need to wrap-up functions SAdd and SCard for my needs and they want to have a string as an input. I saw, though, in a cache processor that you used to use function text.NewInterpolatedString and text.NewInterpolatedBytes. You slightly changed your approach in dealing with these things and I don't understand how I should manage my key field, since redis wants it to be a string. Is it acceptable to transform that field in the end into bytes by []byte(conf.Redis.Key)? I thought it implies a certain overhead regarding unnecessary memory allocation.

**Comment by Jeffail** [comment]
Hey @DpoBoceka, it's easiest to use `text.NewInterpolatedString`. If the config contains functions then it'll allocate every time it's called, then again in order to return a string. However, I wouldn't worry too much about allocations given that the processor is doing network calls in the same function.

**Comment by DpoBoceka** [comment]
Hey Ash, I managed to get something out of my incapable hands and the work is in progress, so far I can get it to work at least. Will tiny up a bit, add metrics, tests and whatnot and hope make a pull request. If you could spare a few moments and glance at my code that would be lovely as a cup of tea in a rainy day. 
While I was at it a grew a question - in order to make an "exists" query wouldn't it be more accurate to perform so under "Condition" logic? We could use operator "exists" and after that "catch" processor to figuratively catch false cases, but if you see fit to have it as a new "condition" I would gladly do as I'm told.

**Comment by Jeffail** [comment]
Hey @DpoBoceka, sounds good. Instead of an `exists` operator I'd recommend just implementing `get` and then that allows users to do their own thing. For example:

```yaml
processors:
- redis:
    operator: get
    key: foo
- catch:
    # Do stuff
```

**Comment by DpoBoceka** [comment]
fair enough, but if you have a complex logic with dependable statements you probably don't want to find yourself in "breaking the sentence". Here's an example:
```
- condition:
    and:
      - text:
           arg: "this is equal foo"
      - redis:
          operator: exists 
          key: "some_important_data" # here could be an array, i think there's a certain api for it
```
 and only if these states (you can have much more) return true you do your processors.
It is really helpful in my case. Above all, it'll be convenient to have additional operator which would indicate whether it true or false should be returned in case redis isn't available. As a matter of fact, that functionality would be of some assistance to users implementing in its own "memory" processor. 
Another downside would be overhead with utilising your network over a top. You don't need a value itself when you ask if it exists you just need a boolean. Sometimes you can store enormous bunch of data in cache, as I do occasionally.
What do you think, makes sense?

**Comment by Jeffail** [comment]
I think in that case I would either do:

```yaml
processors:
- redis:
    operator: get
    key: foo
- catch:
   - metadata: 
       operator: set
       key: key_not_exist
       value: "true"
- conditional:
    condition:
      and:
        - text:
             arg: "this is equal foo"
        - not:
            metadata:
              operator: equals
              key: key_not_exist
              value: "true"
```

Or add a general `cache` condition for check `key_exists` against any cache types, otherwise we're running down the route of every cache target having several component types.
