### ISSUE TITLE
Add an "Advanced Processing Patterns" document

### ISSUE THREAD

**Issue by DpoBoceka** [Jeffail/benthos#274]
Hate being an issue maker :(

I have a counter which is stored in some cache and I need to calculate some percentage against some value and that counter. As an option we could add "divide" operator to "number" but if you have many actions in to calculate it's going to be massive. Perhaps, we should use "math" operator which would be capable of performing standard mathematical operations and resolves some cherry-picked functions from go's "math"? Something like that:
```
pipeline:
  process_field:
  path: foo
  result_type: float
  processors:
  - number:
      operator: math
      value: "${!json_field:some_digit_contaning}/${!json_field:metadata_from_counter}+${!Log(${!json_field:field_to_find_log}}"

```
Actually, I suspect it won't be as hard as it looks - no need to tokenise these parts, we just resolve all json_filed, math.functions and just divide, concatenate, subtract and multiply the rest of the query as a whole.
Or am I missing something as usual?

**Comment by DpoBoceka** [comment]
We have to use some lexer to transform string "10/2" and to get 5 as a result.
Found these:
https://github.com/wangkekekexili/calculator/blob/master/lexer.go
https://github.com/ryandao/go-calculator/blob/master/lib/lexer.go

Perhaps, there's more..

**Comment by Jeffail** [comment]
Hey @DpoBoceka, I'm pretty sure you could use the [`awk` processor](https://docs.benthos.dev/processors/#awk) for that instead. Unless there are problems with that approach I'd rather keep the `number` processor as a simple alternative for more basic operations.

**Comment by DpoBoceka** [comment]
Very well, then. I propose you close this ticket after I post here a solution for that task in order someone would face the same problem and would be able to retrieve something useful out of it.
By the way, I think we lack some more examples of using `awk` processor since it is powerful enough to cover a great variety of cases. I hope I'll contribute on that as soon as I get something interesting.

**Comment by DpoBoceka** [comment]
Piece of bloody cake ....

Input: `{"id":"foo", "bar":10, "baz":2}`
```
pipeline:
  processors:
  - awk:
      codec: json
      parts: []
      program: |
        BEGIN { x = json_get("bar"); y = json_get("baz") }
        { json_set("result", (x/y)) }
```
I didn't go around more complicated math, though, I'm good with that example

**Comment by Jeffail** [comment]
Cool, just dumping some potential ideas for advanced patterns guides:

- awk examples
- jmespath examples
- processing on JSON array elements (for_each, process_field, unarchive (json_array), etc, archive (json_array))

**Comment by Jeffail** [comment]
Changed the name to reflect the direction this issue took. Another guide worth writing is the dictionary pattern: https://github.com/Jeffail/benthos/issues/288

**Comment by DpoBoceka** [comment]
I don't know if someone would use that, but here's a small "hexadecimal to decimal converter":

```
pipeline:
  processors:
  - conditional:
      condition:
        check_field:
          path: foo # can contain hex or dec
          condition:
            text:
              operator: prefix
              arg: "0x"
      processors:
      - process_field:
          path: foo
          result_type: int
          processors:
          - awk:
              program: |
                BEGIN { }
                { ret = 0 }
                { for (i = 1; i <= length($0); i++) {
                  ret = ret*16 + index("123456789abcdef", tolower(substr($0, i, 1)))
                } }
                { print ret }
```
