### ISSUE TITLE
Add a dictionary processor

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#288]
There are lots of use cases where we might want to map a field to a new value following a predefined dictionary. Regardless of how that field might be targeted (json path, metadata, etc) we can satisfy all possibilities by creating a general `dictionary` processor, where the raw contents of the message are referred against a `cache` resource and the value returned replaces the contents. If the key is not found within the cache then we would use an optional default value.

The first step in this new feature will be to support static key/values in a `cache` type. The `memory` cache is the obvious candidate since the data will be stored in memory. We could add a field like so:

```yaml
type: memory
memory:
  compaction_interval: 60s
  ttl: 300
  static_values:
    foo: bar
    baz: buz
```

But we'd need to consider whether TTLs should apply to static values (it doesn't really make sense to TTL a statically configured value, but it might be assumed by users).

The second piece of work is our processor. In reality, we can already implement dictionary behaviour as this point with a `cache` processor:

```yaml
- process_field:
    path: foo
    processors:
    - cache:
        cache: foo
        operator: get
        key: "${!content}"
    - catch:
      - text:
          operator: set
          value: default_value
```

So we could leave it there and document this pattern. There is already a need for more "advanced patterns" documentation so this would be a good candidate. Otherwise, we would implement a `dictionary` processor that basically does this same thing, but perhaps we would have a `default_value` field instead of recommending the `catch` approach (although catching would still be necessary since caches can fail.)
