### ISSUE TITLE
Add metadata to enrichment processor

### ISSUE THREAD

**Issue by ollieparsley** [Jeffail/benthos#292]
When using the `enrichments` (https://docs.benthos.dev/cookbooks/enrichments/) there currently isn't an easy way of getting any metadata (metadata attached to the message or an actual field in the JSON message) to say whether an enrichment succeeded, failed or otherwise. 

It'd be awesome if that could be added so that downstream in separate pipeline components we could use that data for routing, retries or simply storing whether an enrichment succeeded or not.

Maybe once implemented it could be more easily extended to give more context around an enrichment such as response code, duration etc

**Comment by Jeffail** [comment]
First Proposal
===========

Write and utilise metadata fields in the `process_dag` processor. Starting from a blank message (with no metadata fields set) once finished a `process_dag` processor would populate three metadata fields:

- `process_dag_succeeded`, a comma separate list of workflow stages that were executed successfully
- `process_dag_failed`, a comma separate list of workflow stages that were executed but failed
- `process_dag_skipped`, a comma separate list of workflow stages that were not executed due to their conditions

These metadata lists would allow users to configure logic after the workflow stages based on the results of certain stages. We would need to improve processors and conditions for metadata to make it easier to use these outputs. For example:

```yaml
processors:
- process_dag:
    foo: {} # TODO
    bar: {} # TODO
    baz: {} #TODO
- for_each:
  - conditional:
      condition:
        metadata:
          operator: csv_contains
          key: process_dag_failed
          arg: baz
        processors:
        - log:
            message: Whoopsie!
```

We would then expand `process_dag` to also refer to these metadata values when executing stages, where a stage would be skipped if it is already present within `process_dag_succeeded` or `process_dag_skipped`.

Finally, we could expand `process_dag` to also refer to a metadata field `process_dag_apply`, where if the field is non-empty then _only_ stages within the value will be executed. This would allow users to easily implement dynamic workflow stages on a per-message basis.

**Comment by Jeffail** [comment]
Second Proposal
==============

Implement a new processor similar to `process_dag` (`workflow`?) That allows users to specify a path within their document structure for accessing this metadata. If we start by assuming the format is JSON then these fields will always be arrays of strings, making it much easier to work with. For example:

```yaml
processors:
- workflow:
    meta_path: meta.workflow
    stages:
      foo: {} # TODO
      bar: {} # TODO
      baz: {} #TODO
- for_each:
  - conditional:
      condition:
        jmespath:
          query: contains(meta.workflow.failed, 'baz')
      processors:
      - log:
          message: Whoopsie!
```

Similar to the first proposal we would then expand `workflow` to also refer to these values for potentially skipping certain stages that have already been executed.

This proposal requires a new processor but has the advantage of being much more flexible when it comes to combining multiple workflow processors in a single pipeline. I would also argue that JSON is much easier to work around than metadata fields.

**Comment by ollieparsley** [comment]
Hey Ash. The second proposal appears to much more future-proof and adding a way to configure "workflows" could work for more than just enrichments, but other flows that have varying dependencies.

Am I correct in thinking that "stages" are ways of separating out layers of dependencies?

**Comment by Jeffail** [comment]
@ollieparsley Implemented: https://github.com/Jeffail/benthos/commit/e9836484642ccfbc5ce5e653db9b7f577591e13a

Looks like this:

```yaml
workflow:
  meta_path: meta.enrichments
  stages:
    foo:
      premap:
        bar: baz
      processors:
        ...
      postmap:
        nah: m8
```
