### ISSUE TITLE
http processor > GET request should not contain payload

### ISSUE THREAD

**Issue by andytruong** [Jeffail/benthos#305]
Hi Jeff,

I am not sure why the GET request got payload `{}`, which will raise error on some HTTP endpoints. Is there anyway to skip it on GET? Thanks.

```
input:
  http_server:
    address: "localhost:14195"
    path: /ping

pipeline:
  processors:
    - process_map:
        premap_optional: { foo: "${!metadata:foo}" }
        processors:
          - http:
              request: { verb: GET, url: "http://requestbin.net/r/1jf261f1" }
output:
  stdout: {}
```

**Comment by Jeffail** [comment]
Hey @andytruong, if you clear the payload before the request then you won't send out a body:

```yaml
input:
  http_server:
    address: "localhost:14195"
    path: /ping

pipeline:
  processors:
  - text:
      operator: set
      value: ""
  - http:
      request: { verb: GET, url: "http://requestbin.net/r/1jf261f1" }
output:
  stdout: {}
```

Also in your example the `premap_optional` value `${!metadata:foo}` won't work as function interpolations aren't resolved for mappings.
