### ISSUE TITLE
condition count is not working for arg=1

### ISSUE THREAD

**Issue by voronaam** [Jeffail/benthos#307]
Pipeline snippet:

```
    - conditional:
        condition:
          type: count
          count:
            arg: ${LOG_FREQUENCY}
        processors:
          - log:
              level: ERROR
              message: "Gotcha!"
```

In this example I expect `LOG_FREQUENCY` environment variable to control how often a line is logged.

With `LOG_FREQUENCY=100` every 100th message triggers a log line.
With `LOG_FREQUENCY=0` nothing is logged, as expected.

However,
with `LOG_FREQUENCY=1` I expect every message to trigger a log line. While in reality nothing is logged again.

**Comment by Jeffail** [comment]
Hey @voronaam, with that config and `LOG_FREQUENCY=100` I would expect every message to trigger a log line _except_ for the 100th message. In order to perform the behaviour you're specifying you would need to place your `count` condition within `not`:

```
    - conditional:
        condition:
          not:
            count:
              arg: ${LOG_FREQUENCY}
        processors:
          - log:
              level: ERROR
              message: "Gotcha!"
```

In which case I would expect both `LOG_FREQUENCY=0` and `LOG_FREQUENCY=1` to trigger logs for all messages, which is correct according to [the documentation](https://docs.benthos.dev/conditions/#count):

> Counts messages starting from one, returning true until the counter reaches its target, at which point it will return false and reset the counter.

Can you double check your config and the behaviour you're seeing?

**Comment by voronaam** [comment]
I see, I got the way this condition works in reverse. Thank you for the fast response.

With `not` there is slight problem though. Well, problem with my expectation. It works as expected for `1`, `100`, etc, but for `0` it sill logs everything.

I could add another condition with an `and` and check for the variable to not be `0`.

Is it how you would do it as well or there is a better way?

**Comment by Jeffail** [comment]
Yeah, it's a little long-winded but assuming performance isn't absolute highest priority I would probably solve that with:

```yaml
    - conditional:
        condition:
          and:
          - not:
              count:
                arg: ${LOG_FREQUENCY}
          - check_interpolation:
              value: ${LOG_FREQUENCY}
              condition:
                number:
                  operator: greater_than
                  arg: 0
        processors:
          - log:
              level: ERROR
              message: "Gotcha!"
```

If performance is a huge concern then you'll need to use two variables:

```yaml
    - conditional:
        condition:
          and:
          - not:
              count:
                arg: ${LOG_FREQUENCY}
          - static: ${ENABLE_LOG:true}
        processors:
          - log:
              level: ERROR
              message: "Gotcha!"
```
