### ISSUE TITLE
Question: non-replacing HTTP processor

### ISSUE THREAD

**Issue by voronaam** [Jeffail/benthos#308]
The documentation on HTTP processor states that 

> replaces the original message parts with the body of the response

Is there a way instead of replacing the entire body to place it inside the current message's field? Or replace the original message with a json like
```
{
  "request": <original_message>,
  "response": <http response>
}
```

In addition to keeping some context data available for later processors, this would also potentially solve the `204 No Content` response problem (currently Benthos http processor does not like servers ever returning this since it will have no message to continue with).

**Comment by Jeffail** [comment]
Hey @voronaam, the [`process_map` processor](https://docs.benthos.dev/processors/#process_map) lets you do this. It allows you to map a custom payload out of a message, perform some processors to it, then map the resulting payload back into the original message. In your case you can do something like this:

```yaml
pipeline:
  processors:
    - json:
        operator: move
        path: .
        value: request
    - process_map:
        premap:
          .: request
        processors:
          - http: {} # TODO
        postmap:
          response: .
```
