### ISSUE TITLE
Unable to read from a Kinesis stream

### ISSUE THREAD

**Issue by krishnatg** [Jeffail/benthos#309]
Hi,
I am trying to consume from a Kinesis stream with the following config:
```
input:
  type: kinesis
  kinesis:
    credentials:
      profile: "default"
    region: us-west-2
    start_from_oldest: true
    limit: 10
    stream: "stream_test"

output:
  type: file
  file:
    delimiter: ""
    path: "./logs.out"
```
This gives me a `ResourceNotFoundException` when I run benthos.

./benthos -c benthos-to-file.yaml
{"@timestamp":"2019-11-07T18:05:48-06:00","@service":"benthos","level":"INFO","component":"benthos","message":"Launching a benthos instance, use CTRL+C to close."}
{"@timestamp":"2019-11-07T18:05:48-06:00","@service":"benthos","level":"INFO","component":"benthos","message":"Listening for HTTP requests at: http://0.0.0.0:4195"}
{"@timestamp":"2019-11-07T18:05:51-06:00","@service":"benthos","level":"ERROR","component":"benthos.input","message":"Failed to connect to kinesis: ResourceNotFoundException: Shard shardId-000000000000 in stream stream_test under account 111248436868 does not exist\n\tstatus code: 400, request id: c68217c4-d806-1bbb-90bc-a46079e0c462"}
{"@timestamp":"2019-11-07T18:05:51-06:00","@service":"benthos","level":"ERROR","component":"benthos.input","message":"Failed to connect to kinesis: ResourceNotFoundException: Shard shardId-000000000000 in stream stream_test under account 111248436868 does not exist\n\tstatus code: 400, request id: c33fe856-e765-2026-9501-5bf311b0c07f"}
{"@timestamp":"2019-11-07T18:05:52-06:00","@service":"benthos","level":"ERROR","component":"benthos.input","message":"Failed to connect to kinesis: ResourceNotFoundException: Shard shardId-000000000000 in stream stream_test under account 111248436868 does not exist\n\tstatus code: 400, request id: d840d7f5-ff1a-1d90-8e7e-6450396fed41"}

However, at the same time using the AWS CLI, I am able to successfully consume messages using `aws kinesis describe-stream --stream-name stream_test`, `aws kinesis get-shard-iterator --stream-name stream_test --shard-id shardId-000000000000 --shard-iterator-type TRIM_HORIZON`, and `aws kinesis get-records --shard-iterator <shardIterator>`.

Can someone please help me understand where might I be going wrong?
