### ISSUE TITLE
Feature Request: Metrics base name in processors' config

### ISSUE THREAD

**Issue by voronaam** [Jeffail/benthos#312]
As our Benthos configuration is going ever more complicated we find it harder and harder to keep the `rename` block consistent with the `pipeline.processors` state.

With the current config we are getting metrics like `benthos_pipeline_processor_6_processor_0_client_rate__limit_total__ms` and after any significant enough change it is a painful process to make sure all the indexes in the `rename` block match. And there is nothing preventing a mistake.

Would it be possible to specify metric's "base name" in the step definition?

To give a trivial example, I'd love to have something like

```
    - json:
        human_name: 'save.request'
        operator: move
        path: .
        value: request
```

This way I could be certain that the metrics I care about - like the ones on `http` processors - are always named the same.

**Comment by Jeffail** [comment]
Hey @voronaam, I like this idea. I've considered in the past a type of namespacing processor that would solve a similar use case but would look like this:

```yaml
- namespaced:
    label: ns_foobar
    processors:
      - jmespath:
          query: foo
```

Which would create metrics like `pipeline.processors.0.ns_foobar.0.count`, you could then use `rename` to create generalised rules like:

```yaml
rename:
  by_regexp:
    - pattern: ".*\\.ns_(.*)"
      value: "ns.$1"
```

To see metrics like `ns.foobar.0.count`.  This approach is easy to implement. However, the problem I had with it was the amount of boilerplate needed if you wanted a namespace for each individual processor.

We could adapt your idea so that all processor configs have a root level field `label` where you can optionally specify an identifier. When the label is non-empty it would assume the log and metric path for that processor instead of its index. The config would look like this:

```yaml
pipeline:
  processors:
    - label: 'save.request'
      json:
        operator: move
        path: .
        value: request
```

And would produce metric paths like `pipeline.processors.save.request.count`.

It'll potentially be a lot of work to get this in as we need to be sure that every potential "owner" of processors respects labels, and that things like type inference would still work, but I think it's worth doing.

**Comment by voronaam** [comment]
Perfect. I did not think of the logs, but that would certainly be helpful as a name there as well. And `label` is a perfect name for this field.

Thank you for considering it.

**Comment by Jeffail** [comment]
Hey @voronaam,

I've been thinking about this and potentially have a different solution to offer. We could add a `processors` section to `resources` which would allow you to define processors as named resources similar to how you can do it with conditions currently. That would allow you to write out your processors like this:

```yaml
pipeline:
  processors:
    - resource: save.request

resources:
  processors:
    "save.request":
      json:
        operator: move
        path: .
        value: request
```

Which would result in metric paths like `resources.processors.save.request`.

This is much easier to implement and also offers the other advantages of resource declarations. However, it also forces you to restructure your configuration, how would you feel about that?

**Comment by voronaam** [comment]
I like this idea.

It would not be far from what we do now - we are annotating each "non-trivial" processor with a comment explaining that this is a beginning of a section and what it does.

We do this to enable the reader to go through the definition of the pipeline by reading this comments only and to get the idea of what the pipeline does in general. If they are interested in the details, they can always dive deeper in the step definition.

With that, having a top level pipeline definition to be something like this would totally work:

```
pipeline:
  processors:
    - resource: parse.request
    - resource: enrich.salesforce
    - resource: enrich.geoip
    - resource: send.to.analytics
    - resource: send.to.dashboard
```

**Comment by Jeffail** [comment]
Cool, I've implemented it: https://github.com/Jeffail/benthos/commit/969507d670bf68d104c097eedbfd62b84471a54f, I could do with some beta testers. I'll probably put out a release candidate for v3.6.0 tomorrow.

**Comment by Jeffail** [comment]
Release candidate: https://github.com/Jeffail/benthos/releases/tag/v3.6.0-rc1
Or pull the `latest` docker image.

It looks fine to me but there's some other stuff to test as well, but if you get a chance to try it out let me know how it goes.

**Comment by voronaam** [comment]
Just finished testing some permutations. Looks really good. It does all I wanted it to do and more. In the pipeline I tested it I got rid of the `rename` metrics completely. The metrics name are not the same as they were before, but they are meaningful and I think I can use them.

I may still add the `rename` metrics just to shorten the `benthos_resource_processor_` prefix, but it is not a problem at all.

I have also tested nested resource processors and they work without an issue.

By nested I mean something like this:

```
resources:
  processors:
    "call.classifier":
      <some definition>
    "fail.classifier":
      <some definition>
    "do.classifier":
      process_map:
        premap:
          .: request
        processors:
          - resource: call.classifier
          - resource: fail.classifier
        postmap:
          response: .
```

With that my main `pipeline.processors` became a tiny list of nicely named steps :)

Thanks a ton!

P.S. Tested using the current `v3.6.0-rc1` tag.
