### ISSUE TITLE
Return detailed error from json_schema condition

### ISSUE THREAD

**Issue by stephanebruckert** [Jeffail/benthos#313]
https://github.com/xeipuuv/gojsonschema has `err.Details`:
> "PASSWORD must be greater than or equal to 8"

Could the json_schema condition return this detailed error, or does the current implementation of conditions only allow returning true or false? This would avoid doing `check_fields` for all fields

I would love to be able to do something like:
```
  - type: conditional
    conditional:
      condition:
        type: json_schema
        json_schema:
          part: 0
          schema_path: "file://./schema.json"
      else_processors:
      - json:
          operator: set
          path: __log_parser_error
          value: ${!error}
```
Could the condition populate [`${!error}`](https://github.com/Jeffail/benthos/blob/master/docs/config_interpolation.md#error) ?
