### ISSUE TITLE
Question: Custom codec support?

### ISSUE THREAD

**Issue by voronaam** [Jeffail/benthos#315]
We are already using custom processors as described in https://www.jeffail.uk/post/write-a-benthos-plugin/

However, for one other use case we realized that the best would be to write a custom codec for the `process_field` processor. As it would replace a quite long `process_map` with `premap` and `postmap` with just a few lines:

```
    - process_field:
        path: "data"
        codec: deobfuscate
```

Is there support for this? Could you give some pointers at how to go about it?

Thank you!

P.S. Love Benthos :)

**Comment by voronaam** [comment]
FYI, our current config is something like this:

```
    - process_map:
        premap:
          .: data
        processors:
          - type: deobfuscate
        postmap:
          data: .
```

Which is doing exactly the same thins as `process_field`, but just looks way more confusing to the reader.

**Comment by Jeffail** [comment]
Hey @voronaam, for that you would probably need to copy the `process_field` processor implementation into a custom plugin as there's currently no way to inject your own implementation of a codec.

Would the config:

```yaml
    - process_field:
        path: data
        codec: json
        processors:
          - type: deobfuscate
```

Not work for your use case?
