### ISSUE TITLE
Feature Request: json_field_object function

### ISSUE THREAD

**Issue by voronaam** [Jeffail/benthos#316]
This is a suggestion to add a new `json_field_object` function. It will perform the same JSON field select as `json_field`, but would return its result as a JSON object, instead of a string.

This would mimic the behaviour between `metadata` and `metadata_json_object` functions.

https://docs.benthos.dev/config_interpolation/#functions

P.S. On the naming: to follow metadata's function naming would produce `json_field_json_object`. Which, IMHO, looks a bit weird. Hence the proposed `json_field_object` name. But either way works.

**Comment by voronaam** [comment]
Just tested the `metadata_json_object` and that returns JSON encoded string, not the object. I think I misunderstood the feature.

What I am looking for is to shorten something like this:
```
- json:
    operator: set
    path: request
    value:
      foo: bar
- json:
    operator: move
    path: input.data
    value: request.data
- json:
    operator: move
    path: input.other.data
    value: request.extra
```
A pipeline that produces a JSON uses some constants, and moving around different parts of the current content.
Essentially I hoped to be able to do it all in just one processor:
```
- json:
    operator: set
    path: request
    value:
      foo: bar
      data: ${!json_field_object:input.data}
      extra: ${!json_field_object:input.other.data}
```

It is all doable now already using several `json` processors. I just think it would've been extremely more readable to see the produced JSON's schema in the YAML node, instead of a series of mutations.

**Comment by Jeffail** [comment]
Hey @voronaam, for performance reasons it'd be tricky to have the interpolation functions under `value` get properly parsed as objects during a set operation. For mapping tasks like these I often use [`jmespath`](https://docs.benthos.dev/processors/#jmespath), you'd need to use a `merge` function so that you don't lose sibling fields of `request` but it should do what you want here:

```yaml
- jmespath:
    query: |
      merge(@, {
        request: {
          foo: 'bar',
          data: input.data,
          extra: input.other.data
        }
      })
```
