### ISSUE TITLE
Tell me what annoys you

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#326]
If you're using Benthos and find something about it frustrating, but not worthy of raising an issue, please give me a brief description here. It could be anything: features, documentation, performance, me.

Also, if the thing that annoys you is already posted then give it a thumbs up.

**Comment by voronaam** [comment]
Something that currently annoys me about sync_response pattern is that the synchronous response is sent at the very end of the pipeline. I was wondering if it possible to have a "sync_response" processor, such as when input supports sync responses it would be possible to write something like this:

```
input:
  http_server:
    path: /search

pipeline:
  processors:
    - http:
      # some enrichment microservice
    - sync_response:
      # Send whatever is in the current body to the client
    - http:
      # some other enrichment microserivce

output:
  kafka: {}
```

In this example the end user is not waiting for the second enrichment microservice, because its response is only used by the message sent to Kafka, not in the response to the end user.

I am looking to use something like this in an HTTP-to-queue kind of an application. Where there is an HTTP endpoint accepting job items. It makes one call to make sure this is the valid job (basically, an auth) and returns `201 Accepted` response to the caller. The job then proceeds through the pipeline and will be completed eventually, but the caller has no reason to wait.

(I have not looked at the `http_server` implementation yet to see if it can be instrumented in such a way)

**Comment by voronaam** [comment]
Totally unrelated. This also annoys me in `http.go`:

```
	if responseMsg.Len() < 1 {
		return nil, response.NewError(fmt.Errorf(
			"HTTP response from '%v' was empty", h.conf.HTTP.Client.URL,
		))
	}
```

Some servers return absolutely empty `HTTP 200` response and I expect to have this to be an empty string after a call the such a server:

```
- text:
    operator: set
    value: '"${!content}"'
```

**Comment by Jeffail** [comment]
Awesome, thanks @voronaam! This is exactly what I'm looking for. I think both of these might be solvable but I'll need to be careful about backwards compatibility for the `http` processor, but I definitely understand your pain.

**Comment by voronaam** [comment]
@Jeffail I just wrote a quick and dirty `background` processor which executes its children in a separate goroutine and does not wait for their result message.

I think this may act as an easier solution than a `sync_response` in the middle of the pipeline.

The code I have works as a plugin and I tested it that it does what I want from it, in principle.

I think it may even be possible to have a `Pipeline` as its child instead of `Processor[]`. This way this "background" pipeline will even have ability to use buffers and outputs. Though, I do not need this at the moment and it may be an overkill on the complexity.

Take a look at this gist (sample Yaml in the end): https://gist.github.com/voronaam/1e984a2fef66b49d8dcc75872427455c

**Comment by assada** [comment]
The config file becomes huge and hard to understand whats happens inside.

Our dev config for example: https://gist.github.com/assada/b01846141cddefef06c42644a753b7a9

There is a possibility that we have configured something wrong :)

**Comment by kostas-theo** [comment]
I would like to add some new functionality to acheive my specific use case, but as I was working I found that (unless I have missed something obvious) the syntax for simply incrementing a value is just way too cumbersome:

```
- type: process_field
              process_field:
                codec: metadata
                path: rate
                result_type: int
                processors:
                - number:
                    operator: add
                    value: 1
```

**Comment by Jeffail** [comment]
This is all great stuff everyone. I'm aiming to make the next minor release of Benthos mostly address issues from this thread.

@voronaam For the HTTP-to-queue application you mentioned, if I add a `sync_response` processor you might get away with something like this:

```yaml
input:
  http_server:
    path: /search
  processors:
    - http:
      # some enrichment microservice
    - sync_response:
      # Send whatever is in the current body to the client

# Once messages reach the memory buffer the payload is acked immediately.
buffer:
  type: memory

pipeline:
  processors:
    - http:
      # some other enrichment microserivce

output:
  kafka: {}
```

I can easily implement a `sync_response` processor (opened issue https://github.com/Jeffail/benthos/issues/329) but I'll also need to spend some time ensuring there aren't any race conditions introduced by it.

I've also opened a ticket to deal with the http processor empty responses: https://github.com/Jeffail/benthos/issues/330

@assada I definitely feel your pain, I've had to build a few pipelines with a similarly gross output section. It looks as though the distinctions between the kafka outputs you have are the topic and nothing else, so you can probably cut most of that down by using metadata and interpolation to set the topic. You can also use [references](https://docs.benthos.dev/configuration/#reusing-configuration-snippets) to save duplicating the same chunks of config multiple times. 

My attempt to shorten your config ended up with this: https://gist.github.com/Jeffail/ca85e1aec417febf396a1b6e9fae2fa9, unfortunately it's still ugly to look at. I can make it a little smoother by adding a proper `try` output instead of making you configure a broker each time, created a ticket: https://github.com/Jeffail/benthos/issues/331

@kostas-theo agreed, for something so simple and common there ought to be a better way. You could potentially use the `awk` processor:

```yaml
pipeline:
  processors:
    - awk:
        program: |
          { metadata_set("rate", metadata_get("rate") + 1) }
```

But there's a performance hit, there's a good chance you won't even notice it though. I've raised a ticket for looking into a better way: https://github.com/Jeffail/benthos/issues/332

**Comment by gurre** [comment]
I'm using Benthos for batching up zmq messages and archiving them to S3. I tried upgrading to the new batching spec but I had a hard time understanding it. I tried batching on the input and output but to no avail. The docs could perhaps be expanded with some more examples? A graphical configurator would be magical. Or perhaps beginning with just a way to visualize e.g. https://www.diagram.codes.

**Comment by Jeffail** [comment]
@gurre turns out this was actually a bug with the ZMQ input, sorry you lost time on this, I've put out a fix: https://github.com/Jeffail/benthos/releases/tag/v3.6.1

Being able to print a graphical representation of configs would be awesome, it's something I've considered in the past. Maybe as a future weekend project.

**Comment by atheken** [comment]
Thanks for asking @Jeffail  -- I'm just getting started with Benthos, and I'm finding that the docs related to batching and expected behavior to be somewhat limited.

What I was hoping to accomplish was essentially, build batches of X bytes or Y messages, or wait Z time from Kafka, and then flush the batch for processing.

Here's one of multiple permutations I've attempted to do this:

```
input:
  kafka_balanced:
    addresses:
    - localhost:9092
    batching:
      count: 5s
      period: 100ms
      max_bytes: 2048
    client_id: benthos_kafka_input
    commit_period: 5s
    consumer_group: benthos_consumer_group
    fetch_buffer_cap: 1000000
    group:
      heartbeat_interval: 2s
      rebalance_timeout: 20s
      session_timeout: 10s
    max_batch_count: 100
    max_processing_period: 10s
    start_from_oldest: true
    topics:
    - benthos_stream
pipeline:
  processors:
    - archive:
        format: json_array
    - jmespath:
        query: '{"Items" : @ }'
output: 
  kafka:
    ack_replicas: true
    addresses:
    - localhost:9092
    backoff:
      initial_interval: 0s
      max_elapsed_time: 10s
      max_interval: 1s
    round_robin_partitions: true
    timeout: 5s
    topic: benthos_batches
```

The behavior I'm encountering is that if there are messages accumulated in the input topic when I start with this configuration, then I do get a few initial batches, but then benthos pretty steadily generates single message batches.

Otherwise, Benthos seems awesome, and am looking forward to using it heavily for a lot of our production workloads.

**Comment by Jeffail** [comment]
@atheken sorry that it was a headache but glad you got it solved. Running Benthos with the `--strict` flag prevents it from running when there are unrecognized fields in your config, which would've caught this. I'm considering making strict mode the default behavior in the next major version release in order to prevent this kind of problem for new users.

**Comment by atheken** [comment]
That’s what turned up the difference for me: —lint —strict

Thanks again for Benthos; Once I got over that hurdle, I was able to set up two streams that will replace thousands of lines of custom code. And many more to follow.

//Andrew

**Comment by atheken** [comment]
OK. Since I'm at it :-D

**Dynamic reloads:** Make the file-based stream configs work like `haproxy`: You can run `haproxy -c -f <config>` to validate a config (covered by `--static --lint`), you can then sent a unix signal to haproxy to hot reload configs.

This is the use case: We want to build a cluster of many benthos instances as a shared infrastructure service that would run multiple source-controlled stream configs. During deploys, we usually want to refresh the configs, adding/removing/updating individual streams, but ideally not disrupting streams that are unchanged. We would build tooling to distribute/update configs, and then notify benthos to reload the configs, we would like to avoid using the REST APIs for this, as this substantially complicates the update tooling, and requires us to maintain a known list of benthos instances.

**Spread mapping for JSON to Dynamo**: We want to pipe JSON objects directly to dynamodb, this is possible, but the "spread" syntax for json to dynamo appears to prevent the stream config from being displayed in the REST API:

```
"" : "."
```

**Easy JSON field normalization** : JSON requires quotes on properties, but some publishers may naively omit these. This is sometimes fine, but AWS services have a real issue with this:

```
{
stuff : "this'll break"
}
```
```
{
"stuff" : "this is fine"
}
```
This is a reasonable thing to be able to add as a processor to "fix" trivially silly encoding problems.

**Comment by Jeffail** [comment]
Hey @atheken, thanks I've added a ticket for config reloading (https://github.com/Jeffail/benthos/issues/338), it's been asked for previously so it makes sense to get that in.

I've taken a look at the dynamo issue but wasn't able to reproduce it, would you be able to provide a config that causes it?

I love the idea of a general purpose JSON fixer. I'll take a look at that.

**Comment by jhedlund79** [comment]
Probably just an issue on my end. When I build in docker I get 
```go: github.com/Jeffail/benthos/v3@v3.6.1: reading github.com/Jeffail/benthos/go.mod at revision v3.6.1: unknown revision v3.6.1```
My Project builds fine locally and I am vendoring. Have you had any issues with this? All my imports use the /v3 in the import statements.

**Comment by Jeffail** [comment]
Hey @jhedlund79, I updated the plugin example repo with a docker example: https://github.com/benthosdev/benthos-plugin-example and it seems to work. If you can provide more details I'm happy to try and help out.

**Comment by Jeffail** [comment]
Thanks everyone for the feedback, and obviously keep posting more annoying stuff when you find it. Version v3.7.0 release candidate 1 went out today which fixes most of the problems raised here https://github.com/Jeffail/benthos/releases/tag/v3.7.0-rc1

**Comment by assada** [comment]
By the way about issue https://github.com/SignNowInc/SNTerra/pull/1231.

It seems to me it makes sense to add more `TRACE` logs for outputs and inputs. If we had the logs it would be much easier to find the problem.

**Comment by Jeffail** [comment]
@assada yeah that's been on my list for a while. I've created https://github.com/Jeffail/benthos/issues/347.

**Comment by voronaam** [comment]
Thank you for all the changes you are making.

Is there a processor that can be used for a dictionary replace operation? Something I could put inside `process_field` to replace the value from a dictionary and error out when the key is not in the dict.

**Comment by Jeffail** [comment]
Hey @voronaam, you could potentially use a cache for that sort of thing, details in this ticket: https://github.com/Jeffail/benthos/issues/288

I'm planning to write a docs section outlining common patterns such as this (https://github.com/Jeffail/benthos/issues/274)

**Comment by eduardodbr** [comment]
I would really like to have an explode option to be able to explode an array (using the unarchive option with json_array, for example) but keeping the rest of the columns, for example the message:

````
{
  "id": 1,
  "data": [
    {
      "foo": 2,
      "bar": 3
    },
    {
      "foo": 4,
      "bar": 5
    }
  ]
}
````

would be splitted into two different messages :

````
{
  "id": 1,
  "data": {
    "foo": 2,
    "bar": 3
  }
}
````

````
{
  "id": 1,
  "data": {
    "foo": 4,
    "bar": 5
  }
}
````

I was able to some some hacky stuff to achieve this but I would be great if we could have a processor to do it.

**Comment by Jeffail** [comment]
Hey @eduardodbr, I've just added an `explode` operator to the `json` processor, in the next build you'll be able to do:

```yaml
pipeline:
  processors:
    - json:
        operator: explode
        path: data
    - unarchive:
        format: json_array
```

I'd still like to limit the actual expansion of messages to the unarchive processor, but I've mentioned it within the json docs to make this pattern clear.
