### ISSUE TITLE
Create dedicated try output

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#331]
Currently if users want to configure a DLQ for when an output fails they'll need to create a broker with the pattern `try`:

```yaml
output:
  broker:
    pattern: try
    outputs:
      - type: foo
      - type: bar
```

That's a lot of indentation that could be cleaned up with a specialised `try` output. The underlying implementation would be the same:

```yaml
output:
  try:
    - type: foo
    - type: bar
```
