### ISSUE TITLE
Simple operations ought to have a quicker solution

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#332]
Benthos has a huge amount of flexibility with processors such as `process_field` and `process_map`. However, most of the time users just want to perform a relatively simple and common operation on a field, e.g. increment a value:

```yaml
- process_field:
     codec: metadata
     path: foo
     result_type: int
     processors:
      - number:
          operator: add
          value: 1
```

For that purpose we _could_ use `awk`:

```yaml
pipeline:
  processors:
    - awk:
        program: |
          { metadata_set("foo", metadata_get("foo") + 1) }
```

But there's a performance hit and it seems a little heavy handed for something so simple.

Perhaps we could add a more general solution for these common operators that doesn't require a full scripting engine.

**Comment by kkessler** [comment]
for mathematics type operations like your example we could have a [govaluate](https://github.com/Knetic/govaluate) processor to do arithmatic with variables populated from metadata and json, etc.

**Comment by Jeffail** [comment]
Also another requirement I want to expand this issue with is the idea of making metadata as variables easier to work with. The first requirement might be setting multiple metadata fields at a time:

```yaml
# something like this
metadata_map:
  foo: ${!json_field:bar.baz}
  bar: static_value_1
  baz: ${!count:wut}
```

The second thing is more concise branching based on fields:

```yaml
# something like this
branching_thing:
  "foo == 'bar'":
    - type: processor_foo
  "baz > 0":
    - type: processor_bar
```

And finally, since we're dirtying up our message metadata with these short term variables we want a nice clean way of removing them all before writing to outputs:

```yaml
# something like this, removes all metadata proceeded by an underscore
# (assumed to be a temp variable)
type: metadata_rm_underscores
```

**Comment by DpoBoceka** [comment]
Well, I need to remark that by removing all metadata keys with underscores in them we'll let go of the important ones, such as kafka_topic, so we need to be careful there.
Now, as I mentioned, the idea with introducing `Resource` processor was marvellous and implies, perhaps, a bigger step towards functional-directed approach to commit. 
For example, to get my incoming data in order I use `json-move` over 1k times and in terms of metrics I'm not interested in having a knowledge how many times each of these operations was executed, but, rather, how many times benthos used "renaming" in general(perhaps, there is a way to get such number at present moment, and not by manually concatenating little ones).
Apart from that example, we can face a more complicated logic inside our home-made `Resource` instance and now we're able to wrap almost everything with it, even if inside such function we use a lot of conditions, processors etc, as long as we handle all possible failures.
So as a PoC it'll be enough just to test on Renaming case, I suppose - there is no much of a difference.

**Comment by Jeffail** [comment]
The intention with `metadata_rm_underscores` would be that it only removes metadata fields prefixed with an underscore, so the standard metadata values we add right now will be left unchanged. Then we'd standardize on variables having this format: `_foo`.

**Comment by DpoBoceka** [comment]
Does that make sense?

```
pipeline:
  processors:
    - resource: 
        name: my_func1
        metadata:
         operator: multiset
         key: ["_bad", "_good"]
         value: ["my_old_key", "my_new_key"]

resources:
  processors:
    my_func1:
    - json:
        operator: move
        path: ${!metadata:_bad}
        value: ${!metadata:_good}
    - metadata:
        operator: delete_prefix
        value: "_"
```

**Comment by DpoBoceka** [comment]
hey @Jeffail. Could you, please, comment on that one above?
I think it would be really awesome to allow users to do some scripting of sorts.

**Comment by Jeffail** [comment]
Hey @DpoBoceka, I think allowing multiset with the regular `metadata` processor would be good, needs a bit of thought as it'd require a refactor and wouldn't fit for all operator types. In terms of trying to find a solution for resource processor arguments I think our options are just regular metadata:

```yaml
pipeline:
  processors:
    - metadata:
        operator: multiset
         keys: ["_bad", "_good"]
         values: ["my_old_key", "my_new_key"]
    - resource: my_func1

resources:
  processors:
    my_func1:
    - json:
        operator: move
        path: ${!metadata:_bad}
        value: ${!metadata:_good}
    - metadata:
        operator: delete_prefix
        value: "_"
```

Which I think is worth trying to accomodate since it's generally useful. However, this is still limited as most fields don't support interpolation and it wouldn't make sense to. In the case of the `path` field of the `json` processor it's possible to add interpolation there, but it'd be significant work to make the `operator` field support interpolation, for example.

I like the idea for general parameters for a processor (or general config snippets), of course you can always use YAML anchors to something similar, but that still requires writing the structure and isn't as clean.

After giving it some thought I don't think parameters fit within processor resources. The problem is that they are parsed in parallel with other components and therefore having parameters as a form of macroing feels a little hacky and would require some nasty refactoring around how they work.

We could potentially take this into a different direction and have a `templates` section:

```yaml
pipeline:
  processors:
    - template:
        arg1: "hello world"

templates:
  foo: |
    bar:
      baz: "{{.arg1}}"
```

A template is basically a string, that gets parsed into a processor by the `template` processor itself, and becomes inlined with those arguments.
