### ISSUE TITLE
Retry logic for HTTP/HTTPS consumers

### ISSUE THREAD

**Issue by mkorszun** [Jeffail/benthos#34]
Is it possible to have some retry rules / logic for failed HTTP/HTTPS push attempts?

**Comment by Jeffail** [comment]
Hey @mkorszun, how granular would the logic need to be?  I can easily add some simple status code based rules, maybe something like this:

``` yaml
http_client:
  url: http://foo.bar
  retries: 3
  backoff_on: [ 429 ]    # Exponentially backoff the retries for these codes
  drop_on: [ 409, 413 ] # Drop the message entirely (as if successfully sent) for these codes
```
