### ISSUE TITLE
Output fun_out + try

### ISSUE THREAD

**Issue by assada** [Jeffail/benthos#343]
Our QA Engineers found a strange issue.
If you send, for example, 5 identical messages to the benthos input, as a result, not all messages will be at the destination. Our debug logs from the processor prove that the processor received ALL messages.
There are no error logs. Everything looks fine.

Our idea:
1) Read the batch from Kafka topic "A".
2) Process it and write processor result to the elastic AND to Kafka topic "B" in the same time (fun_out).
If something went wrong with the Kafka or elasticsearch, write in the topic "C" to kafka. (Dead Letter). We also tried to implement retry mechanism for output.

But it does not seem to worked. I am almost sure that we were mistaken, but it is strange that there are no error logs.

Benthos version: v3.4.0

worker.yml:
```yaml
input:
  type: kafka_balanced
  kafka_balanced:
    addresses:
      - ${kafka_broker_1}
      - ${kafka_broker_2}
      - ${kafka_broker_3}
    client_id: ${input_client_id}
    commit_period: 1s
    consumer_group: ${consumer_group}
    fetch_buffer_cap: 256
    batching:
      count: 5
      period: 10s
    max_processing_period: 1s
    start_from_oldest: true
    target_version: ${target_version}
    group:
      heartbeat_interval: 3s
      rebalance_timeout: 60s
      session_timeout: 10s
    topics:
      - ${topic_name}

pipeline:
  processors:
    - type: archivarius
output:
  type: switch
  switch:
    outputs:
      - output:
          type: kafka
          kafka:
            ack_replicas: true
            addresses:
              - ${kafka_broker_1}
              - ${kafka_broker_2}
              - ${kafka_broker_3}
            client_id: ${output_client_id}
            compression: none
            max_msg_bytes: ${max_msg_bytes}
            round_robin_partitions: true
            target_version: ${target_version}
            timeout: 5s
            topic: ${failed_topic_name}
        condition:
          type: processor_failed
      - output:
          type: broker
          broker:
            batching:
              count: 5
              period: 10s
            copies: 1
            pattern: fan_out
            outputs:
              - type: broker
                broker:
                  batching:
                    count: 5
                    period: 10s
                  copies: 1
                  pattern: try
                  outputs:
                    - type: retry
                      retry:
                        backoff:
                          initial_interval: 500ms
                          max_elapsed_time: 0s
                          max_interval: 3s
                        max_retries: 3
                        output:
                          type: kafka
                          kafka:
                            ack_replicas: true
                            addresses:
                              - ${kafka_broker_1}
                              - ${kafka_broker_2}
                              - ${kafka_broker_3}
                            client_id: ${output_client_id}
                            compression: none
                            max_msg_bytes: ${max_msg_bytes}
                            round_robin_partitions: true
                            target_version: ${target_version}
                            timeout: 5s
                            topic: ${output_topic_name}
                    - type: kafka
                      kafka:
                        ack_replicas: true
                        addresses:
                          - ${kafka_broker_1}
                          - ${kafka_broker_2}
                          - ${kafka_broker_3}
                        client_id: ${output_client_id}
                        compression: none
                        max_msg_bytes: ${max_msg_bytes}
                        round_robin_partitions: true
                        target_version: ${target_version}
                        timeout: 5s
                        topic: ${failed_topic_name}
              - type: broker
                broker:
                  batching:
                    count: 5
                    period: 10s
                  copies: 1
                  pattern: try
                  outputs:
                    - type: retry
                      retry:
                        backoff:
                          initial_interval: 100ms
                          max_elapsed_time: 0s
                          max_interval: 3s
                        max_retries: 3
                        output:
                          elasticsearch:
                            healthcheck: true
                            index: ${elasticsearch_index}-$${!timestamp:2006.01.02}
                            pipeline: ""
                            sniff: true
                            timeout: 5s
                            type: log
                            urls:
                              - ${elasticsearch_url}
                    - type: kafka
                      kafka:
                        ack_replicas: true
                        addresses:
                          - ${kafka_broker_1}
                          - ${kafka_broker_2}
                          - ${kafka_broker_3}
                        client_id: ${output_client_id}
                        compression: none
                        max_msg_bytes: ${max_msg_bytes}
                        round_robin_partitions: true
                        target_version: ${target_version}
                        timeout: 5s
                        topic: ${failed_topic_name}
        condition:
          type: not
          not:
            type: processor_failed
    retry_until_success: false
metrics:
  type: statsd
  statsd:
    prefix: ${statsd_prefix}
    address: ${statsd_host}
    flush_period: 100ms
    network: ${statsd_network}
```

**Comment by assada** [comment]
P.S
We tried the config provided by @Jeffail. But it did not work and we decided to return to our version. (https://gist.github.com/Jeffail/ca85e1aec417febf396a1b6e9fae2fa9)

**Comment by Jeffail** [comment]
Hey @assada, if I help to break this config down using v3.7.0 would you be willing to try it out with that version?

Otherwise one thing that might help me diagnose this one would be if you set the metrics type to `http_server`, then after attempting to push some messages through give me the output from `curl http://localhost:4195/stats`.

**Comment by assada** [comment]
Yes, we can upgrade to 3.7 if this helps with the issue.

With metrics it will be much more difficult. This will require a lot of changes in our infrastructure =( 
Can you tell me what to look in metrics? Maybe we ourselves will notice something in grafana.

**Comment by assada** [comment]
Also we are try to simplifying configuration.
```yaml
input:
  type: kafka_balanced
  kafka_balanced:
    addresses:
      - ${kafka_broker_1}
      - ${kafka_broker_2}
      - ${kafka_broker_3}
    client_id: ${input_client_id}
    commit_period: 1s
    consumer_group: ${consumer_group}
    fetch_buffer_cap: 256
    max_processing_period: 3s
    start_from_oldest: true
    target_version: ${target_version}
    group:
      heartbeat_interval: 3s
      rebalance_timeout: 60s
      session_timeout: 10s
    topics:
      - ${topic_name}

pipeline:
  processors:
    - type: archivarius
output:
  type: elasticsearch
  elasticsearch:
    healthcheck: true
    index: ${elasticsearch_index}-$${!timestamp:2006.01.02}
    pipeline: ""
    sniff: true
    timeout: 5s
    type: log
    urls:
      - ${elasticsearch_url}
metrics:
  type: statsd
  statsd:
    prefix: ${statsd_prefix}
    address: ${statsd_host}
    flush_period: 100ms
    network: ${statsd_network}
logger:
  level: ALL
```


Disabled batching and left only elasticsearch output. And this version also loses messages. (All messages are processed by the processor normally looking at the logs)
