### ISSUE TITLE
Strategy for stopping on unprocessable message

### ISSUE THREAD

**Issue by simonhdickson** [Jeffail/benthos#355]
Currently we're working on a process where we want to handle only known good messages, but if we hit an unprocessable message instead of dead lettering or skipping, we want to enter into a crash loop (or just attempt to re-process again without acking the message). Is there a good way to cause benthos to enter into such a state?

**Comment by Jeffail** [comment]
Hey @simonhdickson, you can do something like that with a `while` loop. If there's no chance that the processing step might succeed then you might as well do something like this:

```yaml
pipeline:
  processors:
  - # TODO: Processor that might fail
  - while:
      condition:
        type: processor_failed
      processors:
        - log:
            level: ERROR
            fields:
              content: "${!content}"
              error: "${!error}"
            message: "Failed to process message"
        - sleep:
            duration: "1s"
```

That'll loop forever (because the error flag is never cleared) and log the error the message caused every second (to make sure you don't miss it), until eventually you stop Benthos and deal with the underlying issue.

If you have multiple processing threads then it's possible that other messages might continue processing successfully whilst that error loop blocks.

If, however, the processor might succeed on subsequent attempts then you should retry it for each loop:

```yaml
pipeline:
  processors:
  - # TODO: Processor that might fail
  - while:
      condition:
        type: processor_failed
      processors:
        - log:
            level: ERROR
            fields:
              content: "${!content}"
              error: "${!error}"
            message: "Failed to process message"
        - sleep:
            duration: "1s"
        - type: catch # Clear the error flag
        - # TODO: Attempt your processor again
```

**Comment by Jeffail** [comment]
Also what type of input source are you using? If it's something like AMQP then it might be better to immediately Nack the message rather than block the pipeline. It's possible to do something like that but it's a little bit hacky so I'd probably need to build something more sensible.

**Comment by simonhdickson** [comment]
This is connecting to Kafka, thanks I think this might work.

**Comment by Jeffail** [comment]
Okay, if you're batching at the input level then don't forget to wrap this in a `for_each`, or change the condition:

```yaml
  - while:
      condition:
        type: processor_failed
```

To

```yaml
  - while:
      condition:
        any:
          type: processor_failed
```

(If any message in the batch failed)
