### ISSUE TITLE
Support splitting a JSON array if present, passing if not

### ISSUE THREAD

**Issue by gregorskii** [Jeffail/benthos#376]
Hi there,

I bet this is on me not knowing how to use it... but... I would like to optionally split a json array into multiple single outputs.

I can split an array input:

```
[
	{
		"cats": true
	},
	{
		"cats": true
	}
]
```

Into two messages to the output using this config:

```
pipeline:
  processors:
    - type: unarchive
      unarchive:
        format: json_array
```

But it seems to fail when the input is not an array, is there a way to optionally run the unarchive?

Thanks

**Comment by Jeffail** [comment]
Hey @gregorskii, you could use a [`conditional`](https://www.benthos.dev/docs/components/processors/conditional) processor:

```yaml
pipeline:
  processors:
    - conditional:
        condition:
          jmespath:
            query: "type(@) == 'array'"
        processors:
        - unarchive:
            format: json_array
```

There's also a [`switch`](https://www.benthos.dev/docs/components/processors/switch) processor that is similar.
