### ISSUE TITLE
Output `gcp_pubsub` attributes

### ISSUE THREAD

**Issue by gregorskii** [Jeffail/benthos#377]
Is it possible to promote properties of a JSON input to attributes in `gcp_pubsub`?

https://cloud.google.com/pubsub/docs/reference/rest/v1/PubsubMessage

I would like to promote things like event timestamps to `attributes.time`.

It looks like the `gcp_pubsub` output puts the data into `Message Body` on the GCP side.

![Screen Shot 2020-02-14 at 11 10 44 AM](https://user-images.githubusercontent.com/1130448/74560110-b5704800-4f1a-11ea-8ad3-bffbc1f2c6b7.png)

We are using the attributes to sort the data in Cloud Dataflow:

```
read = PubsubIO
    .readMessagesWithAttributes()
    .withTimestampAttribute("time")
    .fromTopic(defaultOptions.getTopic());
```
EDIT:
In the pubsub GO lib the attributes would go in the attributes field of the `message` struct here:
https://github.com/googleapis/google-cloud-go/blob/pubsub/v1.2.0/pubsub/message.go#L36

You could likely pull off fields from the JSON object using jmespath and store them in an additional input to the `gcp_pubsub` output.

Likely this would require code updates. But I wanted to confirm it was not possible via some other means and whether the parsing of attributes is possible.

Thanks!

**Comment by Jeffail** [comment]
Hey @gregorskii, in Benthos there's the raw message contents (in your case a JSON payload) and also the metadata of a message (a map of key/value pairs), when messages are sent to GCP pubsub the metadata of each message is set as attributes.

That means you've got full control over what gets sent as the payload and what attributes you set, but you need to control it using the [`metadata` processor](https://www.benthos.dev/docs/components/processors/metadata). For example you could do something like this:

```yaml
pipeline:
  processors:
  # Optionally remove all existing metadata added by your input
  - metadata:
      operator: delete_all

  # Add a new metadata field from the contents of your message
  - metadata:
      operator: set
      key: time
      value: ${!json_field:event.timestamp}

  # Optionally restructure your JSON document to whatever you want as the published payload
  - jmespath:
      query: |
        {
          foo: event.body,
          id: event.id
        }
```

If you wanted to upload only the contents of a particular field as the payload then you can swap the above `jmespath` processor for something like:

```yaml
  - json:
      operator: select
      path: event.message
```

If there are lots of metadata fields you want to copy out of the payload then listing several `metadata` processors might be a bit of a pain. In that case you can shorten it somewhat with the [`awk`](https://www.benthos.dev/docs/components/processors/awk) processor that provides a `metadata_set` function:

```yaml
  - awk:
      program: |
        {
          metadata_set("time", json_get("event.time"));
          metadata_set("title", json_get("event.title"));
          metadata_set("host", json_get("event.host"));
        }
```

Let me know if that helps. I think it's worth me adding a specific guide for working with messages and metadata that would cover all of this.

**Comment by gregorskii** [comment]
This is very detailed and helpful. It would be a good idea to add this to the docs.

I appreciate the fast response and detailed help. It’s also good to know that Benthos can do this. There is quite a lot of power built into it and it’s amazing to see the yaml config can be so expressive.

Thanks!

**Comment by gregorskii** [comment]
This seems to be working, but the attributes come across hashed somehow..

<img width="802" alt="Screen Shot 2020-02-15 at 10 32 47 AM" src="https://user-images.githubusercontent.com/1130448/74593280-976c1b80-4fde-11ea-8f1b-f6ede7039058.png">

Given the event:

```
{
	"event": "testEvent",
	"timestamp": 1581292860,
	"metadata": {
		"schema_version": "1.0.0"
	}
}
```

The attributes are all `c60e6e6c8f39` in the Google Console.

Config:

```
pipeline:
  processors:
    - conditional:
        condition:
          jmespath:
            query: "type(@) == 'array'"
        processors:
        - unarchive:
            format: json_array

    # Optionally remove all existing metadata added by your input
    - metadata:
        operator: delete_all

    # Add a new metadata field from the contents of your message
    - for_each:
      - metadata:
          operator: set
          key: time
          value: ${!json_field:timestamp}
      - metadata:
          operator: set
          key: schema_version
          value: ${!json_field:metadata.schema_version}
      - metadata:
          operator: set
          key: event
          value: ${!json_field:event}
```

**Comment by Jeffail** [comment]
Hey @gregorskii,

This might be a problem during processing (in the config) or during transit (in the output code). Unfortunately I don't have a GCP account with credits set up to try it out for myself right now. As a sanity check can you run the config with this added log processor at the end:

```yaml
pipeline:
  processors:
    - conditional:
        condition:
          jmespath:
            query: "type(@) == 'array'"
        processors:
        - unarchive:
            format: json_array

    # Optionally remove all existing metadata added by your input
    - metadata:
        operator: delete_all

    # Add a new metadata field from the contents of your message
    - for_each:
      - metadata:
          operator: set
          key: time
          value: ${!json_field:timestamp}
      - metadata:
          operator: set
          key: schema_version
          value: ${!json_field:metadata.schema_version}
      - metadata:
          operator: set
          key: event
          value: ${!json_field:event}
      - log:
          message: "Metadata object: ${!metadata_json_object}"
```

That'll show in the logs whether the metadata fields for each message are as they should be before getting published.

**Comment by Jeffail** [comment]
Also you could try consuming the same topic using another Benthos instance, then print the attributes for messages consumed with the same log processor.

```yaml
input:
  gcp_pubsub:
    project: TODO
    subscription: TODO

pipeline:
  processors:
    - text:
        operator: set
        value: "Content: ${!content}, Attributes: ${!metadata_json_object}"

output:
  type: stdout
```

That'll consume messages from the topic and prints the content and attributes (as a JSON object) to stdout.

**Comment by Jeffail** [comment]
Was actually pretty quick and easy to set up, tried it with some test data and it's showing the raw contents:

![Screenshot_20200215_210853](https://user-images.githubusercontent.com/3921142/74595279-8ef3ff00-5037-11ea-8841-b90ed393e43a.png)

I set up my topic and sub using default settings, is there anything unique in your configuration I can try out?

**Comment by gregorskii** [comment]
Mine is setup with a default topic and subscription as well.

When using any of the logging or debugging tools things like `${!metadata_json_object}` come up empty in the output, and logger:

```
    - log:
        level: INFO
        message: "${!metadata_json_object}"
```

Equals:

```
benthos_1  | {"@timestamp":"2020-02-15T21:52:46Z","@service":"benthos","level":"INFO","component":"benthos.pipeline.processor.5","message":""}
benthos_1  | {
benthos_1  | 	"event": "testEvent",
benthos_1  | 	"timestamp": 1581292860,
benthos_1  | 	"metadata": {
benthos_1  | 		"schema_version": "1.0.0"
benthos_1  | 	}
benthos_1  | }
```

I am running it with:
https://hub.docker.com/layers/jeffail/benthos/3.10.0/images/sha256-18221ae409fff363dfe929b6f60efb4dae2a4879236a3658c03879c63aa9521e?context=explore

**Comment by Jeffail** [comment]
Are you able to give me the full config?

**Comment by gregorskii** [comment]
```
http:
  address: 0.0.0.0:1337
  read_timeout: 5s
  root_path: /benthos
  debug_endpoints: false

input:
  type: broker
  broker:
    copies: 1
    inputs:
    - type: http_server
      http_server:
        address: ""
        cert_file: ""
        key_file: ""
        path: /track
        timeout: 5s
        ws_path: /track/ws

buffer:
  type: memory
  memory:
    limit: 1_000_000_000

pipeline:
  processors:
    - log:
        level: INFO
        message: "DATA ${!json_field:event}"

    - conditional:
        condition:
          jmespath:
            query: "type(@) == 'array'"
        processors:
        - unarchive:
            format: json_array

    # Optionally remove all existing metadata added by your input
    - metadata:
        operator: delete_all

    # Add a new metadata field from the contents of your message
    - metadata:
        operator: set
        key: time
        value: ${!json_field:timestamp}
    - metadata:
        operator: set
        key: schema_version
        value: ${!json_field:metadata.schema_version}
    - metadata:
        operator: set
        key: event
        value: ${!json_field:event}

output:
  type: broker
  broker:
    copies: 25
    pattern: greedy
    outputs:
    - type: gcp_pubsub
      gcp_pubsub:
        project: "${GCP_PROJECT}"
        topic: "${GCP_TOPIC}"

logger:
  prefix: benthos
  level: INFO
  add_timestamp: true
  json_format: true
  static_fields:
    '@service': benthos

shutdown_timeout: 20s
```

**Comment by gregorskii** [comment]
I can't get the lab to pluck JSON fields either:

https://lab.benthos.dev/l/JrYlAC6W3Ds

I have tried a bunch of things, I think the weird hashes in Google's output are null values as the json_field is not grabbing anything in the logger.

**Comment by Jeffail** [comment]
In the lab each line of the input tab is consumed as a separate message, so it'll be broken up. If you switch to the settings tab the first option lets you change it so the whole contents of the tab are consumed as one message.

Got the settings here: https://lab.benthos.dev/l/cg8GGAMLx4A

**Comment by gregorskii** [comment]
Yep the lab works then.

**Comment by Jeffail** [comment]
Modified your above example slightly:

```yaml
http:
  address: 0.0.0.0:1337
  read_timeout: 5s
  root_path: /benthos
  debug_endpoints: false

input:
  type: broker
  broker:
    copies: 1
    inputs:
    - type: http_server
      http_server:
        address: ""
        cert_file: ""
        key_file: ""
        path: /track
        timeout: 5s
        ws_path: /track/ws

buffer:
  type: memory
  memory:
    limit: 1_000_000_000

pipeline:
  processors:
    - conditional:
        condition:
          jmespath:
            query: "type(@) == 'array'"
        processors:
        - unarchive:
            format: json_array

    # Optionally remove all existing metadata added by your input
    - metadata:
        operator: delete_all

    # Add a new metadata field from the contents of your message
    - for_each:
      - log:
          level: INFO
          message: "DATA ${!json_field:event}"
      - metadata:
          operator: set
          key: time
          value: ${!json_field:timestamp}
      - metadata:
          operator: set
          key: schema_version
          value: ${!json_field:metadata.schema_version}
      - metadata:
          operator: set
          key: event
          value: ${!json_field:event}
      - log:
          message: "METADATA: ${!metadata_json_object}"

output:
  type: broker
  broker:
    copies: 25
    pattern: greedy
    outputs:
    - type: stdout

logger:
  prefix: benthos
  level: INFO
  add_timestamp: true
  json_format: true
  static_fields:
    '@service': benthos

shutdown_timeout: 20s
```

If I feed it the file:

```json
[{
	"event": "testEvent",
	"timestamp": 1581292860,
	"metadata": {
		"schema_version": "1.0.0"
	}
},{
	"event": "testEvent2",
	"timestamp": 1581292900,
	"metadata": {
		"schema_version": "2.0.0"
	}
}]
```

With `cat sample.json | curl http://localhost:1337/track --data-binary @-` I'm getting the expected logs:

```
{"@timestamp":"2020-02-15T23:27:46Z","@service":"benthos","level":"INFO","component":"benthos","message":"Launching a benthos instance, use CTRL+C to close."}
{"@timestamp":"2020-02-15T23:27:46Z","@service":"benthos","level":"INFO","component":"benthos","message":"Listening for HTTP requests at: http://0.0.0.0:1337"}
{"@timestamp":"2020-02-15T23:27:47Z","@service":"benthos","level":"INFO","component":"benthos.pipeline.processor.2.0","message":"DATA testEvent"}
{"@timestamp":"2020-02-15T23:27:47Z","@service":"benthos","level":"INFO","component":"benthos.pipeline.processor.2.0","message":"DATA testEvent2"}
{"@timestamp":"2020-02-15T23:27:47Z","@service":"benthos","level":"INFO","component":"benthos.pipeline.processor.2.4","message":"METADATA: {\"event\":\"testEvent\",\"schema_version\":\"1.0.0\",\"time\":\"1581292
860\"}"}
{"@timestamp":"2020-02-15T23:27:47Z","@service":"benthos","level":"INFO","component":"benthos.pipeline.processor.2.4","message":"METADATA: {\"event\":\"testEvent2\",\"schema_version\":\"2.0.0\",\"time\":\"158129
2900\"}"}
{"event":"testEvent","metadata":{"schema_version":"1.0.0"},"timestamp":1581292860}
{"event":"testEvent2","metadata":{"schema_version":"2.0.0"},"timestamp":1581292900}
```

Feel like we're zeroing in on it but I'm wrapping up for the day. I might get a chance to try it out some more tomorrow.

**Comment by gregorskii** [comment]
Awesome, and no problem! I’ll keep playing with it and see what I can find.

**Comment by Jeffail** [comment]
Okay that's maybe a clue. Can you set `debug_endpoints: true` and then paste me the output from `curl http://localhost:1337/debug/config/yaml`?

Looking at your logs and I would hazard a guess that the function interpolation expressions (`${!json_field:event}`, etc) are actually being resolved by something before Benthos reads the config. The reason I'm thinking that is because if the `json_field` interpolation function doesn't find a value it returns `null`, and if the `metadata_json_object` doesn't find any metadata keys it resolves to an empty object `{}`, so if the interpolation function was failing I would expect the logs to look like this:

```
benthos_1  | {"@timestamp":"2020-02-16T03:08:44Z","@service":"benthos","level":"INFO","component":"benthos.pipeline.processor.2.0","message":"DATA null"}
benthos_1  | {"@timestamp":"2020-02-16T03:08:44Z","@service":"benthos","level":"INFO","component":"benthos.pipeline.processor.2.4","message":"METADATA: {}"}
```

Whereas you're seeing nothing in the place of the interp functions, which could happen if the config is being copied or moved by a process that attempts to resolve the interp functions as environment variables.

**Comment by gregorskii** [comment]
```
http:
    address: 0.0.0.0:1337
    read_timeout: 5s
    root_path: /benthos
    debug_endpoints: true
input:
    type: broker
    broker:
        batching:
            byte_size: 0
            condition:
                type: static
                static: false
            count: 1
            period: ""
            processors: []
        copies: 1
        inputs:
          - type: http_server
            http_server:
                address: ""
                cert_file: ""
                key_file: ""
                path: /track
                rate_limit: ""
                sync_response:
                    headers:
                        Content-Type: application/octet-stream
                timeout: 5s
                ws_path: /track/ws
                ws_rate_limit_message: ""
                ws_welcome_message: ""
buffer:
    type: memory
    memory:
        batch_policy:
            byte_size: 0
            condition:
                type: static
                static: false
            count: 0
            enabled: false
            period: ""
            processors: []
        limit: 1000000000
pipeline:
    processors:
      - type: conditional
        conditional:
            condition:
                type: jmespath
                jmespath:
                    part: 0
                    query: type(@) == 'array'
            else_processors: []
            processors:
              - type: unarchive
                unarchive:
                    format: json_array
                    parts: []
      - type: metadata
        metadata:
            key: example
            operator: delete_all
            parts: []
            value: ${!hostname}
      - type: for_each
        for_each:
          - type: log
            log:
                fields: {}
                level: INFO
                message: 'DATA '
          - type: metadata
            metadata:
                key: time
                operator: set
                parts: []
                value: ${!hostname}
          - type: metadata
            metadata:
                key: schema_version
                operator: set
                parts: []
                value: ${!hostname}
          - type: metadata
            metadata:
                key: event
                operator: set
                parts: []
                value: ${!hostname}
          - type: log
            log:
                fields: {}
                level: INFO
                message: 'METADATA: '
    threads: 1
output:
    type: broker
    broker:
        batching:
            byte_size: 0
            condition:
                type: static
                static: false
            count: 1
            period: ""
            processors: []
        copies: 25
        outputs:
          - type: stdout
            stdout:
                delimiter: ""
        pattern: greedy
resources:
    caches: {}
    conditions: {}
    processors: {}
    rate_limits: {}
logger:
    prefix: benthos
    level: INFO
    add_timestamp: true
    json_format: true
    static_fields:
        '@service': benthos
metrics:
    type: http_server
    http_server:
        prefix: benthos
tracer:
    type: none
    none: {}
shutdown_timeout: 20s
```
