### ISSUE TITLE
Improvements to the avro processor

### ISSUE THREAD

**Issue by gregorskii** [Jeffail/benthos#381]
HI again,

I am working with the Avro processor. We are trying to use it to process Avro textual records (or pure JSON) as the event input, and marshal it to Avro a record to send to GCP as bytes.

Currently the process we have been debugging in #377 is working, but we are trying to move Avro validation and processing closer to our event processing side (after GCP).

In our ideal flow our event publishers would send either pure JSON or textual Avro records to Benthos, Benthos would process those records into Avro records and transmit them to our pipeline as a Avro byte object. The pipeline would be able to validate the bytes with the Avro reader and writer.

Is this possible with Benthos and the Avro processor currently, or am I misunderstanding what the Avro processor is doing?

I have added it to a test pipeline with a schema defined and it seems to have no affect.

A second question is whether the Avro.schema property can be loaded from a file dynamically, or does it have to come from a single Avro schema definition?

Here is our example Avro schema:

```
{
  "type" : "record",
  "name" : "Event_TestEvent",
  "fields" : [ {
    "name" : "event_type",
    "type" : {
      "type" : "enum",
      "name" : "EventType",
      "symbols" : [ "TestEvent" ]
    }
  }, {
    "name" : "metadata",
    "type" : {
      "type" : "record",
      "name" : "Metadata",
      "fields" : [ {
        "name" : "schema_version",
        "type" : "string"
      } ]
    }
  }, {
    "name" : "event_properties",
    "type" : {
      "type" : "record",
      "name" : "TestEventProperties",
      "fields" : [ {
        "name" : "source",
        "type" : [ "null", "string" ],
        "default" : null
      } ]
    }
  }, {
    "name" : "event_id",
    "type" : "string"
  }, {
    "name" : "timestamp",
    "type" : {
      "type" : "long",
      "logicalType" : "timestamp-millis"
    }
  } ]
}
```

Benthos config:

```
http:
  address: 0.0.0.0:1337
  read_timeout: 5s
  root_path: /benthos
  debug_endpoints: true

input:
  type: broker
  broker:
    copies: 25
    inputs:
    - type: http_server
      http_server:
        address: ""
        cert_file: ""
        key_file: ""
        path: /track
        timeout: 5s
        ws_path: /track/ws

buffer:
  type: memory
  memory:
    limit: 1_000_000_000

pipeline:
  processors:
    - avro:
        operator: from_json
        encoding: textual
        schema: "{\"type\":\"record\",\"name\":\"Event_TestEvent\",\"fields\":[{\"name\":\"event_type\",\"type\":{\"type\":\"enum\",\"name\":\"EventType\",\"symbols\":[\"TestEvent\"]}},{\"name\":\"metadata\",\"type\":{\"type\":\"record\",\"name\":\"Metadata\",\"fields\":[{\"name\":\"schema_version\",\"type\":\"string\"}]}},{\"name\":\"event_properties\",\"type\":{\"type\":\"record\",\"name\":\"TestEventProperties\",\"fields\":[{\"name\":\"source\",\"type\":[\"null\",\"string\"],\"default\":null}]}},{\"name\":\"event_id\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}"

    - log:
        level: INFO
        message: "DATA ${!content}"

output:
  type: stdout

logger:
  prefix: benthos
  level: INFO
  add_timestamp: true
  json_format: true
  static_fields:
    '@service': benthos

shutdown_timeout: 20s
```

Thanks!

**Comment by Jeffail** [comment]
Hey @gregorskii, yeah that should be possible.

The dynamic schema part is harder, do you mean selecting a schema based on a field within each message?

Right now if you want to select from N schemas then you'd need to configure that many processors and use a switch or something to select them, which is pretty gross. It would be quick to add a `schema_file` field as an alternative to pasting the whole schema in the config, and then maybe we can explore allowing function interpolation on that field.

**Comment by gregorskii** [comment]
We can try using multiple schema definitions and a switch to see if it works for now, then enhance it later.

It seemed like the Avro processor had no affect, how do we debug it or test if it was working?

It seemed if we added new fields to the json input the output would have the field even if the schema did not define that field, and the same if we removed them. We tried outputting the content, and checking on the pub sub side to see what the final output would be.

Thanks

**Comment by Jeffail** [comment]
What you should be seeing on the output is a textual avro payload, if you get JSON out then it'll be failing to convert it. Either set logging to debug mode to see if there are messages failing validation or add an error handle to expose it:

```yaml
pipeline:
  processors:
    - avro:
        operator: from_json
        encoding: textual
        schema: "{\"type\":\"record\",\"name\":\"Event_TestEvent\",\"fields\":[{\"name\":\"event_type\",\"type\":{\"type\":\"enum\",\"name\":\"EventType\",\"symbols\":[\"TestEvent\"]}},{\"name\":\"metadata\",\"type\":{\"type\":\"record\",\"name\":\"Metadata\",\"fields\":[{\"name\":\"schema_version\",\"type\":\"string\"}]}},{\"name\":\"event_properties\",\"type\":{\"type\":\"record\",\"name\":\"TestEventProperties\",\"fields\":[{\"name\":\"source\",\"type\":[\"null\",\"string\"],\"default\":null}]}},{\"name\":\"event_id\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}"

    - catch:
      - log:
          message: "Validation failed due to: ${!error}"

    - log:
        level: INFO
        message: "DATA ${!content}"
```

The docs ought to have some usage examples to demo this stuff but I've been waiting to hear back on use cases, this is probably a good case study.
