### ISSUE TITLE
Mqtt input appears to ignore configured `urls` in streams mode

### ISSUE THREAD

**Issue by jackmac92** [Jeffail/benthos#382]
Just wanted to report a strange issue I had when trying to use mqtt inputs as part of streams mode. Hopefully I'm not doing anything too stupid

```
input:
  broker:
    inputs:
      - type: mqtt
        mqtt-watever:
          urls:
          - tcp://PRIVATE_MQTT_SERVER_IP:1883
          clean_session: true
          user: BENTHOS_MQTT_USER
          password: BENTHOS_MQTT_PASSWORD
          client_id: benthos-transcriber
          qos: 0
          topics:
            - zanzito/#
            - homeassistant/#
      - type: mqtt
        mqtt-vip:
          urls:
          - tcp://PRIVATE_MQTT_SERVER_IP:1883
          clean_session: true
          user: BENTHOS_MQTT_USER
          password: BENTHOS_MQTT_PASSWORD
          client_id: benthos-vip-transcriber
          qos: 1
          topics:
            - dropLoop/#
            - monitor/#

output:
  inproc: 'emqx-mqtt'
```

That config resulted in a spamming error message

`Failed to connect to mqtt: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused`
(Full error below)
```
{"@timestamp":"2020-02-22T20:06:40Z","@service":"benthos","level":"ERROR","component":"benthos.mqtt-inproc.input.broker.inputs.0","message":"Failed to connect to mqtt: Network Error : dial tcp 127.0.0.1:1883: connect: connection refused"}
```

The above error occurred at first in docker, but the error message when running with a local binary of benthos generates is almost identical, just a different representation of localhost  `[::1]:1883`

I wondered if two different mqtt connections might be causing the issue, but I get the same error when only one mqtt input is used.

However, when run as part of a single config file (not streams mode) the above works as expected

**Comment by Jeffail** [comment]
Hey @jackmac92, the fields `mqtt-watever` and `mqtt-vip` are invalid, they must match the type being created (`mqtt`), you can also get rid of the `type: mqtt` part:

```yaml
input:
  broker:
    inputs:
      - mqtt:
          urls:
          - tcp://PRIVATE_MQTT_SERVER_IP:1883
          clean_session: true
          user: BENTHOS_MQTT_USER
          password: BENTHOS_MQTT_PASSWORD
          client_id: benthos-transcriber
          qos: 0
          topics:
            - zanzito/#
            - homeassistant/#
      - mqtt:
          urls:
          - tcp://PRIVATE_MQTT_SERVER_IP:1883
          clean_session: true
          user: BENTHOS_MQTT_USER
          password: BENTHOS_MQTT_PASSWORD
          client_id: benthos-vip-transcriber
          qos: 1
          topics:
            - dropLoop/#
            - monitor/#

output:
  inproc: 'emqx-mqtt'
```

There should be some warning logs that unrecognised fields are present in the config, unfortunately they're easy to miss and Benthos still runs when that is the case (unless you run with `--strict`). In the next major version release I'm going to make strict config validation the default to try and avoid these issues.
