### ISSUE TITLE
numeric field operations

### ISSUE THREAD

**Issue by Lichtsinnig** [Jeffail/benthos#384]
Hi, how can I add 2 numbers in a configuration?
As I understand it, the expression is perceived as a string.

input

```
curl http://localhost:4195/t/post -d '{"fields": "ppp","EventID":"4720","ventropia":"t","summary":"test3","issuetype":"www"}' -H "Content-Type: application/json" -X POST
```
Config

````
input:
  type: http_server
buffer:
  type: memory
pipeline:
  processors:
    - json:
        path: CCC
        operator: set
        value: 0  
    - switch:
      - condition:
        json:
          path: EventID
          operator: equals
          arg: "4720" 
        processors:
          - json:
              operator: set
              path: CCC
              value: ${!json_field:CCC} + 1
output:
  type: stdout
  stdout:
    delimiter: ""

```

Result obtained
output

```
{"CCC":"0 + 1","EventID":"4720","fields":"ppp","issuetype":"www","summary":"test3","ventropia":"t"}
```

Desired result
output

```
{"CCC":"1","EventID":"4720","fields":"ppp","issuetype":"www","summary":"test3","ventropia":"t"}
```
