### ISSUE TITLE
Ability to write to input socket?

### ISSUE THREAD

**Issue by dselans** [Jeffail/benthos#385]
Hi,

Awesome project! Apologies if I missed this in the docs but is there a way to write to an input TCP socket on an interval?

Specifically, I need to do the equivalent of this: `echo mntr | nc some-ip 2181`

Thanks!

**Comment by Jeffail** [comment]
Hey @dselans, yeah you can do stuff like continuously read a source of data (like a sample file) and sleep for each message:

```yaml
input:
  read_until:
    input:
      file:
        path: ./input_data.txt
    restart_input: true
    condition:
      static: false

pipeline:
  processors:
    - sleep:
        duration: 100ms

output:
  socket:
    network: tcp
    address: some-ip:2181
```

If you don't want to bother reading a file and have a static string you want to send you can do something like this:

```yaml
input:
  read_until:
    input:
      http_client:
        url: http://localhost:4195/endpoints
    restart_input: true
    condition:
      static: false

pipeline:
  processors:
    - sleep:
        duration: 100ms
    - text:
        operator: set
        value: mntr

output:
  socket:
    network: tcp
    address: some-ip:2181
```

That uses an `http_client` input as a dummy just to create a message (by polling benthos's own http server) and then at the end of the pipeline you swap the message contents for your static string.
