### ISSUE TITLE
sort with uniq values in array

### ISSUE THREAD

**Issue by Lichtsinnig** [Jeffail/benthos#387]
I have an array with duplicate values ​​[1,2,3,1,10,1]. How can I sort an array with unique values?
And get [1,2,3,10]
The only way to do this is with awk, are there any other options?

**Comment by DpoBoceka** [comment]
Hey @Lichtsinnig, it's better be done by `awk`, yes. I can't think of a more efficient solution to this at the moment

**Comment by Lichtsinnig** [comment]
> Привет @Lichtsinnig , это лучше сделать `awk`, да. Я не могу придумать более эффективного решения этого вопроса в данный момент


I tried to make a configuration with awk but it failed :(

**Comment by DpoBoceka** [comment]
well, I thought you were able to get that done already. In that case I'm not positive, if `awk` would manage that demand.
Actually, it shouldn't be so hard to expand `json` processor functionality with `sort` and `unique` operators applied to arrays.

**Comment by Lichtsinnig** [comment]
Config 
```
input:
  type: http_server
buffer:
  type: memory
pipeline:
  processors:
    - process_field:
        codec: json
        path: list
        processors:
          - awk:
              program: |
                        BEGIN{a[$1]++}END{for(i in a) {print a[i]}}                                                        
output:
  type: stdout
  stdout:
    delimiter: ""
```

I get one element, but not the whole array :(

```
{"EventID":4720,"TargetUserNameT":"U","list":"1","u":123}
```
