### ISSUE TITLE
question: Parallel from S3

### ISSUE THREAD

**Issue by relistan** [Jeffail/benthos#388]
Love this project and have been using it for awhile now to good success. I'm struggling to understand from the docs and looking at the code how to achieve the following:

  * s3 input where it scans the files with the prefix
  * process them in parallel with fixed parallelism
  * write out to another path in S3 in parallel

It works fine in a single, non-parallel stream. I tried adding a broker in the input and a broker on the output and running the processors as input processors on the input broker. This still only ran a single item at a time as far as I can tell. I tried various other combinations. Am I missing something? Maybe just not possible with the S3 input? Help appreciated!

Something like (contrived, hopefully indented properly):
```yaml
input:
  broker:
    copies: 3
    inputs:
        - s3:
            bucket: "${S3_INPUT_BUCKET:somewhere}"
            region: "${S3_REGION:us-west-2}"
            prefix: "somewhere"
    processors:
      - ...
output:
  broker:
   copies: 3
   pattern: "round_robin"
   outputs:
     - s3: ...
```

**Comment by Jeffail** [comment]
Hey @relistan, which version of Benthos are you using? Since version `3.8.0` there's a bunch of changes that make this much easier. Firstly, when you configure a single input the messages will be automatically distributed across processing pipelines, so the following is all you should need in order to get your work distributed:

```yaml
input:
  s3:
    bucket: "${S3_INPUT_BUCKET:somewhere}"
    region: "${S3_REGION:us-west-2}"
    prefix: "somewhere"

pipeline:
  threads: 3
  processors:
    - ...
```

Although you might still find you're bottlenecked on the download speed.

Secondly, you can configure a single output and tune a `max_in_flight` in order to have that many messages sending in parallel at a time:

```yaml
output:
  s3:
    ...
    max_in_flight: 10
```

^ In the case where uploading objects takes significantly longer than downloading/processing this could potentially result in up to 10 objects being uploaded at a given time.

If you find your performance bottleneck is the rate at which you can download then unfortunately that's a little bit trickier as the S3 input currently downloads one object at a time, a `broker` would solve that normally but when you're downloading by prefix it would result in each object being downloaded multiple times.

You can solve that right now by going through the process of hooking up an SQS queue and distributing the downloads across brokered inputs that way. However, I can also look into refactoring the input so that prefix downloads can maybe be done in parallel, but I doubt I can get to that in the short term.
