### ISSUE TITLE
Failing on making benthos fetch external REST APIs

### ISSUE THREAD

**Issue by inliquid** [Jeffail/benthos#391]
We'd like to use `benthos` at our company, and the idea for solution we trying to build is that it will fetch a number of different sources, receive the data (basically, JSON), process it and store in some DB.  What I trying to experiment with at the moment, is let's say we have an external REST API which provides some JSON output, so I want `benthos` to retrieve data by periodically `GET`ting specific url and storing that data (for now I temporary use Postgres with `jsonb` fields but later want to switch to Mongo - don't know yet, but maybe by developing a plugin). 

So that's the config:
```
# http:
#   address: 0.0.0.0:4195
#   read_timeout: 5s
#   root_path: /benthos
#   debug_endpoints: false
input:
  # type: stdin
  # stdin:
  #   delimiter: ""
  #   max_buffer: 1e+06
  #   multipart: false
  http_client:
  # url: http://localhost:4195/get
  url: "https://api.openweathermap.org/data/2.5/forecast?lat=55.915822&lon=37.226880&appid=***"
  # url: "http://127.0.0.1:8888"
  verb: GET
  # headers:
  #   Content-Type: application/json
  rate_limit: ""
  timeout: 10s
  payload: ""
  # stream:
  #   enabled: false
  #   reconnect: true
buffer:
  type: none
  none: {}
pipeline:
  processors: 
    - for_each:
      - sql:
          driver: postgres
          dsn: postgresql://benthos:benthos@127.0.0.1/benthos?sslmode=disable
          query: "INSERT INTO footable (foo) VALUES ($1);"
          args:
          - ${!json_field:foo}
          # - ${!json_field:document.bar}
          # - ${!metadata:kafka_topic}
  threads: 1
output:
  # type: stdout
  # stdout:
  #   delimiter: ""
  drop: {}
resources:
  caches: {}
  conditions: {}
  processors: {}
  rate_limits: {}
logger:
  prefix: benthos
  # level: ALL
  level: DEBUG
  add_timestamp: true
  json_format: true
  static_fields:
    '@service': benthos
metrics:
  type: http_server
  http_server:
    prefix: benthos
tracer:
  type: none
  none: {}
shutdown_timeout: 20s
```

1. First problem I got to is that `http_client` for some reason results in 404 responses, while same url works fine when sent from the browser:
```
{"@timestamp":"2020-03-03T13:20:59+03:00","@service":"benthos","level":"ERROR","component":"benthos.input","message":"Failed to read message: HTTP request returned unexpected response code (404): 404 Not Found"}
{"@timestamp":"2020-03-03T13:21:03+03:00","@service":"benthos","level":"ERROR","component":"benthos.input","message":"Failed to read message: HTTP request returned unexpected response code (404): 404 Not Found"}
```

2. Second problem is that seems like `benthos` does not even trying to send a request on given url. I spawned a `nc` instance to listen on port `8888`:
```
c:\bin>nc -vv -l -p 8888
listening on [any] 8888 ...
```
and switched `url`:
```
  url: "http://127.0.0.1:8888"
```
and, surprisingly, there is nothing (if I use browser I do see a request in netcat output).

3. Setting log level to `DEBUG` or `ALL` doesn't help, there is no additional information in logs, and I have no idea what's in request and where is `benthos` trying to send it with 404 response. How am I supposed to debug such cases?

**Comment by Jeffail** [comment]
Hey @inliquid,

From your config example it looks like you're a victim of YAML indentation, the fields underneath `http_client` need to be indented like this:

```yaml
input:
  http_client:
    url: "https://api.openweathermap.org/data/2.5/forecast?lat=55.915822&lon=37.226880&appid=***"
    verb: GET
    rate_limit: ""
    timeout: 10s
    payload: ""
```

Otherwise they get ignored and Benthos will run with default values for the `http_client` input (causing the 404 logs).

You can avoid this sort of issue by running benthos with strict mode, i.e. `benthos --strict -c ./config.yaml`, and it'll exit with an error if there are unrecognized fields in your config. Unfortunately, it's not default behavior to run this way, it's planned to be in the future but I haven't yet as it'd be a breaking change (arguably) so I'm waiting for the next major version release.

Benthos also shouldn't really have a concept of a default URL for this exact reason, I've opened https://github.com/Jeffail/benthos/issues/392 to deal with that separately.
