### ISSUE TITLE
jmespath and json with array

### ISSUE THREAD

**Issue by Lichtsinnig** [Jeffail/benthos#394]
Hi. @Jeffail.

I get an error when I access an array element.

input

```
{"issues":[{"id":123, "key":999},{"id":444, "key":555}], "rrr":"dfg"}
```

Config

```
input:
  type: http_server
buffer:
  type: memory
pipeline:
  processors:
    - process_field:
        codec: json
        path: issues
        processors:      
          - jmespath:
              query:  {issues:issues[0].id}
output:
  type: stdout
  stdout:
    delimiter: ""
```

output error

```
{"@timestamp":"2020-03-03T17:28:16+03:00","@service":"benthos","level":"ERROR","component":"benthos","message":"Failed to load stream configs: yaml: line 11: did not find expected ',' or '}'"}
```

Expected Result:

```
{"issues" : 123}
```

If I do not use an appeal to an array element, I get a valid configuration
