### ISSUE TITLE
Can http_server download files?

### ISSUE THREAD

**Issue by inliquid** [Jeffail/benthos#395]
Is it possible for `http_server` to download and process files `POST`ed as a form to given endpoint?

**Comment by DpoBoceka** [comment]
https://www.benthos.dev/docs/components/inputs/http_server#path-defaults-to-post
So, you should be able to combine those messages(raw bytes) into a single one and sent it the way you see fit. But in general it depends on the way you're transmitting the initial message(aka your file)

**Comment by DpoBoceka** [comment]
https://www.benthos.dev/docs/components/outputs/http_client

>  If the message has multiple parts (is a batch) the request will be sent according to RFC1341

**Comment by inliquid** [comment]
The case is pretty simple, for testing I use post form like this:
```html
    <form action="http://127.0.0.1:8080/post/" method="POST">
        <p><input type="file" name="photo" required multiple title="Upload one or more photos"></p>
        <p><input type="submit" value="Upload"></p>
    </form>
```
`http_server` config:
```yaml
  http_server:
    # address: ""
    address: 127.0.0.1:8080
    path: /post/
    # ws_path: /post/ws/
    timeout: 10s
    rate_limit: ""
```

as a result `benthos` is only able to see filename (that's what come in the body) and does not download file (or files, when there are many in multipart form).
