### ISSUE TITLE
JSON validate

### ISSUE THREAD

**Issue by gregorskii** [Jeffail/benthos#402]
Could there be a function to ensure JSON passed to the processor is valid? Currently incorrect JSON flows through the system to the output sink. It would be ideal to be able to catch it upfront. I do see there is a JSON schema function which could do something similar, but a simple check would be idea.

A alternate approach to this would be to request a field from the JSON object and if the field is null directly set the `processor_failed` meta field. Is this possible?

**Comment by DpoBoceka** [comment]
perhaps the `text` condition and the `is` operator of it could be extended to adopt such functionality.
https://www.benthos.dev/docs/components/conditions/text#is

**Comment by Jeffail** [comment]
Hey @gregorskii,

There's a `json` condition that allows you to check the existence of the root:

```yaml
pipeline:
  processors:
  - filter_parts:
      json:
        operator: exists
        path: .
```

Alternatively, if you're doing some processing on the JSON documents then they should error if the document isn't json, so you can just catch the error and remove the docs:

```yaml
pipeline:
  processors:
    - jmespath:
        query: ...
    - filter_parts:
        type: processor_failed
```

**Comment by Jeffail** [comment]
Also, because the `json` condition defaults to `operator: equals` with a path pointing to the root you can actually just write:

```yaml
pipeline:
  processors:
  - filter_parts:
      json: {}
```

Demo here: https://lab.benthos.dev/l/-xeOgY-l0N5

**Comment by gregorskii** [comment]
What is the process for filtering and grouping the errors?:

```
pipeline:
  processors:
    - filter_parts:
        json: {}
    - filter_parts:
        type: processor_failed

output:
  broker:
    pattern: greedy
    copies: 25
    outputs:
      - type: gcp_pubsub # Dead letter queue
        gcp_pubsub:
          project: "{{GCP_PROJECT}}"
          topic: "{{GCP_DEADLETTER_TOPIC}}"
        processors:
          - filter_parts:
              type: processor_failed
      - type: gcp_pubsub # Success
        gcp_pubsub:
          project: "{{GCP_PROJECT}}"
          topic: "{{GCP_TOPIC}}"
        processors:
          - filter_parts:
              not:
                type: processor_failed
```

Thanks!

**Comment by Jeffail** [comment]
Hey @gregorskii,

If you want to route non-JSON docs to their own topic then it's easiest to set a metadata field and interpolate the `topic` of a single GCP output:

```yaml
pipeline:
  processors:
    - switch:
        - condition:
            json: {}
          processors:
            - metadata:
                operator: set
                key: dest_topic
                value: "{{GCP_TOPIC}}"
        - processors:
            - metadata:
                operator: set
                key: dest_topic
                value: "{{GCP_DEADLETTER_TOPIC}}"

output:
  gcp_pubsub:
    project: "{{GCP_PROJECT}}"
    topic: "${!metadata:dest_topic}"
    max_in_flight: 25
```

Also another thing to note is that since v3.8.0 instead of using a `greedy` broker you can just set a field `max_in_flight`.

**Comment by Jeffail** [comment]
If you're just looking for a more generic pattern for catching all errors then you can also do something similar with `try` and `catch`:

```yaml
pipeline:
  processors:
    - metadata:
        operator: set
        key: dest_topic
        value: "{{GCP_TOPIC}}"
        
    - try:
        - jmespath:
            query: "TODO"
        - ... more processors that might fail ...
        
    - catch:
        - metadata:
            operator: set
            key: dest_topic
            value: "{{GCP_DEADLETTER_TOPIC}}"

output:
  gcp_pubsub:
    project: "{{GCP_PROJECT}}"
    topic: "${!metadata:dest_topic}"
    max_in_flight: 25
```

**Comment by gregorskii** [comment]
Awesome thank you again for the excellent examples! I will try to get this working tomorrow. Appreciate it once again!

**Comment by gregorskii** [comment]
Putting it all together I came up with this:

```
http:
  address: 0.0.0.0:1337
  read_timeout: 5s
  root_path: /benthos
  debug_endpoints: false

input:
  type: broker
  broker:
    copies: 25
    inputs:
    - type: http_server
      http_server:
        address: ""
        cert_file: ""
        key_file: ""
        path: /track
        timeout: 5s
        ws_path: /track/ws

buffer:
  type: memory
  memory:
    limit: 1_000_000_000

pipeline:
  processors:
    - switch:
        - condition:
            json: {}
          processors:
            - metadata:
                operator: set
                key: dest_topic
                value: "{{GCP_DEADLETTER_TOPIC}}"

        - processors:
            - conditional:
                condition:
                  jmespath:
                    query: "type(@) == 'array'"
                processors:
                  - unarchive:
                      format: json_array

            # Optionally remove all existing metadata added by your input
            - metadata:
                operator: delete_all

            - metadata:
                operator: set
                key: dest_topic
                value: "{{GCP_TOPIC}}"

            # Add a new metadata field from the contents of your message
            - for_each:
                - metadata:
                    operator: set
                    key: timestamp
                    value: ${!json_field:timestamp}
                - metadata:
                    operator: set
                    key: schema_id
                    value: ${!json_field:metadata.schema_id}
                - metadata:
                    operator: set
                    key: event_id
                    value: ${!json_field:event_id}
                - metadata:
                    operator: set
                    key: event_type
                    value: ${!json_field:event_type}

output:
  gcp_pubsub:
    project: "{{GCP_PROJECT}}"
    topic: ${!metadata:dest_topic}
    max_in_flight: 25

logger:
  prefix: benthos
  level: INFO
  add_timestamp: true
  json_format: true
  static_fields:
    '@service': benthos

shutdown_timeout: 20s

```

But this results in the `topic` not being interpolated:

```
benthos_1  | {"@timestamp":"2020-03-12T22:09:46Z","@service":"benthos","level":"ERROR","component":"benthos.output","message":"Failed to connect to gcp_pubsub: rpc error: code = InvalidArgument desc = Invalid resource name given (name=projects/PROJECT/topics/${!metadata:dest_topic}). Refer to https://cloud.google.com/pubsub/docs/admin#resource_names for more information."}
```

**Comment by Jeffail** [comment]
Sorry @gregorskii, turns out interpolation functions on that field haven't been implemented. Fortunately it was quick to implement (https://github.com/Jeffail/benthos/commit/47b6d780b54accb422ea4498b3be7527f3a3d018), which gives you three options:

1. Temporarily work around this with a `broker`, I'll add an example at the bottom, and then use interpolations once I put a release out (probably in a week or so)
2. If you're comfortable building Benthos yourself then use the latest from master branch
3. I can put a release candidate out which would provide a release and docker images to pull from

This is currently the only feature added since the last release so ideally I want to avoid putting one out yet, but it's also not a bother if this is blocking you.

Example broker based work around:

```yaml
output:
  broker:
    pattern: fan_out
    outputs:
      - gcp_pubsub: # DLQ
          project: "{{GCP_PROJECT}}"
          topic: "{{GCP_DEADLETTER_TOPIC}}"
        processors:
          - filter_parts:
              metadata:
                operator: equals
                key: output_topic
                arg: "{{GCP_DEADLETTER_TOPIC}}"

      - gcp_pubsub: # Success
          project: "{{GCP_PROJECT}}"
          topic: "{{GCP_TOPIC}}"
        processors:
          - filter_parts:
              metadata:
                operator: equals
                key: output_topic
                arg: "{{GCP_TOPIC}}"
```

^ This would result in only one message in flight at a time (a current limitation of the `fan_out` broker), if needed you can make it even more gross with a greedy broker:

```yaml
output:
  broker:
    pattern: greedy
    copies: 25
    outputs:
    - broker:
        pattern: fan_out
        outputs:
          - gcp_pubsub: # DLQ
              project: "{{GCP_PROJECT}}"
              topic: "{{GCP_DEADLETTER_TOPIC}}"
            processors:
              - filter_parts:
                  metadata:
                    operator: equals
                    key: output_topic
                    arg: "{{GCP_DEADLETTER_TOPIC}}"

          - gcp_pubsub: # Success
              project: "{{GCP_PROJECT}}"
              topic: "{{GCP_TOPIC}}"
            processors:
              - filter_parts:
                  metadata:
                    operator: equals
                    key: output_topic
                    arg: "{{GCP_TOPIC}}"
```

^ This would get you 25 max in flight messages but at the cost of opening 50 connections in total.

**Comment by gregorskii** [comment]
I can swap it to a greedy broker to test it and wait for the release.

The project we are working on will not be released for a couple more weeks.

Thank you! 🙏

**Comment by gregorskii** [comment]
This was the combo of configs that worked for me:

```
pipeline:
  processors:
    - switch:
        - condition:
            json: {}
          processors:
            - metadata:
                operator: set
                key: dest_topic
                value: "{{GCP_TOPIC}}"

            - conditional:
                condition:
                  jmespath:
                    query: "type(@) == 'array'"
                processors:
                  - unarchive:
                      format: json_array

            # Optionally remove all existing metadata added by your input
            - metadata:
                operator: delete_all

            - metadata:
                operator: set
                key: dest_topic
                value: "{{GCP_TOPIC}}"

            # Add a new metadata field from the contents of your message
            - for_each:
                - metadata:
                    operator: set
                    key: timestamp
                    value: ${!json_field:timestamp}
                - metadata:
                    operator: set
                    key: schema_id
                    value: ${!json_field:metadata.schema_id}
                - metadata:
                    operator: set
                    key: event_id
                    value: ${!json_field:event_id}
                - metadata:
                    operator: set
                    key: event_type
                    value: ${!json_field:event_type}

        - processors:
            - metadata:
                operator: set
                key: dest_topic
                value: "{{GCP_DEADLETTER_TOPIC}}"

output:
  broker:
    pattern: greedy
    copies: 25
    outputs:
      - broker:
          pattern: fan_out
          outputs:
            - gcp_pubsub: # DLQ
                project: "{{GCP_PROJECT}}"
                topic: "{{GCP_DEADLETTER_TOPIC}}"
              processors:
                - filter_parts:
                    metadata:
                      operator: equals
                      key: dest_topic
                      arg: "{{GCP_DEADLETTER_TOPIC}}"

            - gcp_pubsub: # Success
                project: "{{GCP_PROJECT}}"
                topic: "{{GCP_TOPIC}}"
              processors:
                - filter_parts:
                    metadata:
                      operator: equals
                      key: dest_topic
                      arg: "{{GCP_TOPIC}}"
```
