### ISSUE TITLE
Selective outputs for messages in a batch

### ISSUE THREAD

**Issue by inliquid** [Jeffail/benthos#411]
Say, I have a batch of 2 messages. I want to always output first part with `http_client`, second with `files`. How can I do that? From my experiments I found that `select_parts` processor will replace batch with selected part and so I can only process 1 part of a message batch with both outputs. For `broker` output it's not possible to direct 1st part to one output and 2nd to another... Any way to handle this?

**Comment by Jeffail** [comment]
Hey @inliquid,

You can place processors on a specific output in a broker which lets you do this:

```yaml
output:
  broker:
    pattern: fan_out
    outputs:
    - http_client:
        url: foo
      processors:
        - select_parts:
            parts: [0]
        
    - files:
        path: /bar.json
      processors:
        - select_parts:
            parts: [1]
```
