### ISSUE TITLE
Can't output from kinesis-balanced or kinesis

### ISSUE THREAD

**Issue by avdempsey** [Jeffail/benthos#412]
I have the following config and benthos 3.11.0:

`input:
  kinesis_balanced:
    stream: what-a-great-stream
    start_from_oldest: false
    dynamodb_table: table-for-benthos
    dynamodb_billing_mode: PAY_PER_REQUEST
    region: us-east-1
    credentials:
        profile: what-a-great-profile
output:
    file:
        path: outfile.txt
        delimiter: ""
`

Using the same AWS profile, on us-east-1, I'm able to put records on this stream, get records from it, and when I scan dynamodb `table-for-benthos` I see leases are being updated by benthos as long as it's running. The file, `outfile.txt` is getting created, and if I swap the input to stdin it works.

I'm not getting any errors, and I'm not getting any output from kinesis.

I'm so close to living the dream, I can taste it.

**Comment by Jeffail** [comment]
Hey @avdempsey,

Could be a range of things, would be good to collect some diagnostic info. Can you add the following to your config:

```yaml
logger:
  level: TRACE

metrics:
  type: stdout
```

Run it for a few seconds and then paste me the yummy logs.

**Comment by avdempsey** [comment]
No new data sire:
```{"@timestamp":"2020-03-19T19:27:46-07:00","@service":"benthos","level":"INFO","component":"benthos","message":"Launching a benthos instance, use CTRL+C to close."}
{"@timestamp":"2020-03-19T19:27:46-07:00","@service":"benthos","level":"INFO","component":"benthos","message":"Listening for HTTP requests at: http://0.0.0.0:4195"}
{"@timestamp":"2020-03-19T19:27:47-07:00","@service":"benthos","level":"INFO","component":"benthos.input","message":"Receiving Amazon Kinesis messages from stream: respondent-event-stream-dev"}
^C{"@timestamp":"2020-03-19T19:40:15-07:00","@service":"benthos","level":"INFO","component":"benthos","message":"Received SIGTERM, the service is closing."}
{"@timestamp":"2020-03-19T19:40:15-07:00","@service":"benthos","level":"DEBUG","component":"benthos.input","message":"Waiting for pending acks to resolve before shutting down."}
{"@timestamp":"2020-03-19T19:40:15-07:00","@service":"benthos","level":"DEBUG","component":"benthos.input","message":"Pending acks resolved."}
panic: close of closed channel

goroutine 330 [running]:
github.com/patrobinson/gokini.(*KinesisConsumer).Shutdown(0xc000230c00)
	/home/ash/go/pkg/mod/github.com/patrobinson/gokini@v0.0.7/consumer.go:249 +0x37
created by github.com/Jeffail/benthos/v3/lib/input/reader.(*KinesisBalanced).CloseAsync
	/home/ash/src/go/benthos/lib/input/reader/kinesis_balanced.go:207 +0x46
```
With config:

```
input:
  kinesis_balanced:
    stream: what-a-great-stream
    start_from_oldest: true
    dynamodb_table: table-for-benthos
    dynamodb_billing_mode: PAY_PER_REQUEST
    region: us-east-1
    credentials:
        profile: what-a-great-profile

output:
  file:
    path: outfile.txt
    delimiter: ""

logger:
  level: TRACE

metrics:
  type: stdout```

**Comment by Jeffail** [comment]
That panic definitely ain't right, I'll look at that separately. Can you try the same but with the standard `kinesis` input?

**Comment by avdempsey** [comment]
I got standard `kinesis` to work with:

```
input:
  kinesis:
    stream: what-a-great-stream
    client_id: benthos_consumer
#    dynamodb_table: table-for-benthos-2
    shard: shardId-000000000000
    start_from_oldest: false
#    commit_period: 1s
    region: us-east-1
    credentials:
        profile: what-a-great-profile
output:
  file:
    path: outfile.txt
    delimiter: ""

logger:
  level: TRACE

metrics:
  type: stdout
```

But I had to comment out dynamodb table stuff as seen above. I was getting this with dynamodb:
`` 
{"@timestamp":"2020-03-20T15:36:44-07:00","@service":"benthos","level":"ERROR","component":"benthos.input","message":"Failed to connect to kinesis: ResourceNotFoundException: Requested resource not found"}
```

So perhaps the issue with both pertains to dynamodb? This aws profile `what-a-great-profile` was able to create a new dynamodb table, and `kinesis-balanced` did look like it was getting leases from the dynamodb table I made.
