### ISSUE TITLE
Can't prevent `http_client` from resending error messages indefinitely

### ISSUE THREAD

**Issue by inliquid** [Jeffail/benthos#415]
Here is `http_client` config that I tried:

1. Using backoff limit:
```
      - http_client:
          # retry_period: 10s
          max_retry_backoff: 30s
          # retries: 3
          backoff_on:
            - 429
            - 500
          url: http://${MONGOD_ADDR:127.0.0.1:9000}/internal/v1/save-data/
          verb: POST
          headers:
            Content-Type: application/json
            X-Image-ID: ${!metadata:image_id}
          rate_limit: ""
          timeout: 5s
          max_in_flight: 1
          batching:
            count: 1
            byte_size: 0
            period: ""
        processors:
          - select_parts:
              parts: [0]
```

Logs after 1 message batch with error message part:
```
>benthos.exe -c config-addons.yaml
{"@timestamp":"2020-03-25T15:17:07+03:00","@service":"benthos","level":"INFO","component":"benthos.input","message":"Receiving HTTP messages at: http://:8000/api/v1/image-upload/"}
{"@timestamp":"2020-03-25T15:17:07+03:00","@service":"benthos","level":"INFO","component":"benthos","message":"Launching a benthos instance, use CTRL+C to close."} 
{"@timestamp":"2020-03-25T15:17:07+03:00","@service":"benthos","level":"INFO","component":"benthos.output.broker.outputs.0","message":"Sending messages via HTTP requests to: http://127.0.0.1:9000/internal/v1/save-data/"}
{"@timestamp":"2020-03-25T15:17:07+03:00","@service":"benthos","level":"INFO","component":"benthos.output.broker.outputs.1","message":"Writing message parts as files."}
{"@timestamp":"2020-03-25T15:17:07+03:00","@service":"benthos","level":"INFO","component":"benthos","message":"Listening for HTTP requests at: http://0.0.0.0:4195"}
{"@timestamp":"2020-03-25T15:17:15+03:00","@service":"benthos","level":"TRACE","component":"benthos.input","message":"Consumed 2 messages from POST to '/api/v1/image-upload/'."}
{"@timestamp":"2020-03-25T15:17:15+03:00","@service":"benthos","level":"TRACE","component":"benthos.output.broker.outputs.1","message":"Attempting to write 1 messages to 'files'."}
{"@timestamp":"2020-03-25T15:17:15+03:00","@service":"benthos","level":"TRACE","component":"benthos.output.broker.outputs.0","message":"Attempting to write 1 messages to 'http_client'."}
{"@timestamp":"2020-03-25T15:17:15+03:00","@service":"benthos","level":"TRACE","component":"benthos.output.broker.outputs.1","message":"Successfully wrote 1 messages to 'files'."}
{"@timestamp":"2020-03-25T15:17:22+03:00","@service":"benthos","level":"ERROR","component":"benthos.output.broker.outputs.0","message":"Failed to send message to http_client: HTTP request returned unexpected response code (500): 500 Internal Server Error"}
{"@timestamp":"2020-03-25T15:17:22+03:00","@service":"benthos","level":"ERROR","component":"benthos.output","message":"Failed to dispatch fan out message: HTTP request returned unexpected response code (500): 500 Internal Server Error"}
{"@timestamp":"2020-03-25T15:17:22+03:00","@service":"benthos","level":"TRACE","component":"benthos.output.broker.outputs.0","message":"Attempting to write 1 messages to 'http_client'."}
{"@timestamp":"2020-03-25T15:18:16+03:00","@service":"benthos","level":"ERROR","component":"benthos.output.broker.outputs.0","message":"Failed to send message to http_client: Post \"http://127.0.0.1:9000/internal/v1/save-data/\": EOF"}
{"@timestamp":"2020-03-25T15:18:16+03:00","@service":"benthos","level":"ERROR","component":"benthos.output","message":"Failed to dispatch fan out message: Post \"http://127.0.0.1:9000/internal/v1/save-data/\": EOF"}
{"@timestamp":"2020-03-25T15:18:16+03:00","@service":"benthos","level":"TRACE","component":"benthos.output.broker.outputs.0","message":"Attempting to write 1 messages to 'http_client'."}
{"@timestamp":"2020-03-25T15:19:46+03:00","@service":"benthos","level":"ERROR","component":"benthos.output.broker.outputs.0","message":"Failed to send message to http_client: HTTP request returned unexpected response code (500): 500 Internal Server Error"}
{"@timestamp":"2020-03-25T15:19:46+03:00","@service":"benthos","level":"ERROR","component":"benthos.output","message":"Failed to dispatch fan out message: HTTP request returned unexpected response code (500): 500 Internal Server Error"}
{"@timestamp":"2020-03-25T15:19:46+03:00","@service":"benthos","level":"TRACE","component":"benthos.output.broker.outputs.0","message":"Attempting to write 1 messages to 'http_client'."}
{"@timestamp":"2020-03-25T15:21:16+03:00","@service":"benthos","level":"ERROR","component":"benthos.output.broker.outputs.0","message":"Failed to send message to http_client: HTTP request returned unexpected response code (500): 500 Internal Server Error"}
{"@timestamp":"2020-03-25T15:21:17+03:00","@service":"benthos","level":"ERROR","component":"benthos.output","message":"Failed to dispatch fan out message: HTTP request returned unexpected response code (500): 500 Internal Server Error"}
{"@timestamp":"2020-03-25T15:21:17+03:00","@service":"benthos","level":"TRACE","component":"benthos.output.broker.outputs.0","message":"Attempting to write 1 messages to 'http_client'."}
{"@timestamp":"2020-03-25T15:21:29+03:00","@service":"benthos","level":"INFO","component":"benthos","message":"Received SIGTERM, the service is closing."}
```

I found it much easier to see what's happening with logs of external service which reply with 500 error code on that incoming error message:

```
{"level":"info","message":"Server listening on :9000","time":"2020/03/25 15:17:05.560850"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:17:15.708913"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:17:16.710896"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:17:18.712557"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:17:22.712630"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:17:22.713568"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:17:30.715211"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:17:46.717027"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:18:16.718501"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:19:16.720339"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:19:46.722957"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:19:46.724959"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:20:16.726928"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:21:16.729152"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:21:17.731234"}
{"level":"info","message":"Terminating signal caught","time":"2020/03/25 15:21:31.977791","signal":"interrupt"}
{"level":"info","message":"Server stopping gracefully","time":"2020/03/25 15:21:31.978779"}
```

As you can see intervals are increasing, however there are sometimes 2 messages at near same time:
```
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:17:22.712630"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:17:22.713568"}
```
and `benthos` actually continue to send those messages indefinitely. 

2. Using retries limit:
```
      - http_client:
          retry_period: 10s
          # max_retry_backoff: 30s
          retries: 3
          # backoff_on:
          #   - 429
          #   - 500
          url: http://${MONGOD_ADDR:127.0.0.1:9000}/internal/v1/save-data/
          verb: POST
          headers:
            Content-Type: application/json
            X-Image-ID: ${!metadata:image_id}
          rate_limit: ""
          timeout: 5s
          max_in_flight: 1
          batching:
            count: 1
            byte_size: 0
            period: ""
        processors:
          - select_parts:
              parts: [0]
      - files:
          path: ${OUT_DIR:out}/${!metadata:image_id}.jpg     
        processors:
          - select_parts:
              parts: [1]
```

`benthos` logs are pretty much similar, so I show external service's logs to have a more clear view on what's happening:
```
{"level":"info","message":"Server listening on :9000","time":"2020/03/25 15:50:06.557723"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:50:12.543249"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:50:22.544079"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:50:32.544728"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:50:42.545726"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:50:42.546724"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:50:52.548616"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:51:02.548800"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:51:12.549118"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:51:12.550049"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:51:22.558350"}
{"level":"info","message":"Terminating signal caught","time":"2020/03/25 15:51:27.051154","signal":"interrupt"}
{"level":"info","message":"Server stopping gracefully","time":"2020/03/25 15:51:27.051154"}
```

You can see that retry interval increased to 10s, however there are still "doubles":
```
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:50:42.545726"}
{"level":"error","message":"Error decoding request body: invalid character 'ÿ' looking for beginning of value","time":"2020/03/25 15:50:42.546724"}
```

And, same again, it does not stop at 3rd retry, and continue to resend it indefinitely. Taking in account #414 just 1 single error message will block whole system (in addition to spamming the logs and eating memory).
