### ISSUE TITLE
Is it possible to propagate error responses with `http_client`

### ISSUE THREAD

**Issue by inliquid** [Jeffail/benthos#417]
There is a parameter `propagate_response`, which according to docs can make `http_client` propagate responses from arbitrary server back to input: https://www.benthos.dev/docs/components/outputs/http_client#propagate_response

However that seems to not work when response is error (and message is being dropped to stop infinite retries either with `drop` output and limit on `retries` or with `drop_on` statement). However most of the time errors is exactly what we would like to see as the sync response, because good tries are good anyways - there is `200 OK` and nothing else needed. So the question is whether it's possible or not, and if there is any workaround?

**Comment by Jeffail** [comment]
Hey @inliquid, not currently but I've thought about this in the past and it's definitely possible to implement. An alternative would be to use a `drop` output and use an `http` processor to make the request, that would let you capture any errors with processor error handling: https://www.benthos.dev/docs/configuration/error_handling

**Comment by inliquid** [comment]
Thank you @Jeffail, unfortunately I can't use `http` processor because there is a batch where one part should always go to `files` output, and another part is to be processed by external server. As I see from the documentation, `http` does not allow to just select a part, and if I use `select_parts` processor, this will affect whole batch and will not allow to output unselected parts as the file.

**Comment by Jeffail** [comment]
Hey @inliquid, you can do something like this:

```yaml
  broker:
    pattern: fan_out
    outputs:
    - files:
        path: TODO
      processors:
      - select_parts:
          parts: [0]

    - drop: {}
      processors:
      - select_parts:
          parts: [1]
      - http:
          request:
            url: TODO
            verb: POST
      - catch:
        # If an error occurred change the message contents to the error message and send it back to the input
        - text:
            operator: set
            value: "ERROR: ${!error}"
        - sync_response: {}
```

**Comment by inliquid** [comment]
With this setup it still returns `200 OK` as the response to client sending to input. Is there any way to return `500` response? Second problem is that error from arbitrary server is lost, we just receive a very generic `HTTP request returned unexpected response code (500): 500 Internal Server Error`. So basically it just should propagate answers back to the client, both good responses and errors.

**Comment by Jeffail** [comment]
Ah I see, what you'll need for that is some sort of `response_code: ${!metadata:code}` field, or something similar. Unfortunately, there's no support for that right now, synchronous responses are very limited.

**Comment by Jeffail** [comment]
Closing as this has been added.

**Comment by brivadeneira** [comment]
Hello there!

How I should implement this?
I mean, return the http_client response to the input? (in my case an http_server)

thanks

**Comment by Jeffail** [comment]
Hey @brivadeneira, you need to set the field https://www.benthos.dev/docs/components/outputs/http_client#propagate_response to `true`

**Comment by brivadeneira** [comment]
Thanks for the answer!

I have already setted propagate_response field,
but I receive a time_out from the input:

```yaml
input:
  label: "fan_out_webhook_sendgrid"
  http_server:
    address: ""
    path: /webhook/sendgrid
    allowed_verbs:
      - POST
    timeout: 5s
    sync_response:
      headers:
        Content-Type: application/json


pipeline:
  processors:
    - type: sync_response
    - bloblang: | 
        root.this = this

output:
  switch:
    retry_until_success: false
    cases:
      - check: 'meta("key") == "${KEY}"'
        output:
          try:
            # Callback clevertap
            - http_client:
                url: https://cb.wzrkt.com/sendgrid?account=${ACCOUNT}
                verb: POST
                propagate_response: true
                retries: 3
                max_retry_backoff: 10s
                retry_period: 1s
                copy_response_headers: true
                
                headers:
                  Content-Type: application/json
                  Accept-Encoding: gzip
              label: "post_sendgrid_clevertap_event"
              processors:
                - try:
                    - bloblang: | 
                        root = content()
                - catch:
                  - bloblang: | 
                        root.is_error = errored()
                        root.error = error()
                  - log:
                        level: ERROR
                        message: "Message with error ${! error() } "
                - log:
                    level: INFO
                    message: "Message: ${! content() } "

            # Callback overol
            - http_client:
                url: https://www.properati.com.ar/api/v3/sendgrid/event
                verb: POST
                retries: 3
                max_retry_backoff: 10s
                retry_period: 1s
                copy_response_headers: true
                headers:
                  Content-Type: application/json
                  Accept-Encoding: gzip
              label: "post_sendgrid_overol_event"
              processors:
                - try:
                    - bloblang: root = content()
                - catch:
                  - bloblang: | 
                        root.is_error = errored()
                        root.error = error()
                  - log:
                        level: ERROR
                        message: "Message with error ${! error() } "
                - log:
                    level: INFO
                    message: "Message: ${! content() } "

      - output:
          reject: "Message failed due to: Wrong key"
          processors:
          - log:
              level: ERROR
              message: "Wrong key"

logger:
  level: DEBUG
  format: json
  add_timestamp: true
  static_fields:
    '@service': benthos
    
metrics:
  http_server:
    prefix: benthos
    path_mapping: ""
tracer:
  none: {}
shutdown_timeout: 20s

```

thanks!
