### ISSUE TITLE
`http_client` output does not respect `copy_response_headers` parameter

### ISSUE THREAD

**Issue by inliquid** [Jeffail/benthos#421]
So for instance, if some server replies with `Content-Type: application/json`, there will be `Content-Type: application/octet-stream` in propagated response.

**Comment by Jeffail** [comment]
Hey @inliquid, there's a field `copy_response_headers` which might be what you're after. It sends the response back with the same headers as the payload, which should include `content-type`.

**Comment by Jeffail** [comment]
Just to clarfiy, you need to set https://www.benthos.dev/docs/components/inputs/http_server#sync_responseheaders in order to specify the headers in the response, and `copy_response_headers` on the client copies the response header to the payload.

**Comment by inliquid** [comment]
1. `copy_response_headers` for `http_client` doesn't work, just nothing changes, I still see `application/octet-stream`
2. `sync_response.headers` for `http_server` server sets content type, BUT it does not copy anything, it just set what you wrote here.

**Comment by Jeffail** [comment]
Hey @inliquid, did a bit of investigation and it looks like the `http_client` output is failing to respect `copy_response_headers`. A work around for now is to use an `http` processor:

```yaml
input:
  http_server:
    path: /post
    sync_response:
      headers:
        Content-Type: ${!metadata:content-type}
pipeline:
  processors:
    - http:
        request:
          copy_response_headers: true
          url: http://localhost:4196/post
          verb: POST
    - type: sync_response
output:
  type: drop
```

I'll try and get this fixed for the `http_client` output for the next release.
