### ISSUE TITLE
[processor] duplicate parts

### ISSUE THREAD

**Issue by eightnoteight** [Jeffail/benthos#430]
in gist, we have a usecase where our input comes `gateway-kafka-topic` and want to run 2 separate transformations on the input and send it to 2 different outputs `kafka-topic-output1` and `kafka-topic-ouptput2`

I've explore the inproc output/input and using a broker output I can technically duplicate the payloads that I need by adding tagging and in the next step removing the tagging, but seemed like a bit complicated loop in my big transformation yaml config. and also didn't want to have these loops with more cases added.

any tips around the same? do you think this is achievable using a processor?

**Comment by Jeffail** [comment]
Hey @eightnoteight, from the sounds of it you can just use an output broker with output specific processors:

```yaml
output:
  broker:
    pattern: fan_out
    outputs:
    - kafka:
        topic: kafka-topic-output1
        ...
      processors:
      - thing

    - kafka:
        topic: kafka-topic-output2
        ...
      processors:
      - thing
```

Alternatively, you can duplicate the message, process them separately using the `parts` field of your processors, then use interpolation on the output topic:

```yaml
pipeline:
  processors:
  - select_parts:
      parts: [0,0]
      
  - jmespath:
      parts: [0]  
      query: ...
  - metadata:
      parts: [0]
      operator: set
      key: kafka_topic
      value: kafka-topic-output1

  - jmespath:
      parts: [1]  
      query: ...
  - metadata:
      parts: [1]
      operator: set
      key: kafka_topic
      value: kafka-topic-output2
      
output:
  kafka:
    addresses: [ localhost:9092 ]
    topic: '${!meta("kafka_topic")'
```
