### ISSUE TITLE
Setting HTTP_ADDRESS

### ISSUE THREAD

**Issue by mfamador** [Jeffail/benthos#438]
Hi!
I'm trying to set `HTTP_ADDRESS` through env vars and I'm getting some unexpected results, probably my mistake.

This way it works just fine:
```
❯ docker run --rm -e "HTTP_ADDRESS=0.0.0.0:4196" jeffail/benthos
```
```
... "message":"Listening for HTTP requests at: http://0.0.0.0:4196"
```

But setting a configuration - nor overriding `HTTP_ADDRESS` - it will serve at the default port 4195:
```
❯ docker run --rm -v ~/pipeline.yaml:/benthos.yaml -e "HTTP_ADDRESS=0.0.0.0:4196" jeffail/benthos
```
```
... "message":"Listening for HTTP requests at: http://0.0.0.0:4195"
```

Running the binary locally, I cannot make it run at 4196 not even without config:
```
❯ HTTP_ADDRESS=0.0.0.0:4196 benthos
```
```
... "message":"Listening for HTTP requests at: http://0.0.0.0:4195"
```

Can you please see if I'm doing some obvious mistake?
Thank you so much!
Cheers

**Comment by Jeffail** [comment]
Hey @mfamador! Setting fields with env vars requires interpolation expressions in a config:

```yaml
http:
  address: ${HTTP_ADDRESS:0.0.0.0:4195}
  debug_endpoints: ${HTTP_DEBUG_ENDPOINTS:false}
  read_timeout: ${HTTP_READ_TIMEOUT:5s}
  root_path: ${HTTP_ROOT_PATH:/benthos}
```

The docker image is built with a default config containing env vars for each field: https://github.com/Jeffail/benthos/blob/master/config/env/default.yaml, but when you're running locally or deploying your own config you need to add the interpolation expression in order to use env vars.
