### ISSUE TITLE
Bloblang interpolation function doesn't compile in json processor

### ISSUE THREAD

**Issue by zlozano** [Jeffail/benthos#442]
version: v3.14.0
processor:

```
pipeline:
  threads: 1
  processors:
    - json:
        operator: set
        path: topic
        value: ${!meta("kafka_topic")}
```

error: `"Failed to create stream (ingress): failed to create processor 'json': failed to parse value expression: failed to parse expression: char 9: required one of: [boolean number quoted-string match function null array object variable-path field-path]"`

reference doc: https://www.benthos.dev/docs/components/processors/json#value

I am trying to add the Kafka topic to my payload body. On startup, I receive the above error message. I have tried wrapping the entire `value` in quotes, with no success. I also tried removing the quotes around `kafka_topic`, and that compiled, but resulted in an empty field, e.g. `{"topic": ""}`.

**Comment by Jeffail** [comment]
Hey @zlozano, looks like a bug, I'll have it fixed by the next release. In the meantime the old interpolation syntax should still work:

```yaml
pipeline:
  threads: 1
  processors:
    - json:
        operator: set
        path: topic
        value: ${!metadata:kafka_topic}
```

Or, if you're feeling adventurous, use the new bloblang processor:

```yaml
pipeline:
  threads: 1
  processors:
    - bloblang: |
        root = this
        topic = meta("kafka_topic")
```
