### ISSUE TITLE
custom function for http_client header

### ISSUE THREAD

**Issue by rzkmak** [Jeffail/benthos#446]
Hi, I just do some poc for benthos and I find that it's a great tool!

I wanna ask about how to extends http_client output to add more header with a custom function
for example hmac-sha256 authentication

I couldn't find any of information in the docs or closed issue, apologies if I missed about this in docs

Thanks~

**Comment by Jeffail** [comment]
Hey @rzkmak, there's an example repo that shows how to add custom components here: https://github.com/benthosdev/benthos-plugin-example, and the code for creating HTTP requests from messages is here: https://github.com/Jeffail/benthos/blob/master/lib/util/http/client/type.go

However, in the case of hmac authentication you might get away without needing to write a plugin at all. Depending on your use case you could generate your hash header with the [bloblang processor](https://www.benthos.dev/docs/components/processors/bloblang) and reference it as a configured header:

```yaml
pipeline:
  processors:
  - bloblang: 'meta auth_token = "POST+%v".format(meta("target_path")).hash("hmac-sha256", "${PASSWORD}").encode("base64")'

output:
  http_client:
    url: http://somewhere/${!meta("target_path")}
    verb: POST
    headers:
      Authentication: 'hmac ${USERNAME}:${!meta("auth_token")}'
```

If your token generation is more complicated then you could still write a processor plugin for creating the hashes and reference it as metadata, that's probably easier overall than writing a custom output.
