### ISSUE TITLE
Help wanted: How do I properly batch my messages after routing to appropriate output

### ISSUE THREAD

**Issue by klintan** [Jeffail/benthos#451]
Sorry to ask for help here, was looking at stack, but there were no previous benthos questions there (perhaps I'll ask this one there as well? ). I've been digging in to the documentation and all the guides, but I think I'm missing something because I can't seem to get it to work: 

I want to route messages based on a bloblang condition, they are first an arbitrary batch size, I split them up into individual messages, and then use a switch to route to two different folders on s3. I want the files to be written in batches for each type of message:

```
# processors ends with this..
    - type: split
      split:
        size: 1

output:
  switch:
    outputs:
      - condition:
          bloblang: this.exists("from")
        fallthrough: false
        output:
          broker:
            pattern: fan_out
            batching:
              count: 100
              period: 1000ms
              processors:
                - type: archive
                  archive:
                    format: lines
            outputs:
              - type: s3
                s3:
                  bucket: my-bucket
                  path: test/output/edges/${!count}-${!timestamp_unix_nano}.jsonl
                  timeout: 60s
                processors:
                  - type: log
                    log:
                      level: INFO
                      message: "lambda batch for edges done (${!count}*${LAMBDA_BATCH_SIZE}): ${S3_OUTPUT_PREFIX}/${!metadata:s3_key}"

      - output:
          broker:
            pattern: fan_out
            batching:
              count: 100
              period: 1000ms
              processors:
                - type: archive
                  archive:
                    format: lines
            outputs:
              - type: s3
                s3:
                  bucket: my-bucket
                  path: test/output/vertices/${!count}-${!timestamp_unix_nano}.jsonl
                  timeout: 60s
                processors:
                  - type: log
                    log:
                      level: INFO
                      message: "lambda batch vertices done (${!count}*${LAMBDA_BATCH_SIZE}): ${S3_OUTPUT_PREFIX}/${!metadata:s3_key}"
```

Since s3 output does not support batching I used a broker for each to batch each route up to 100 messages and wait up to 1 second.

I think i'm probably approaching the problem wrong. I had an idea of using `for_each` to do the routing, but I would still face the same issue that I need to batch each "route" by itself using archive lines.

edit: just to clarify, the routing works as expected, but unfortunately it is only one json-document/line per file.

**Comment by Jeffail** [comment]
Hey @klintan, the switch output doesn't work well with batching in child outputs, I need to clarify that in the documentation. The simplest approach would be to batch once and send a filtered version of that batch to your output destinations:

```yaml
output:
  broker:
    pattern: fan_out
    batching:
      count: 100
      period: 1s
    outputs:
      - s3:
          bucket: my-bucket
          path: test/output/edges/${!count}-${!timestamp_unix_nano}.jsonl
          timeout: 60s
        processors:
          - bloblang: root = if !this.exists("from") { deleted() }
          - archive:
              format: lines
      - s3:
          bucket: my-bucket
          path: test/output/vertices/${!count}-${!timestamp_unix_nano}.jsonl
          timeout: 60s
        processors:
          - bloblang: root = if this.exists("from") { deleted() }
          - archive:
              format: lines
```

Sorry about the confusion. Batching is still pretty awkward within Benthos as there's a lot of different strategies on offer and they don't always work together.

Another thing to note is that if your data is coming from kafka or kinesis then due to ordering guarantees batching at the output level won't work, so you'd need to preserve your existing batch and use the [`group_by`](https://www.benthos.dev/docs/components/processors/group_by) processor to break it into the batches you want to route separately.
