### ISSUE TITLE
Question - Http Processor

### ISSUE THREAD

**Issue by mallikvala** [Jeffail/benthos#460]
Documentation for `http` processor type mentions `Performs an HTTP request using a message batch as the request body, and replaces the original message parts with the body of the response.`

I want to retain the original message `part` contents after the `http` processor to be able to use it in an `output`. For the `output` i need both the initial `part` and the response from the `http` processor.  Is there a way to do it?

Thank you.

**Comment by Jeffail** [comment]
Hey @mallikvala, yeah there's two ways you can do this. If you're processing JSON documents then you can perform the HTTP request and insert the result into the original payload with the [`process_map`](https://www.benthos.dev/docs/components/processors/process_map/) processor: 

```yaml
pipeline:
  processors:
    - process_map:
        processors:
          - http: {} # TODO
        postmap:
          http_result: .
```

The other way is to create a clone of the message (creating a batch of two identical messages), only apply the http processor to the second message and then use split to break the batch into two individual messages:

```yaml
pipeline:
  processors:
    - select_parts:
        parts: [0,0]
    - process_map:
        parts: [1]
        processors:
          - http: {} # TODO
    - split: {}
```
