### ISSUE TITLE
Improve batched output DLQ routing

### ISSUE THREAD

**Issue by bojtirmw** [Jeffail/benthos#461]
Hey @Jeffail!

First of all, thanks for Benthos! It's a really great tool, and I find it amazing how you maintain it! It's awesome to see how frequently there is a new release with some really good features and quick fixes! (and I can say, `bloblang` is a huge hit ;) )

I have a couple of distinct questions, and I thought I would just list them here in only one thread, I hope it's okay. Eventually we can raise separate ones if needed.

So my questions are:

* As `bloblang` section of the docs says about `timestamp_unix` function: "Resolves to the current unix timestamp in seconds. You can add fractional precision up to the nanosecond by specifying the precision as an argument, e.g. `timestamp_unix(3)` for millisecond precision." I have tried using `timestamp_unix(3)` expecting millis precision but it still returns seconds, or am I missing something? https://lab.benthos.dev/l/FX2Kd5LccHP 

* dynamo cache processor: it produces warning log ("key not found:") if there is no value found for a key when using `get`. It's not a big deal, just wondering if there's a possibility to eliminate that log entry, since in my pipeline it is okay not having a value for a key when calling get, and I handle the error properly. This log entry creates a bit of noise in the logs which I can eliminate by filtering out in our log visualisation but that would be great if there would be no such log entry at all. Or is there any other way to check if the dynamo cache has a value under a specific key?

* try output & batches: what I am trying to achieve here is: if during my pipeline there was no error, I want to save messages to a dynamo table, preferably in batches. If there was no error in the pipeline, I want the messages to be routed to a DLQ. At this stage I want to drop messages if saving to dynamo fails (later on I would like to use the DLQ instead of dropping the message, but I have run into this issue which I would like to solve first). 
Normally I would do the batching at the level of dynamo output but I have read that it is worth creating batches before the broker or switch output (https://github.com/Jeffail/benthos/issues/451).
So I ended up with an output configuration like this:

```
output:
  broker:
    pattern: fan_out
    batching:
      count: ${OUTPUT_BATCH_COUNT:25}
      byte_size: ${OUTPUT_BATCH_BYTE_SIZE:16000000} # 16mb by default
      period: ${OUTPUT_BATCH_PERIOD:1s}
    outputs:
      - resource: dlq
      - resource: dynamo

resources:
  outputs:
    dlq:
      sqs:
        url: ${DLQ_URL}
      processors:
        - bloblang: root = if error().length() == 0 { deleted() }
        - log:
            level: WARN
            fields:
            message: 'Failed to process message: error: ${!error()}'
        - bloblang: root = meta("originalMessage")

    dynamo:
      try:
        - dynamodb:
            table: ${OUTPUT_TABLE_NAME}
            max_in_flight: ${OUTPUT_MAX_IN_FLIGHT:100}
            json_map_columns:
              "": .
        - type: drop
          processors:
            - for_each:
              - log:
                  level: WARN
                  fields:
                    event_type: ${!meta("event_type")}
                    payload: ${!content}
                    originalPayload: ${!meta("originalMessage")}
                  message: 'Failed to save message: error: ${!error()}'
      processors:
        - bloblang: root = if error().length() > 0 { deleted() }
```

What I saw from the logs, that there are intermittent dynamodb errors like "Failed to send message to dynamodb: failed to set 1 items". What was strange that after this log entry I found my warning log messages of "Failed to save message" multiple times from which I suspect the whole batch was passed to the `drop` output by the `try` output. I also noticed that neither of those messages have `error()` set.
So my questions regarding this are:
* Am I right suspecting that `try` output passes the whole batch down to `drop`?
* Can I achieve that only the failed message parts are passed to `drop` and `error()` is filled properly?
* Is the way I do the batching right? Do you have anything to add/advise or is this the right way to do it atm? (also asking because I just saw there is a new release of `3.19.0` containing some `switch` improvements).

Sorry for the dozen questions and many thanks in advance!

**Comment by Jeffail** [comment]
> First of all, thanks for Benthos! It's a really great tool, and I find it amazing how you maintain it! It's awesome to see how frequently there is a new release with some really good features and quick fixes! (and I can say, `bloblang` is a huge hit ;) )

❤️ 

>     * As `bloblang` section of the docs says about `timestamp_unix` function: "Resolves to the current unix timestamp in seconds. You can add fractional precision up to the nanosecond by specifying the precision as an argument, e.g. `timestamp_unix(3)` for millisecond precision." I have tried using `timestamp_unix(3)` expecting millis precision but it still returns seconds, or am I missing something? https://lab.benthos.dev/l/FX2Kd5LccHP

This looks like a bug, should be a quick fix so I'll try and get it in the next release, opened https://github.com/Jeffail/benthos/issues/463 to track it.

>     * dynamo cache processor: it produces warning log ("key not found:") if there is no value found for a key when using `get`. It's not a big deal, just wondering if there's a possibility to eliminate that log entry, since in my pipeline it is okay not having a value for a key when calling get, and I handle the error properly. This log entry creates a bit of noise in the logs which I can eliminate by filtering out in our log visualisation but that would be great if there would be no such log entry at all. Or is there any other way to check if the dynamo cache has a value under a specific key?

Agreed that's annoying, we shouldn't really be logging that from the cache client so I can get that removed.

I need to pop out so I'll have to tackle the batching question later.

**Comment by Jeffail** [comment]
> Am I right suspecting that try output passes the whole batch down to drop?

Yeah unfortunately a limitation of Benthos is that when a broker type receives a batch it attempts and acknowledges them as a whole. Therefore when one payload fails they all do.

> Can I achieve that only the failed message parts are passed to drop and error() is filled properly?

The `error()` of a message is currently only populated during processor errors, but I can look into expanding it so that the `try` broker also populates it.

As for breaking the messages down there is a pattern for this where you try into a new try that breaks the batch back down with `split`, that allows you to reattempt each payload individually. The cons of this approach are that payloads which sent successfully in the first batched attempt will be resent and it also slows down your pipeline by sending messages solo, if the errors are common and therefore in a warm path this might be a problem.

I've actually used a pattern similar to this with Kafka in the past so I can help out with the configuration if you want to try it out, we can then also look into ways of baking the pattern into something easier to configure.

> Is the way I do the batching right? Do you have anything to add/advise or is this the right way to do it atm? (also asking because I just saw there is a new release of 3.19.0 containing some switch improvements).

This looks fine, it's exactly how I'd recommend doing it.

**Comment by bojtirmw** [comment]
Hey,

many thanks for your help!

So, do I get it right that since `error()` is currently only populated during processor errors, right now I cannot really tell which message parts were failed? Because if we use `bloblang` processor to filter for failed messages we would normally use `errors().length() > 0` condition.

Assuming we can filter which messages are failed in a bacth and if I wanted to send those failed message parts into DLQ I would only need to change `type: drop` to `resource: dlq` in my `dynamo` output resource above (because the `dlq` output already does the filtering I need). Am I right? So modifying like this:

```
resources:
  outputs:
    dlq:
      sqs:
        url: ${DLQ_URL}
      processors:
        - bloblang: root = if error().length() == 0 { deleted() }
        - log:
            level: WARN
            fields:
            message: 'Failed to process message: error: ${!error()}'
        - bloblang: root = meta("originalMessage")

    dynamo:
      try:
        - dynamodb:
            table: ${OUTPUT_TABLE_NAME}
            max_in_flight: ${OUTPUT_MAX_IN_FLIGHT:100}
            json_map_columns:
              "": .
        - resource: dlq ## <= changed from type: drop
          processors:
            - for_each:
              - log:
                  level: WARN
                  fields:
                    event_type: ${!meta("event_type")}
                    payload: ${!content}
                    originalPayload: ${!meta("originalMessage")}
                  message: 'Failed to save message: error: ${!error()}'
      processors:
        - bloblang: root = if error().length() > 0 { deleted() }
```

Obviously in this case my error and warn log messages should also be refined.

Many thanks,
Robert

**Comment by Jeffail** [comment]
Been thinking through this over the weekend and I'm pretty sure I can implement automatic `try` into batching without you needing to configure around it, so with the following:

```yaml
output:
  try:
  - foo:
      batching:
        count: 100
  - bar: {}
```

If 93 out of 100 messages in the batch succeed only 7 messages would be routed to the `bar` output. There will be some edge cases where it would retry the whole batch depending on the output type (sometimes it's simply not possible to know which messages in particular failed) but dynamo should be possible.

I'll try and take a first attempt at this next weekend.

**Comment by bojtirmw** [comment]
Sounds awesome! Thanks!

**Comment by Jeffail** [comment]
I took a look at this today and it's a little more awkward to identify which dynamodb items weren't uploaded than I originally thought. You get a list of the remaining items but no identifier, and no indexes relating them to the original batch, so I'll need to play around with some sort of manual lookup to get this working.

I'm going to modify this issue into a feature request and will keep you posted. I think this is an important feature so it's high on my list of priorities.

**Comment by Jeffail** [comment]
Took longer than expected but I managed to get this in, it's general so all outputs are going to be able to follow the same rules. I'm planning to put a release out this evening which will allow you to do this:

```yaml
output:
  try:
  - dynamodb:
      table: foo
      string_columns:
        id: ${!json("id")}
        content: ${!content()}
      batching:
        count: 10
        period: 1s
  - file:
      path: /usr/local/benthos/failed_stuff.jsonl
```
