### ISSUE TITLE
Cache expects JSON data

### ISSUE THREAD

**Issue by patrobinson** [Jeffail/benthos#462]
I am using the cache processor and have a pipeline following [the example](https://www.benthos.dev/docs/components/processors/cache) like this:

```yaml
input:
  type: http_server
  http_server:
    path: /post
    timeout: 5s
resources:
  caches:
    assume_role_cache:
      dynamodb:
        table: "assume_role_cache"
        hash_key: "principal_id"
        data_key: "arn"
        endpoint: http://dynamodb-local:8000
        region: us-east-1
pipeline:
  threads: 1
  processors:
    - cache:
         cache: assume_role_cache
         operator: set
         key: '${!json_field:principal_id}'
         value: ${!json_field:arn}
    - process_map:
         processors:
           - cache:
                cache: assume_role_cache
                operator: get
                key: ${!json_field:userIdentity.principalId}
          postmap:
            tmp.principal: .
```

I can see the values populated in Dynamo successfully but when it attempts to hydrate from the cache I get an error:

```
{"@timestamp":"2020-06-30T05:53:01Z","@service":"benthos","level":"DEBUG","component":"benthos.pipeline.processor.1.5.0","message":"Failed to parse response part '0': invalid character 'a' looking for beginning of value. Failed part: 'arn:aws:iam::123456789012:user/Bob'"}
```

There seems to be an expectation that the data stored in Dynamo is a JSON blob, but this isn't documented anywhere.
Once I make the cache store a JSON blob it works.

**Comment by Jeffail** [comment]
Hey @patrobinson, the problem is with the postmap `tmp.principal: .`, in order to insert the result of the `process_map` processors Benthos requires the result itself to be valid JSON (an object, array, number, boolean or string). Since your goal is to set `tmp.principal` to a string result you just need to quote the result so that it's a valid json string:

```yaml
pipeline:
  threads: 1
  processors:
    - cache:
         cache: assume_role_cache
         operator: set
         key: '${!json_field:principal_id}'
         value: ${!json_field:arn}
    - process_map:
         processors:
           - cache:
                cache: assume_role_cache
                operator: get
                key: ${!json_field:userIdentity.principalId}
           - bloblang: 'root = content().quote()'
          postmap:
            tmp.principal: .
```
