### ISSUE TITLE
Allow custom status code responses with `http_server` sync responses

### ISSUE THREAD

**Issue by dz-at-tc** [Jeffail/benthos#465]
From the [json_schema](https://www.benthos.dev/docs/components/processors/json_schema) docs, I see how we can log errors and call deleted() to prevent bad messages from reaching the output stream.

But if our input is an [http_server](https://www.benthos.dev/docs/components/inputs/http_server), is it possible to also return a 400 Bad Request http response code to the caller?  And perhaps the response body could include the error details as well?

For context, I'm considering using benthos as something of a simple (as in write only) rest api in front of RabbitMQ.  Valid json documents would be published as output, but ideally I would like to immediately notify callers about invalid http requests.

I should also note that I'm brand new to benthos, but wanted to thank you for sharing the good fruit from all your hard work on the Boring Tasks front!  :-)

**Comment by Jeffail** [comment]
Hey @dz-at-tc, unfortunately setting a custom status code isn't currently possible. Your options right now are to set a header, and the payload can be whatever format you want. I'll update this issue to add custom status codes to sync responses as I believe it'll be possible.

**Comment by Jeffail** [comment]
Forgot to close this but it was added to the latest release: https://github.com/Jeffail/benthos/blob/master/CHANGELOG.md#3210---2020-07-12

**Comment by dz-at-tc** [comment]
Hi @Jeffail , first up, thanks so much for adding this new enhancement sir!

I've been trying sort out how to put this into practice for my original use case (ie, to conditionally return 400 / bad request for invalid json), but alas I can't seem to get the syntax right...  I'm hoping it's just my inexperience with the config file rules.

Here is what I have so far:

```
input:
    type: http_server
    http_server:
        path: /post
        sync_response:
            headers:
                Content-Type: application/octet-stream
            status: "200"

pipeline:
    processors:
        - bloblang: meta key = "good_queue"
        - json_schema:
            schema_path: "file:///path/to/schema.json"
        - catch:
            - log:
                level: ERROR
                message: "json schema validation failed: ${! error() }"
            - bloblang: meta key = "invalid_queue"
            # TODO not sure how to change status code to 400 / bad request ?!
            #- sync_response:
            #    status: 400  # path 'pipeline.processors[2].catch[2].sync_response': Key 'status' found but is ignored

output:
    broker:
        pattern: fan_out
        outputs:
            - type: stdout
            - type: sync_response
            - type: amqp_0_9
              amqp_0_9:
                url: amqp://guest:guest@localhost:5672/
                exchange: amq.direct
                key: ${! meta("key") }
                max_in_flight: 1
                persistent: true
```

My use of the meta key field seems to be working nicely to conditionally publish to the good or invalid queue, depending on whether json schema validation passes or fails.

But alas, as shown in the comments above, benthos does not seem to recognize the new status field in the catch error handling context (and hence refuses to start).  This seems like the logical place to update the status, mais non?!  

I welcome your thoughts regarding what I may be doing wrong here, thanks!

**Comment by Jeffail** [comment]
Hey @dz-at-tc, you set the status code using interpolation functions that have access to the response message, so in your case you likely want something like this:

```yaml
input:
    type: http_server
    http_server:
        path: /post
        sync_response:
            headers:
                Content-Type: application/octet-stream
            status: '${! meta("status_code") }'

pipeline:
    processors:
        - bloblang: |
            meta key = "good_queue"
            meta status_code = "200"
        - json_schema:
            schema_path: "file:///path/to/schema.json"
        - catch:
            - log:
                level: ERROR
                message: "json schema validation failed: ${! error() }"
            - bloblang: |
                meta key = "invalid_queue"
                meta status_code = "400"

output:
    broker:
        pattern: fan_out
        outputs:
            - type: stdout
            - type: sync_response
            - type: amqp_0_9
              amqp_0_9:
                url: amqp://guest:guest@localhost:5672/
                exchange: amq.direct
                key: ${! meta("key") }
                max_in_flight: 1
                persistent: true
```
