### ISSUE TITLE
TLS config support for output to Elasticsearch

### ISSUE THREAD

**Issue by awangc** [Jeffail/benthos#472]
When writing to Elasticsearch, it is desirable to be able to pass on alternate CA certificates, or choose to ignore verifying the certificate. Proposal is to add the TLS config block to the Elasticsearch writer output, so a section like this can be passed when configuring Elasticsearch in Benthos

```
(elasticsearch config)
...
max_in_flight: 1
tls:
  enabled: true
  root_cas_file: "/path/to/cacert"
  skip_cert_verify: false
```

Proposed PR: https://github.com/Jeffail/benthos/pull/471
