### ISSUE TITLE
AMQP 1.0 (beta): amqp:link:detach-forced

### ISSUE THREAD

**Issue by ianaz** [Jeffail/benthos#483]
Using Service Bus from Azure (which uses AMQP 1.0)

Messages are received correctly, but after I while I get this message:

```
Failed to read message: link detached, reason: *Error{Condition: amqp:link:detach-forced, Description: The link 'G19:151274741:MB9xjRjuCfMcXqGvOKbKyGeG9fJypgtW-sjO4ErGrubNtxbFpGcCxx' is force detached. Code: consumer(link11331556). Details: InnerMessageReceiver was closed. TrackingId:e33664c70000930b00ace7e45f28340d_G19_B11, SystemTracker:queue-name-dev:Queue:queue-name, Timestamp:2020-08-03T16:01:10, Info: map[]}
```
I will analyze it more tomorrow and update the ticket if I find anything helpful

My config:

```
input:
  broker:
    inputs:
    - amqp_1:
        url: "myqueueurl"
        source_address: "my-queue-name"
    batching:
      count: 180
      period: "50s"
// processors etc.....
```
