### ISSUE TITLE
Add support for rate_limit in file input

### ISSUE THREAD

**Issue by fitter22** [Jeffail/benthos#487]
Hey, I want to set my pipeline to read user credentials from file and then trigger the processing with each message (one user - one line in file - one msg). The whole pipeline should run periodically for all accounts.

I am trying to design it nicely and I though that actually my problem could be solved by the _rate_limit_ option in file input. It looks (at least for me) like a good use-case which could be used in many scenarios. What do you think about it?

**Comment by Jeffail** [comment]
Hey @fitter22, there's a [`rate_limit` processor](https://www.benthos.dev/docs/components/processors/rate_limit) you can place at the input level which would work the same way, it'd look something like this:

```yaml
input:
  file:
    path: foo
  processors:
  - rate_limit:
      resource: foolimit
```

Basically a line would be read from the file and if the rate limit blocks then it applies back pressure and prevents the next line from being read, which throttles the whole pipeline.

**Comment by fitter22** [comment]
Thanks @Jeffail 
that rate_limit processor at input + cron job should to the thing I want to achieve.

Maybe one question, because I think I might be missing something. My pipeline should execute periodically with the same input (real data input is moved to pipeline due to complicated authorization). With your proposed solution I need to trigger bentos externally to rerun the pipeline (with cron or smth similar).
But is that a proper way to go with benthos in general? In one of the previous pipelines I made, I used bloblang input as a "clock" which periodically triggers the pipeline. So I got an "infinite" execution with configurable intervals, all from within the bentos itself.

In the problem I am explaining in this issue I tried to emulate similar logic with a _sequence_ of inputs:
```
input:
  sequence:
    inputs:
      - bloblang:
          mapping: root = ""
          interval: 3s
      - file:
          path: test.txt
```
But I am getting only empty messages.
So is cron job a "proper way" to periodically re-run the pipeline with non-looping inputs, like _file_?

**Comment by Jeffail** [comment]
Hey @fitter22, that's close but the first `bloblang` input in your sequence will never finish, and therefore the `file` input won't ever be consumed, you can fix that by adding `count: 1` so it waits for the interval, produces a single message, then ends.

You can also prevent the generated message from actually appearing by making your mapping `root = deleted()`, that results in the bloblang input waiting for the interval, generating a message which gets deleted, and since the count of generated messages is now reached it closes down and the next input is consumed.

Finally, once the file input is consumed the pipeline will shut down and you'll need to restart it again. If instead you want the input to be re-consumed for every 3 second interval you can place the `sequence` input within a `read_until` input, which has the ability to restart the child input once it ends, it'll look like this:

```yaml
input:
  read_until:
    restart_input: true
    condition:
      static: false
    input:
      sequence:
        inputs:
          - bloblang:
              mapping: 'root = deleted()'
              interval: 3s
              count: 1
          - file:
              path: test.txt
```

Which is a long and confusing config. In order to make this type of pattern simpler I could add a field `restart_interval` to the `read_until` input which would delay the restart of the child inputs each time by the specified amount, it'd look like this:

```yaml
input:
  read_until:
    restart_input: true
    restart_interval: 3s
    condition:
      static: false
    input:
      file:
        path: test.txt
```

Which is a little bit nicer, I'm not sure it's intuitive to need to use a `read_until` input in order to create a timed input so maybe it's worth putting all this behaviour into something like a new `cron` input that embodies all the behaviour. I'll think it over.
