### ISSUE TITLE
Extending jmespath to add metrics from JSON fields

### ISSUE THREAD

**Issue by bigkraig** [Jeffail/benthos#49]
What are your thoughts on extending (or replicating) the jmespath condition to fetch fields and expose them as metrics? Adding counters/gauges would allow you to scrape the stream from Prometheus and generate alerts and dashboards. We'd be most interested at doing this off of a KSQL table, but I imagine it could be useful from all sorts of inputs.

**Comment by Jeffail** [comment]
Hey @bigkraig, would the goal here be to extract the value of a field from a document and change a metric by that amount? So, for example, for a document `{"foo":{"bar":4}}` we might increment the counter `stats.foo_bars` by 4?

**Comment by bigkraig** [comment]
I guess it could go a few ways.

I may want to count the amount of time I see a field (like a 4xx error) or I may want to expose the value of them, like a transaction total. If I think even further if someone is reading in their logs with response times, they may want to do a histogram.

Obviously it would make sense to just instrument the application, but we have quite a lot of legacy products where that would be difficult to do.

**Comment by Jeffail** [comment]
That sounds interesting, we could add something like a `metric` processor that allows you to mutate either a `counter`, `gauge` or `timing` metric, and the value you specify in configuration could use function interpolation (https://github.com/Jeffail/benthos/blob/master/docs/config_interpolation.md#functions) so that either you specify a static value, or extract an integer value either from metadata, a json path, etc.

If I add that as a processor you could then use a https://github.com/Jeffail/benthos/tree/master/docs/processors#conditional processor to make it conditional based on the type/contents of the message.

It could look something like this:

``` yaml
type: conditional
conditional:
  condition:
    type: jmespath
    jmespath:
      query: 'doctor.error == "people died"'
  processors:
  - type: metric
    metric:
      type: counter
      path: people.that.have.died
      operator: increment
      value: ${!json_field:doctor.people.killed}
```

Or, the shorthand version might just be:

``` yaml
type: metric
metric:
  type: counter
  path: people.that.have.died
  operator: increment
  value: ${!json_field:doctor.people.killed}
```

In which case if `doctor.people.killed` doesn't exist, isn't a number, or returns 0 it's a no-op.
