### ISSUE TITLE
Best practices for streams mode

### ISSUE THREAD

**Issue by dilipkk-foyernet** [Jeffail/benthos#494]
Hi Ashley,

Thank you so much for this awesome work, I am planning to use this library for my project, we have bunch SQS queues to process the messages from so I am planning to use streams mode to configure each input - output combination as stream.
My questions is how do I choose required CPU and memory, I am planning to run the entire process as docker container.
Is possible to have thread or go routine pool shared across streams?
For high availability, we may be running multiple instances of this setup then what should we consider for avoid duplicate processing. I know most of the work in done at SQS level it self but in cases there are bugs in out setup how do we monitor errors or duplicate processing.

Looking to hear from you soon.
Thanks,
Dilip

**Comment by Jeffail** [comment]
Hey @dilipkk-foyernet, selecting CPU and memory will probably need some trial and error as it'll depend on the size of the data you're processing and what exactly you're doing to it. When running multiple pipelines in streams mode they will share a thread pool equalling the number of threads on the machine, and for each individual stream you can configure [a number of parallel processing pipelines](https://www.benthos.dev/docs/configuration/processing_pipelines) that suits the task at hand (or set it to zero to match the number of CPUs).

For monitoring errors there are a few options available: https://www.benthos.dev/docs/guides/monitoring, each input, processor and output you configure will automatically emit metrics showing errors, but you can also use the [metric processor](https://www.benthos.dev/docs/components/processors/metric) for emitting custom metrics. For example, you could do a quick check for short term duplicates with something like this:

```yaml
pipeline:
  processors:
    - cache:
        resource: foocache
        operator: add
        key: '${! json("message.id") }'
        value: "storeme"
    - catch:
      - metric:
          type: counter
          path: duplicates.detected

resources:
  caches:
    foocache:
      memory:
        ttl: 300
```
