### ISSUE TITLE
AMQP 1.0 - connection reset by peer

### ISSUE THREAD

**Issue by ianaz** [Jeffail/benthos#507]
Hi,

we're using Benthos in production for a week now, connecting to Azure Service Bus via amqp 1.0 input with the following configuration:

```
input:
  broker:
    inputs:
    - amqp_1:
        url: "...."
        source_address: "..."
    batching:
      count: 180
      period: 220s
```

it works well except for two times where we got the following error:

```
OUR_APP_NAME.input | Failed to read message: read tcp 172.20.0.3:38854->51.107.71.205:5671: read: connection reset by peer
```

Once this error occurs, it's then repeated every second until a reboot of the application is made.
Any idea of what could it be? Checked on Azure's side and there's no error there.. might be a server issue as well i guess... but all other services on the same machine are running fine 
We're still investigating as it's not reproducible, but maybe it rings a bell to you @Jeffail..?
