### ISSUE TITLE
Outputs in switch does not have default value

### ISSUE THREAD

**Issue by rucciva** [Jeffail/benthos#511]
when using output in switch, default value are filled with go's default value instead of benthos's default value as noted in doc. 

```
{"@timestamp":"2020-09-29T13:11:59+07:00","@service":"benthos","level":"ERROR","component":"benthos","message":"Service closing due to: failed to create output 'switch': failed to create case '0' output type 'kafka': failed to create output 'kafka': failed to construct batch policy: failed to create condition: condition type was not recognised"}
```

**Comment by Jeffail** [comment]
Hey @rucciva, can you provide me with an example config that triggers this?

**Comment by rucciva** [comment]
sure

```
---
input:
  type: kafka_balanced
  kafka_balanced:
    addresses: [ ${KAFKA_BROKERS:"kafka:9092"} ]
    topics: [ ${KAFKA_INPUT_TOPICS:logs} ]
    consumer_group: ${KAFKA_CONSUMER_GROUP:my_app}
    client_id: ${KAFKA_CONSUMER_CLIENT_ID:my_app_kafka_input}
    batching:
      count: ${KAFKA_MAX_BATCH_COUNT:50}

pipeline:
  threads: ${PIPELINE_THREADS:4}
  processors:
    - type: my_custom_processor
       my_custom_processor:
  
output:
  type: switch
  switch:
    cases:
      - check: meta("output") == "kafka"
        output:
          type: kafka
          kafka:
            addresses: [ ${KAFKA_BROKERS:"kafka:9092"} ]
            client_id: ${KAFKA_PUBLISHER_CLIENT_ID:my_app_kafka_output}
            topic: ${! meta("output_kafka_topic")  }
            batching:
              byte_size: ${BATCH_SIZE:20971520}
              period: ${BATCH_PERIOD:5s}

      - check: meta("output") == "elasticsearch"
        output:
          type: elasticsearch
          elasticsearch:
            urls: [ ${ELASTICSEARCH_BASE_URLS:"http://elasticsearch:9200"} ]
            index: ${! meta("output_elasticsearch_index") }
            id: ${! meta("output_elasticsearch_id") }
            batching:
              byte_size: ${BATCH_SIZE:20971520}
              period: ${BATCH_PERIOD:5s}
    ```

**Comment by rucciva** [comment]
also another context. this happens in go test. i'm trying to write integration test of my custom processor. i invoke it somewhat like this

```
os.Args = os.Args[:1]
service.RunWithOpts(service.OptOverrideConfigDefaults(myDefaultConfigOverride))`
```

**Comment by Jeffail** [comment]
I can't seem to reproduce this with v3.29.0, are you using any custom lib to parse the YAML config or are you letting `service` do all of that?

Another possibility is that there's a mismatch in lib versions if you're building with plugins. Can you paste me the output of these two commands:

```sh
cat ./go.sum | grep benthos/v3
```

And

```sh
cat ./go.sum | grep yaml.v3
```

And I'll compare with what I've got.

**Comment by rucciva** [comment]
ah, i'm using yaml.v2, let me check first

**Comment by Jeffail** [comment]
Yeah that'll be it, is there something preventing you from using `yaml.v3`? For enforcing defaults I'm only currently implementing the v3 APIs as they're easier to work with.

**Comment by rucciva** [comment]
nope, i can safely use yaml.v3. I guess this is just me not knowing that benthos v3 use yaml v3. thanks for the fast response. cheers

**Comment by Jeffail** [comment]
No problem, I assumed plugin users were always parsing configs through `service` so I didn't make any announcements when I upgraded to yaml.v3, I think in hindsight I should have made it clearer and added comments in the plugin repo explaining the changes. Sorry for the confusion, I've marked this issue as `annoying` but will close it in favour of https://github.com/benthosdev/benthos-plugin-example/issues/5.

**Comment by jamesthompson** [comment]
I've just been bitten by this. @rucciva how did you get your plugin to parse the config properly?

**Comment by Jeffail** [comment]
@jamesthompson are you using yaml.v3? If so are you able to share any of your code?

**Comment by jamesthompson** [comment]
@Jeffail Thanks for rapid response (and excellent library)

I am a golang noob so apologies if any of this is daft.

I pulled the latest benthos-plugin-example repo and created a quick and dirty integration with the BigQuery Storage API gRPC interface. To my surprise it actually works. I'd be happy to try to tidy this up and submit as a new input some day as well if there's any interest.

My `go.mod` looks like this:

```
module github.com/benthosdev/benthos-plugin-example

go 1.16

require (
	cloud.google.com/go v0.78.0
	cloud.google.com/go/bigquery v1.15.0
	github.com/DataDog/zstd v1.4.1 // indirect
	google.golang.org/grpc v1.35.0
	github.com/googleapis/gax-go/v2 v2.0.5
	github.com/Jeffail/benthos/v3 v3.46.0
	github.com/alecthomas/participle v0.4.2-0.20191220090139-9fbceec1d131 // indirect
	github.com/fastly/go-utils v0.0.0-20180712184237-d95a45783239 // indirect
	github.com/go-redis/redis v6.15.5+incompatible // indirect
	github.com/golang/snappy v0.0.3
	github.com/google/gofuzz v1.1.0 // indirect
	github.com/gopherjs/gopherjs v0.0.0-20181103185306-d547d1d9531e // indirect
	github.com/gotestyourself/gotestyourself v2.2.0+incompatible // indirect
	github.com/hamba/avro v1.5.4
	github.com/jehiah/go-strftime v0.0.0-20171201141054-1d33003b3869 // indirect
	github.com/lestrrat-go/strftime v1.0.1 // indirect
	github.com/olivere/elastic v6.2.23+incompatible // indirect
	github.com/ory/dockertest v3.3.4+incompatible // indirect
	github.com/pbnjay/strptime v0.0.0-20140226051138-5c05b0d668c9 // indirect
	github.com/tebeka/strftime v0.1.3 // indirect
	github.com/uber-go/atomic v1.3.2 // indirect
	golang.org/x/crypto v0.0.0-20210503195802-e9a32991a82e
	google.golang.org/api v0.40.0
	google.golang.org/genproto v0.0.0-20210222152913-aa3ee6e6a81c
	gotest.tools v2.2.0+incompatible // indirect
	nanomsg.org/go-mangos v1.4.0 // indirect
)
```

and my plugin imports look like this:

```go
package input

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"math/big"
	"strconv"
	"strings"
	"sync"
	"time"

	bqs "cloud.google.com/go/bigquery/storage/apiv1"
	"cloud.google.com/go/civil"
	bqspb "google.golang.org/genproto/googleapis/cloud/bigquery/storage/v1"
	"google.golang.org/grpc"

	"github.com/Jeffail/benthos/v3/lib/input"
	"github.com/Jeffail/benthos/v3/lib/log"
	"github.com/Jeffail/benthos/v3/lib/message"
	"github.com/Jeffail/benthos/v3/lib/metrics"
	"github.com/Jeffail/benthos/v3/lib/types"
	"github.com/googleapis/gax-go/v2"
	"github.com/hamba/avro"
)
```

I have no explicit references to yaml.v3 in my imports, so it's basically just a version of your `gibberish.go` example.

This is my `go.sum` grepping for yaml:
```
cat go.sum | grep yaml
github.com/ghodss/yaml v1.0.0 h1:wQHKEahhL6wmXdzwWG11gIVCkOv05bNOh+Rxn0yngAk=
github.com/ghodss/yaml v1.0.0/go.mod h1:4dBDuWmgqj2HViK6kFavaiC9ZROes6MMH2rRYeMEF04=
gopkg.in/yaml.v2 v2.0.0-20170812160011-eb3733d160e7/go.mod h1:JAlM8MvJe8wmxCU4Bli9HhUf9+ttbYbLASfIpnQbh74=
gopkg.in/yaml.v2 v2.2.1/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
gopkg.in/yaml.v2 v2.2.2/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
gopkg.in/yaml.v2 v2.2.3/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
gopkg.in/yaml.v2 v2.2.4/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
gopkg.in/yaml.v2 v2.2.5/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
gopkg.in/yaml.v2 v2.2.7/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
gopkg.in/yaml.v2 v2.2.8/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
gopkg.in/yaml.v2 v2.3.0 h1:clyUAQHOM3G0M3f5vQj7LuJrETvjVot3Z5el9nffUtU=
gopkg.in/yaml.v2 v2.3.0/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=
gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c/go.mod h1:K4uyk7z7BCEPqu6E+C64Yfv1cQ7kz7rIZviUmN+EgEM=
gopkg.in/yaml.v3 v3.0.0-20200615113413-eeeca48fe776/go.mod h1:K4uyk7z7BCEPqu6E+C64Yfv1cQ7kz7rIZviUmN+EgEM=
gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b h1:h8qDotaEPuJATrMmW04NCwg7v22aHH28wwpauUhK9Oo=
gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b/go.mod h1:K4uyk7z7BCEPqu6E+C64Yfv1cQ7kz7rIZviUmN+EgEM=
sigs.k8s.io/yaml v1.1.0 h1:4A07+ZFc2wgJwo8YNlQpr1rVlgUDlxXHhPJciaPY5gs=
sigs.k8s.io/yaml v1.1.0/go.mod h1:UJmg0vDUVViEyp3mgSv9WPwZCDxu4rQW1olrI1uml+o=
```

My config struct looks like this with the init below:
```go
type BigQueryStorageAPISourceConfig struct {
	Project string `json:"project" yaml:"project"`
	Table   string `json:"table" yaml:"table"`
	RowRestriction string   `json:"row_restriction" yaml:"row_restriction"`
	SelectedFields []string `json:"selected_fields" yaml:"selected_fields"`
}
```

```go
func init() {
	input.RegisterPlugin(
		"bigquery_storage_api",
		func() interface{} {
			return NewBigQueryStorageAPISourceConfig()
		},
		func(iconf interface{}, mgr types.Manager, logger log.Modular, stats metrics.Type) (types.Input, error) {
			logger.Infoln("Parsing BigQuery Storage API input configuration")
			conf, ok := iconf.(*BigQueryStorageAPISourceConfig)
			if !ok {
				return nil, errors.New("failed to cast config")
			}
			logger.Infof("Using configuration: %v", conf)
			return NewBigQueryStorageAPISource(*conf, mgr, logger, stats)
		},
	)

	input.DocumentPlugin(
		"bigquery_storage_api",
		`
This plugin creates a BigQuery Storage API input converting AVRO records to pipe-delimited CSV format.`,
		nil, // No need to sanitise the config.
	)
}
```

and finally my config looks like this:
```
input:
  bigquery_storage_api:
    project: "projects/fakeproject-123"
    table: "projects/fakeproject-123/datasets/test_dataset/tables/test_table"
    selected_fields: []
    row_restriction: ""

output:
  stdout:
  label: ""

shutdown_timeout: 5s
```

This is not getting parsed at present. Do I need to sanitize my go.sum, or is there a way to be explicit about how to parse the config with a particular yaml dependency?
