### ISSUE TITLE
Fingerprint processor

### ISSUE THREAD

**Issue by rucciva** [Jeffail/benthos#52]
Hi, thanks for such a great design btw. 

I would love to use it in my scenario where i need to export and procesa logs to elasticsearch. But since benthos guarantees at-least-once delivery, i think i need a way to generate id based on the event processed so that it doesnt get duplicated in elasticsearch. Something like [logstash fingerprint plugin](https://www.elastic.co/guide/en/logstash/current/plugins-filters-fingerprint.html). 

Will this be supported?

**Comment by Jeffail** [comment]
Hey @rucciva, if I create a general purpose `hash` processor you would be able to do the following:

``` yaml
processors:
  - type: json
    json:
      operator: set
      path: id
      value: ${!json_field:some.field}-${!json_field:another.field}
  - type: process_field
    process_field:
      path: id
      processors:
        - type: hash
          hash:
            algorithm: sha256
```

And then you could use the `id` as your ES id, would that work for you?
