### ISSUE TITLE
Websockets open_message

### ISSUE THREAD

**Issue by gmonk** [Jeffail/benthos#520]
does open message have certain characters it does not like ?   I have an input that requires a message in json format to be sent like below  in order to subscribe and unsubscribe to message topics.  I have tried wrapping the message with " " and single quotes and leaving quotes off entirely and seems to not like either the { or :  characters   if this is the case can we escape these 
{
"messageType": "Subscription",
 "subscription":{
      "type": "Event",
      "action":"Subscribe
}

**Comment by Jeffail** [comment]
Hey @gmonk, it should be possible to send JSON data, can you show an example of the actual config you're using?

**Comment by gmonk** [comment]
input:
    websocket:
    open_message: "{"messageType ": "Subscription","subscription": {"type ": "Event ","action ": "Subscribe "}}"
    url: ws://x.x.x.x/api/subscriptions




The above config produces:
**Configuration file read error: yaml: line 3: mapping values are not allowed in this context**


if I comment out  open_message everything runs.  But I will not get any messages because of not sending subsciption message



I  have verified the ws subscription using websocat from the command line and everthing works as it supposed to.

**Comment by Jeffail** [comment]
Thanks, and does it still fail if you use single quotes like this:

```yaml
input:
  websocket:
    open_message: '{"messageType ": "Subscription","subscription": {"type ": "Event ","action ": "Subscribe "}}'
    url: ws://x.x.x.x/api/subscriptions
```

**Comment by gmonk** [comment]
yes is does however the error returned is different

Configuration file read error: yaml: line 2: did not find expected key

**Comment by Jeffail** [comment]
That sounds like you have an extra indentation somewhere. For example if I run:

```yaml
input:
  websocket:
    open_message: '{"messageType ": "Subscription","subscription": {"type ": "Event ","action ": "Subscribe "}}'
    url: ws://x.x.x.x/api/subscriptions
```

But if I run the following:

```yaml
input:
  websocket:
    open_message: '{"messageType ": "Subscription","subscription": {"type ": "Event ","action ": "Subscribe "}}'
      url: ws://x.x.x.x/api/subscriptions
```

Then I get the `Configuration file read error: yaml: line 2: did not find expected key` error.
