### ISSUE TITLE
Auto Acknowledgment RabbitMQ Consumer

### ISSUE THREAD

**Issue by islamhamdi** [Jeffail/benthos#521]
Hi,

I'm trying to use benthos for consuming messages out of rabbitmq and publishing them to S3, the following configs are used:

```
input:
  amqp_0_9:
    url: amqp://<username>:<password>@rabbitmq-domain.com:5672
    queue: <queue-name>
    consumer_tag: benthos-consumer
    prefetch_count: 10

output:
  s3:
    bucket: <s3-bucket-name>
    path: ${!count("files")}-${!timestamp_unix_nano()}.txt
    content_type: application/octet-stream
    max_in_flight: 1000 # increase throughput, max #messages in flight
    storage_class: INTELLIGENT_TIERING
    batching:
      count: 1000
    region: <region>
    credentials:
      id: <aws-key>
      secret: <aws-secret>
```

However, as the default prefetch count is 10, messages get blocked because we require acknowledging messages to rabbitmq after the consumption, and no more messages can be fetched/consumed, is there a way to auto-ack messages after consuming them?

**Comment by Jeffail** [comment]
Hey @islamhamdi, if you stick a [memory buffer](https://www.benthos.dev/docs/components/buffers/memory) in your pipeline then it'll acknowledge messages as they are consumed:

```yaml
input:
  amqp_0_9:
    url: amqp://<username>:<password>@rabbitmq-domain.com:5672
    queue: <queue-name>
    consumer_tag: benthos-consumer
    prefetch_count: 10

buffer:
  memory: {}

output:
  s3:
    bucket: <s3-bucket-name>
    path: ${!count("files")}-${!timestamp_unix_nano()}.txt
    content_type: application/octet-stream
    max_in_flight: 1000 # increase throughput, max #messages in flight
    storage_class: INTELLIGENT_TIERING
    batching:
      count: 1000
    region: <region>
    credentials:
      id: <aws-key>
      secret: <aws-secret>
```

But I can also take a look at adding an `autoack` field that would be a better solution in your case.
