### ISSUE TITLE
Multiple metric label renames applied randomly

### ISSUE THREAD

**Issue by nicktelford** [Jeffail/benthos#522]
If you provide benthos with multiple label renames to apply:
```
metrics:
  rename:
    by_regexp:
    - pattern: "resource\\.processor\\.(.+)\\.processor\\.(\\d+)\\.(.+)"
      to_label:
        resource_type: processor
        resource_name: $1
        processor: $2
      value: $3
```

The assignment of label values will often be random. This is because `to_label` is a `map`, and map traversal order is random.
