### ISSUE TITLE
Panic on rename of metrics with different label cardinality

### ISSUE THREAD

**Issue by nicktelford** [Jeffail/benthos#524]
This causes benthos to panic due to the different number of labels between metrics:
```
metrics:
  rename:
    by_regexp:
   - pattern: "resource\\.output\\.(.+)\\.processor\\.(\\d+)\\.(.+)"
     to_label:
       resource_type: output
       resource_name: $1
       processor: $2
     value: $3
   - pattern: "resource\\.output\\.(.+)\\.(.+)"
     to_label:
       resource_type: output
       resource_name: $1
     value: $2
```

This is extremely inconvenient, as the number of labels for a Prometheus metric will often vary based on the metric in question.

**Comment by Jeffail** [comment]
Unfortunately, I don't think it's possible to have prometheus metrics of the same name and a different number of labels, so you'd either need to ensure that the value you rename the metric to would be different in these two renames or that the number of labels matches, which you can do with just an empty label:

```yaml
metrics:
  rename:
    by_regexp:
     - pattern: "resource\\.output\\.(.+)\\.processor\\.(\\d+)\\.(.+)"
       to_label:
         resource_type: output
         resource_name: $1
         processor: $2
       value: $3
     - pattern: "resource\\.output\\.(.+)\\.(.+)"
       to_label:
         resource_type: output
         resource_name: $1
         processor: ""
       value: $2
```

However, I'll still need to fix https://github.com/Jeffail/benthos/issues/522 for this to work properly.
