### ISSUE TITLE
Long numbers parsed as scientific notation

### ISSUE THREAD

**Issue by zaiboot** [Jeffail/benthos#530]
I have the following session
https://lab.benthos.dev/l/23r0oZ00sR9 and for the sake of keeping the code visible will post it here:

input.json
```
{
    "long": 228930314431312345,
    "id": "foo",
    "links": [
        "https://github.com/Jeffail/benthos",
        "https://docs.benthos.dev",
        "https://www.benthos.dev"
    ]
}
```

config.yaml
```
pipeline:
    processors:
    - bloblang: |
        message = this.long
    - log:
        level: INFO
        message: 'message asdsa${! json("message") }'
```

I get the following input
```
Log: message 2.2893031443131235e+17
{"message":228930314431312350}
```

Basically I've been reading about json and javascript and long/ big numbers and it appears json itself do not provide a way to handle long/ big numbers. Some workarounds are the modify the source json file to wrap the number in " or converting it into a string. When I try to inspect the type it returns 
`number`, which is correct. But this is not an actual number but a big number.

I already tried:
* `${! json("message").string() }`
* `message = this.long.string()´ => returns `{"message":"2.2893031443131235e+17"}`
Just wondering if there is any kind of workaround? I mean I can always do a regexp to parse the data but it feels a bit hacky.

I tried to look related issues but none resemble to this.

Thanks and I hope this makes sense.
