### ISSUE TITLE
Set Cache TTL by key

### ISSUE THREAD

**Issue by mfamador** [Jeffail/benthos#531]
Hi!
I believe the only way to set the cache TTL is defining it in the cache resource.
It would be very useful to be able to define it also when setting or adding the key-value in the cache processor.

For instance, when caching an OAuth token, which has an expiry timestamp, it would be nice to set the cache TTL to that expiry time, instead of using one defined globally in the resource cache. 
I believe it could be easily feasible and backwards compatible adding an optional field `ttl` to the cache processor (used only on `set` and `add` operators).

Something like this:
```
pipeline:
  processors:
  - branch:
      processors:
      - cache:
          resource: tokencache
          operator: get
          key: token
      - catch:
        - oauth2_token:
            endpoint: https://my-identity-server
            client_id: my-client-id
            client_secret: a-secret
            scopes:
            - devices-api
        - cache:
            resource: tokencache
            operator: set
            key: token
            ttl: '${! this.expiry.parse_timestamp_unix()-timestamp_unix() }'
            value: '${! json() }'
      result_map: |
        token = this

resources:
  caches:
    tokencache:
      memory:
        ttl: 600
```
