### ISSUE TITLE
Bloblang for field values

### ISSUE THREAD

**Issue by codingconcepts** [Jeffail/benthos#542]
It would be great to have a list of fields that support Bloblang as described in the [Interpolation](https://www.benthos.dev/docs/configuration/interpolation) page.

I'm hoping to spin up multiple Kafka consumers with different client_ids but the client_id doesn't seem to support Bloblang:

``` yaml
input:
    kafka_balanced:
        addresses:
            - localhost:9092
        topics: [ topic.1 ]
        client_id: ${! uuid_v4() }
        consumer_group: example

output:
  stdout: {}
```

The output of running against the above configuration is as follows:

```
{"@timestamp":"2020-11-02T20:21:19Z","@service":"benthos","level":"ERROR","component":"benthos.input","message":"Failed to connect to kafka_balanced: kafka: invalid configuration (ClientID is invalid)"}
```

Does this field support Bloblang, or have I misunderstood something?
