### ISSUE TITLE
Problem parsing numbers from json input using the metrics processor and function interpolation

### ISSUE THREAD

**Issue by kekscode** [Jeffail/benthos#553]
I try to achieve the following:

* Read JSON from an API (once)
* create custom metrics with the `metric` processor using values from the JSON by bloblang function interpolations
* end the benthos process (which sends the data to a push_gateway for scraping asynchronously by prometheus)

I always get `0` values instead of the real integers and float values from the json on the push_gateway and benthos tells me:

`{"@timestamp":"2020-11-14T14:32:46+01:00","@service":"benthos","level":"ERROR","component":"benthos.input.processor.2","message":"Handler error: strconv.ParseInt: parsing \"null\": invalid syntax"}
      "inside_temp": 23.6,
      "outside_temp": 15.5`

Benthos version (on MacOS):

```
benthos -v
Version: 3.32.0
Date: 2020-10-29T20:22:48Z
```

I created a small example configuration for reproduction:

`config.yml`:

```
metrics:
  prometheus:
    push_url: localhost:9091  # docker run -p 9091:9091 prom/pushgateway

input:
  stdin: {}
  processors:
    - metric:
        name: inside_temperature
        type: gauge
        value: ${! json("response.climate_state.inside_temp") }
    - metric:
        name: outside_temperature
        type: gauge
        value: ${! json("response.climate_state.outside_temp") }
    - metric:
        name: battery_level
        type: gauge
        value: ${! json("response.charge_state.battery_level") }
```

and incoming json example.json:

```
{
  "response": {
    "charge_state": {
      "battery_level": 50
    },
    "climate_state": {
      "inside_temp": 23.6,
      "outside_temp": 15.5
    }
  }
}
```

Testing is done via:

```
cat example.json | benthos -c config.yml
```

while the push_gateway test instance is running as `docker run -p 9091:9091 prom/pushgateway`

Any idea what i'm doing wrong?
Note: I tried to add `.number()` to the bloblang function interpolation, but that didn't change anything.
