### ISSUE TITLE
Message get corrupted when logging is active

### ISSUE THREAD

**Issue by stergiotis** [Jeffail/benthos#554]
Trying to fuzz a plugin of mine, I found that benthos seems to corrupt messages in-deterministically when logging messages are emitted. Below my minimal example. Run it a few times until you see `{check: "fail", ...}` messages appear in the output. I couldn't observe the problem when I set the log-level of the processor below the threshold (e.g. here DEBUG).

Many thanks for looking into this!

```yaml
input:
  file:
    codec: lines
    delete_on_finish: false
    max_buffer: 1000000
    multipart: false
    paths:
      - /usr/bin/bash
      #- /dev/urandom
pipeline:
  processors:
    - bloblang: |
         meta orig = content()
    - log:
       level: INFO
       message: "dummy"

    - bloblang: |
        root = match {
          meta("orig") == content() => {"check": "pass"}
          _ => {"check": "fail","orig": {"content": meta("orig").encode("base64"), "len": meta("orig").length()}, "transf": {"content": content().encode("base64"), "len": content().length()}}
        }
  threads: 1
output:
  file:
    path: "out3.txt"
    delimiter: ""
logger:
  prefix: benthos
  level: INFO
  add_timestamp: true
  json_format: true
  static_fields:
    '@service': benthos
```
