### ISSUE TITLE
Inproc example?

### ISSUE THREAD

**Issue by bigkraig** [Jeffail/benthos#56]
I'm sure its just that I am misunderstanding the configuration, but is there a simple example of using inproc for input & output?

What I am trying to achieve is a Kafka input that is then sent to a few different processor paths, where I can filter based off of different things and send to different outputs or calculate metrics.

**Comment by bigkraig** [comment]
..or would a fan_out broker output be better?

**Comment by Jeffail** [comment]
Hey @bigkraig, yeah that sounds like something you would want to do with a `fan_out` output broker. Your output block could look something like this:

``` yaml
output:
  type: broker
  broker:
    pattern: fan_out
    outputs:
      - type: foo
        processors:
          - type: filter
            filter: {} # TODO
      - type: foo
        processors:
          - type: filter
            filter: {} # TODO
      # ... etc ...
```

The `inproc` types are more for linking multiple stream pipelines when running Benthos in streams mode: https://github.com/Jeffail/benthos/blob/master/docs/streams/README.md
