### ISSUE TITLE
Serverless runtime errors required for Benthos to support AWS lambda event source processing

### ISSUE THREAD

**Issue by razor-x** [Jeffail/benthos#591]
When connecting an AWS Lambda function to an AWS event source, many sources have default behaviour when the lambda function returns a runtime error. Since, given a valid config, Benthos in Serverless mode does not throw runtime errors on pipeline failure and thus always returns successfully from AWS's perspective, using Benthos for many typical Lambda use-cases is not possible.

Services that expect to handle errors include DynamoDB Streams, SQS, Step Functions, Cognito, S3, Kinesis, etc.

For clarity, let's compare processing an SQS queue from a Benthos container vs a Benthos AWS Lambda.

### Container

- Input type: `sqs`
- If any step in the pipeline fails, the input will NOT delete the SQS message, allowing for an eventual retry or deadletter of the message by SQS. 

### Lambda

With SQS message processed by lambda, if the lambda returns an error the message is not deleted, and will retry until the lamdba returns no error (or the attempts are exceeded and the message is sent to a deadletter queue if configured).

- Benthos input type: None (Serverless)
- If any step in the pipeline fails, e.g., saving to an output, Benthos does NOT throw a runtime error, so AWS deletes the source message from SQS (assumes the message was processed correctly).

**Comment by Jeffail** [comment]
Hey @razor-x, if the output fails (i.e. an `http_client` output can't reach the target endpoint) then I would expect the handler to return an error, can you confirm that is not the case? If so I'll upgrade this from annoying to a bug.

The other requirement here is nacking (returning an error in this context) when processors fail rather than when an output fails, which would mean you could "fail" a lambda when processing fails. I think once we have a solution to this it should eventually be the default, but we'd need to wait for v4 for that because it would technically be a breaking change.

I think the quick and dirty solution would be to add a `nack` output type, which would always return a send error, that would allow you to use a `switch` that nacks messages based on processing errors like this:

```yaml
output:
  switch:
    cases:
      - check: !errored()
        output:
          sync_response: {}
      - output:
          nack: {}
```

Although it's worth mentioning that you can hack together this solution with an output that always fails:

```yaml
output:
  switch:
    cases:
      - check: errored()
        output:
          http_client:
            url: http://localhost:1234/this/url/always/fails
      - output:
          gcp_pubsub:
            project: therealtarget
            topic: thing
```

**Comment by razor-x** [comment]
@Jeffail Got on a bit of a side track here and made a new skeleton repo for deploying Benthos on AWS Lambda: https://github.com/makenew/serverless-benthos

Anyway, I'm going to use that to make another repo where I can push minimal working examples of questions / bugs I find. First case being the cases we are discussing here.

In the meantime, I thought you might like to checkout the skeleton repo. It handles bundling the config inside the zip and for runs entirely on GitHub actions with fully automated test / deployments.

**Comment by razor-x** [comment]
I validated a failed output does give an error via

```yaml
---
pipeline:
  processors:
    - bloblang: |
        root.body = "{\"data\":\"TODO\"}"
        root.statusCode = 200

output:
  broker:
    pattern: fan_out_sequential
    outputs:
      - http_client:
          url: http://localhost:1234/this/url/always/fails
          timeout: 2s
      - type: serverless_response
```

The error can be a bit opaque since it's raw from the processor with no context, but the logs do have the info

Throws

```json
{
  "errorMessage": "request cancelled",
  "errorType": "errorString"
}
```

Logs

```json
{"@timestamp":"2020-12-16T18:03:39Z","functionName":"rxbugs-serverless-benthos-stg-trigger-err","version":"0.0.1","level":"ERROR","component":"benthos.output","message":"Failed to dispatch fan out message to output '0': Post \"http://localhost:1234/this/url/always/fails\": dial tcp 127.0.0.1:1234: connect: connection refused"}
```

Would expect instead for it to throw

```json
{
  "errorMessage": "Failed to dispatch fan out message to output '0': Post \"http://localhost:1234/this/url/always/fails\": dial tcp 127.0.0.1:1234: connect: connection refused",
  "errorType": "errorString"
}
```

For the processor case, the `nack` idea sounds fine. Another option I can think of is adding an option to the `serverless_response` output type that allows you to pass an error (or opt in to the behaviour). The nack output is more versatile but would mean a lot more boiler plate in serverless configs.

```yaml
output:
  serverless_response:
    throw_if_errored: true
```

Or

```yaml
output:
  serverless_response:
    # Will throw this error if errored()
    error_message: "processing failed due to: ${! error() }"
```

Or 

```yaml
output:
  serverless_response:
    # Will throw this error if errored()
    nack: "processing failed due to: ${! error() }"
    nack: '' # default in v3
    nack: "${! error() }" # default in v4
```

**Comment by razor-x** [comment]
Side note, I can't use `serverless_response` with benthos tests

```
$ benthos test config
Failed to execute test target 'config/trigger-err.yaml': line 9: line 1: type 'serverless_response' was not recognised
```

**Comment by Jeffail** [comment]
Ohhh I like the idea of adding it as a field to the `serverless_response` and `sync_response` outputs. However, that would only be a convenience in the case where _only_ the sync or serverless responses are the output target, and I've already seen cases where users would want to do this with other output types as well.

The `serverless_response` output has a general equivalent [`sync_response`](https://www.benthos.dev/docs/components/outputs/sync_response), which can be used in both lambdas and unit test configs. In fact the only reason `serverless_response` still exists is backwards compatibility. I'll remove it from the docs as it's not relevant anymore.

I think to start with I'll add a beta `nack` output that'll give us a chance to play around with the concept and solve more use cases. Then if we're happy we can add it to `sync_response`, I think in most cases a user probably won't be interested in customizing the error message, so I might start off with two fields:

```yaml
output:
  sync_response:
    nack_on_error: true
    nack_custom_message: "processing failed due to: ${! error() }"
```

**Comment by Jeffail** [comment]
I've added a quick and dirty `reject` output type: https://github.com/Jeffail/benthos/commit/2008eaf72c82f5cd32504621a2ade9ad8e13b17e

**Comment by razor-x** [comment]
This looks great! Done quick but doesn't look too dirty.

**Comment by Jeffail** [comment]
Marked this as V4 since the next phase (making the reject behaviour the default) will need to wait for the next major version release as it could break existing deployments.

**Comment by razor-x** [comment]
Perhaps a silly question, but maybe there is gotcha I am not aware of. Would these be equivalent?

```yaml
output:
  switch:
    cases:
      - check: '!errored()'
        output:
          amqp_1:
            url: amqps://guest:guest@localhost:5672/
            target_address: queue:/the_foos

      - output:
          reject: "processing failed due to: ${! error() }"
```

vs checking for the error first?

```yaml
output:
  switch:
    cases:
      - check: errored()
        output:
          reject: "processing failed due to: ${! error() }"
      - output:
          amqp_1:
            url: amqps://guest:guest@localhost:5672/
            target_address: queue:/the_foos
```

Mainly thinking it makes more sense if there were more switches to "fail first" (meaning the error case always beats anything else).
