### ISSUE TITLE
Improve unit test error reporting to include processor errors on fail

### ISSUE THREAD

**Issue by mangatmodi** [Jeffail/benthos#592]
I have the following processor in `config.yml`

```yaml
pipeline:
  processors:
    - bloblang: |
        root.doc =  this
        root.key = meta("kafka_key").parse_json()
        root.topic = meta("kafka_topic")
```

I have the following test in `config_benthos_test.yml`
```yaml
parallel: true
tests:
    - name: Map the kafka content correctly
      environment: {}
      target_processors: /pipeline/processors/0
      input_batch:
        - content: "{\"AnyKey\":\"AnyValue\"}"
          metadata:
            kafka_key: "{\"KafkaKey\":\"KafkaValue\"}"
      output_batches:
        - - content_equals: "{\"key\":\"{\"KafkaKey\":\"KafkaValue\"}\"}"
```

But the test doesn't apply the `boblang` processor, it emits the input as it is

```
Test 'config.yaml' failed

Failures:

--- config.yaml ---

Example test case [line 3]:
batch 0 message 0: content_equals: content mismatch
  expected: {"key":"{"KafkaKey":"KafkaValue"}"}
  received: {"AnyKey":"AnyValue"}
```

I am using benthos version 3.35.0 and I am executing the test using `benthos test ./`. Not sure what I am doing wrong. The test is able to find the processor I need. I did the manual test, the mapping is working.

**Comment by Jeffail** [comment]
Hey @mangatmodi, if you run it with trace logging enabled `benthos test --log trace .` you'll see there's an error when executing your mapping: `failed to execute mapping query at line 3: metadata value not found`, which is because there's no `kafka_topic` metadata value in your test input.

There's two annoying ways in which Benthos hasn't been helpful here:
1. If a test fails then it makes sense to print an error if there is one, rather than just the expected vs actual output
2. When the `meta` function fails because a key is missing it doesn't actually print the key it tried to find

These can both be improved so if you don't mind I'll use this issue to track it.

**Comment by mangatmodi** [comment]
@Jeffail Thank you so much for the quick and great response. I agree the message should have been helpful. The main reason for the test failure was the wrong input data. However this leads to my next question.

If the data is wrong(as in my case), does it means that `bloblang` will emit the input content as it is? I thought it would drop the message and print a log line :-/

**Comment by Jeffail** [comment]
It's up to you, by default Benthos never drops data, it'll instead mark the message as having failed and you're able to handle that in variety of ways depending on your use case, here's an overview: https://www.benthos.dev/docs/configuration/error_handling

In your case you can delete data with a `catch` processor:

```yaml
pipeline:
  processors:
    - bloblang: 'root = meta("foobar")'
    - catch:
      - log:
          message: "Payload ${! content() } failed due to ${! error() }, dropping it"
      - bloblang: 'root = deleted()'
```

**Comment by mangatmodi** [comment]
Thanks a lot again, I would make changes and now will also add a failure test :)

**Comment by mangatmodi** [comment]
@Jeffail Sorry I am back again. I added a test which shall fail
```yaml
    - name: Drop the incorrect data
      environment: {}
      target_processors: /pipeline/processors/0
      input_batch:
        - content: "{\"AnyKey\":\"AnyValue\"}"
          metadata: # kafka_key is missing
            kafka_topic: "any-topic"

      output_batches:
        - - content_equals: "{\"AnyKey\":\"AnyValue\"}"

```

And changed my processor to 
```yaml
pipeline:
  processors:
    - bloblang: |
        root.doc =  this
        root.key = meta("kafka_key").parse_json()
        root.topic = meta("kafka_topic")
    - catch:
      - log:
        message: "Error while processing a message"
        level: ERROR
        fields:
          payload: ${! json() }
          from_topic: ${! meta("kafka_topic")}
          error: ${! error() }
      - bloblang: 'root = deleted()'
```

But it looks like it is not going to the catch block. I don't get this log message on `--trace` and the content is still `{"AnyKey":"AnyValue"}` instead of empty.

**Comment by Jeffail** [comment]
Looks like you're only targetting the first bloblang processor with `target_processors: /pipeline/processors/0`, if you change that to point to the list of processors with `target_processors: /pipeline/processors` then it should execute them all. I did the exact same thing just an hour ago :stuck_out_tongue:

**Comment by mangatmodi** [comment]
True, that makes sense. I also had a syntax error. One last question :P How do I test zero output batches? 
I got - `processors resulted in zero output batches` when I tried - `content_matches: "^$"`

**Comment by mangatmodi** [comment]
got it, I needed this
```

    - name: Drop the incorrect data
      environment: {}
      target_processors: /pipeline/processors
      input_batch:
        - content: "{\"AnyKey\":\"AnyValue\"}"
          metadata: # kafka_key is missing
            kafka_topic: "any-topic"

      output_batches:
        

```
