### ISSUE TITLE
Support batching for output HDFS  

### ISSUE THREAD

**Issue by deavil** [Jeffail/benthos#600]
Hi!
Are there any plans for supporting writing to HDFS with batching? We want to writing compressed files with size witch equal size of hdfs block.

**Comment by Jeffail** [comment]
Hey @deavil, yeah this should be quick to add. In the meantime you can currently define batches using a broker (with a single output):

```yaml
output:
  broker:
    outputs:
      - hdfs:
          hosts:
            - localhost:9000
          directory: foo
          path: ${!count("files")}-${!timestamp_unix_nano()}.tar.gz
    batching:
      count: 1000
      processors:
        - archive:
            format: tar
        - compress:
            algorithm: gzip
```
