### ISSUE TITLE
xml processor truncates content with i, b and em html tags 

### ISSUE THREAD

**Issue by salimane** [Jeffail/benthos#616]
We are using the XML processor https://www.benthos.dev/docs/components/processors/xml
The XML processor truncates content with i, b, and em HTML tags . Here is how to reproduce it :

`xml-to-json.yaml`
```
input:
  files:
    path: "./sample.xml"

pipeline:
  processors:
    - type: xml
      xml:
        operator: to_json
```

`sample.xml`
```
<article>
<p>Hello World <em>truncate me</em> here </p>
</article>
```

```
$ benthos -c xml-to-json.yaml
{"@timestamp":"2021-01-13T10:08:10+01:00","@service":"benthos","level":"INFO","component":"benthos","message":"Launching a benthos instance, use CTRL+C to close."}
{"@timestamp":"2021-01-13T10:08:10+01:00","@service":"benthos","level":"INFO","component":"benthos","message":"Listening for HTTP requests at: http://0.0.0.0:4195"}
{"article":{"p":"Hello World"}}
{"@timestamp":"2021-01-13T10:08:10+01:00","@service":"benthos","level":"INFO","component":"benthos","message":"Pipeline has terminated. Shutting down the service."}
```

@Jeffail are we doing something wrong?

**Comment by Jeffail** [comment]
Hey @salimane, it might be possible to support mixed content tags (https://www.w3.org/TR/REC-xml/#sec-mixed-content) in future but it looks as though the library Benthos is using (https://github.com/clbanning/mxj) doesn't have that yet. However, I doubt that being able to fully parse HTML is within the scope of the library (and this processor).

The output that you're seeing currently is a best attempt to parse HTML as XML, it might be possible to expand it so that mixed content tags are simply ignored but there might be other side effects that make this processor unsuitable for working with HTML.

**Comment by salimane** [comment]
@Jeffail are there any other processors that we can mix up with the XML one to have better results with HTML?

**Comment by Jeffail** [comment]
Been thinking about this. What we could potentially do is expand the existing `strip_html` bloblang method (https://www.benthos.dev/docs/guides/bloblang/methods#strip_html) to allow you to provide an explicit list of elements to keep within the stripped output, which would allow you to preserve the overall HTML structure, and then follow it with an XML parse. It would look something like this:

```yaml
pipeline:
  processors:
    - bloblang: 'root = content().strip_html(["article","p"])'
    - xml:
        operator: to_json
```

And if I also add a `parse_xml` method to bloblang then it'll become even simpler:

```yaml
pipeline:
  processors:
    - bloblang: 'root = content().strip_html(["article","p"]).parse_xml()'
```
