### ISSUE TITLE
Cassandra doesn't seem to respect retries

### ISSUE THREAD

**Issue by codingconcepts** [Jeffail/benthos#625]
The Cassandra output does not appear to respect retries:

**cassandra.yaml**
```yaml
input:
  stdin: {}

output:
  try:
  - cassandra:
      addresses: [localhost]
      password_authenticator:
        enabled: true
        username: cassandra
        password: cassandra      
      consistency: LOCAL_QUORUM
      backoff:
        initial_interval: 100ms
        max_interval: 1s
        max_elapsed_time: 30s
      query: INSERT INTO sandbox.test ("id") VALUES (?)
      args:
      - ${! json("id") }
  - stdout: {}
```

Run Cassandra with the following command:
```
$ docker run -it --name cassandra -p 9042:9042 bitnami/cassandra:latest
```

Run benthos with this configuration (`benthos -c cassandra.yaml`), then - once connected and running but before sending a message - pause the Docker containing running the following:
```
$ docker pause <ID_OF_CASSANDRA_CONTAINER>
```

Send in an message:
```
> {"id": 1}
```

Wait for 5-10s, then start Cassandra again:
```
$ docker unpause <ID_OF_CASSANDRA_CONTAINER>
```

The message will try and fail to send to Cassandra, then immediately write to stdout, without attempting Cassandra again, as per the backoff configuration.
