### ISSUE TITLE
Implement a New Authentication Type for HTTP

### ISSUE THREAD

**Issue by kozelok** [Jeffail/benthos#643]
Hello,

I need to use a 3rd party authentication scheme which isn't Basic/Oauth and uses a custom header instead. Is it possible to implement a custom auth strategy using plugin?

Thank you!

**Comment by Jeffail** [comment]
Hey @kozelok, yeah I've seen similar patterns in the past, the headers field https://www.benthos.dev/docs/components/processors/http#headers supports interpolation functions in the value, so you could run a plugin to get your auth value and set it as metadata then access it in the headers field with something like:
```yaml
http:
  headers:
    x-foo-bar: ${!meta("auth_token")}
```

**Comment by kozelok** [comment]
Is there a way to do this in the Input block? I am looking to have a scheduled poll rate using http_client. It is at this step that I need to set the header.

Would I need to create a separate pipeline in streams mode and pull it out from cache?

**Comment by Jeffail** [comment]
That might get tricky, one possibility is to use a [bloblang input](https://www.benthos.dev/docs/components/inputs/bloblang) to generate a trigger message at an interval, and from that message trigger your plugin to establish the auth credentials, followed by an [http processor](https://www.benthos.dev/docs/components/processors/http).

However, I'm currently in the process of implement a plugin API for bloblang functions and methods, at which point it would be possible to wrap your auth credential logic in a function plugin and do something like this:

```yaml
input:
  http_client:
    url: http://localhost:4195/get
    verb: GET
    headers:
      x-auth-header: ${! get_credentials() }
```
