### ISSUE TITLE
Unrecoverable errors from jmespath

### ISSUE THREAD

**Issue by patrobinson** [Jeffail/benthos#649]
Hi again 😄 

I'm facing an interesting problem with jmespath processor when it fails at a given point but does not set the error flag on that message.

Example pipeline:

```yaml
---
logger:
  prefix: benthos
  level: DEBUG
  add_timestamp: true
  json_format: true
  static_fields:
    '@service': benthos
input:
  http_server:
    path: /post
    timeout: 5s
pipeline:
  processors:
  - switch:
    - condition:
        type: "jmespath"
        jmespath:
          query: >
            contains(keys(foo), 'bar')
      processors:
      - log:
          level: DEBUG
          message: '${!json_field:foo.bar}'
  - catch:
    - log:
        message: "Processing failed due to: ${!error()}"
output:
  switch:
    retry_until_success: false
    cases:
      - check: '!errored()'
        output:
          stdout:
            delimiter: ""
      - check: errored()
        output:
          reject: "processing failed due to: ${! error() }"
```

Example message:
```
{
    "foo": "notBar"
}
```

When I send this event to my pipeline I get a 200 response. I expect the message to be rejected and receive a 502 (although probably should be a 500, but that's not today's issue)

```
12:42 $ curl -sf -o /dev/null -w "%{http_code}\n" -F 'foo=@debug/invalid_record.json;type=text/plain' localhost:4195/post
200
```

Benthos logs the error and outputs the message:
```
{"@timestamp":"2021-02-01T12:42:14+11:00","@service":"benthos","level":"DEBUG","component":"benthos.pipeline.processor.0.0.condition.jmespath","message":"Failed to search json: Invalid type for: notBar, expected: []jmespath.jpType{\"object\"}"}
{
    "foo": "notBar"
}
```

Is this just a caveat of jmespath? This behaviour concerns me as I never expect Benthos to silently fail. Testing with Bloblang if I create a similar scenario (although not exactly the same because Bloblang doesn't throw an error in this one) it behaves as expected. However I'm concerned about other edge cases now that I can't foresee

**Comment by Jeffail** [comment]
Hey @patrobinson, thanks for raising this and for the write up. Unfortunately this is a limitation of the `condition` component type and is one of the reasons it's now deprecated. My original thought process was that since error handling in `jmespath` is quite difficult and very verbose it would be a better user experience to treat a query that throws an error the same as a `false` for the purpose of conditions, but when using a regular `jmespath` processor a thrown error will still "fail" the message.

I've double checked how this works with the `check` field using a bloblang expression, and can confirm that you will get error logs and a failed condition when a bloblang `check` throws an error within the `switch` processor. However, it's still possible for the message to also pass subsequent cases. I consider this to be a bug for the same reasons you've outlined so I'll get that fixed this evening, but unfortunately I can't fix the old `condition` mechanism without introducing breaking changes.

**Comment by Jeffail** [comment]
The bloblang check part of this is fixed in: https://github.com/Jeffail/benthos/commit/001dcd91b6b5d5a569e89b688efd5900b1df2487

@patrobinson Closing for now but if you have any follow up questions feel free to reopen.

**Comment by patrobinson** [comment]
Thanks for the very quick response, truly love your work.

So in short the answer is:
- Don't use jmespath (use bloblang)
- Don't use condition (use check)

Is that a fair summary?

**Comment by Jeffail** [comment]
Yeah exactly, I won't be removing conditions until V4 so they'll be supported in their current state for a while, but `check` should solve all the same problems in a better way so I'd recommend using it if you can. If there's something it can't do that conditions can then open an issue as that's something I'd want to fix ASAP.

**Comment by patrobinson** [comment]
@Jeffail very similar scenario (let me know if you want me to create a seperate issue) When using the `check` with bloblang, if I send some input that's not JSON (in this case `abc`) then it fails the check but doesn't reject my message, as no error flag is set:

config:
```yaml
---
logger:
  prefix: benthos
  level: DEBUG
  add_timestamp: true
  json_format: true
  static_fields:
    '@service': benthos
input:
  http_server:
    path: /post
    timeout: 5s
pipeline:
  processors:
  - switch:
      - check: this.exists("digestS3Object").catch(throw("not valid JSON"))
        processors:
        - filter:
            any: {}
output:
  switch:
    retry_until_success: false
    cases:
      - check: '!errored()'
        output:
          stdout:
            delimiter: ""
      - check: errored()
        output:
          reject: "processing failed due to: ${! error() }"
```

output
```
13:39 $ benthos -c test-pipeline.yml 
{"@timestamp":"2021-02-02T13:39:55+11:00","@service":"benthos","level":"INFO","component":"benthos","message":"Launching a benthos instance, use CTRL+C to close."}
{"@timestamp":"2021-02-02T13:39:55+11:00","@service":"benthos","level":"INFO","component":"benthos","message":"Listening for HTTP requests at: http://0.0.0.0:4195"}
{"@timestamp":"2021-02-02T13:40:39+11:00","@service":"benthos","level":"ERROR","component":"benthos.pipeline.processor.0","message":"Failed to test case 0: failed to execute mapping query at line 1: not valid JSON"}
abcd
```
