### ISSUE TITLE
Log Processor - Number Fields

### ISSUE THREAD

**Issue by bojtirmw** [Jeffail/benthos#654]
Hey @Jeffail ,

as I see, when using the log processor, all the values of the specified fields are put into the final json as strings. Can it be achieved somehow to put integers there?

I would expect the `count` field of the json to be number if I was using the following example config:
```
pipeline:
  processors:
    - log:
        level: DEBUG
        message: "foo"
        fields:
          count: '${! json("count").number() }'
```
Suppose `count=100`, instead of getting `{"count":100}` it is `{"count":"100"}` which causes troubles when trying to visualise or aggregate it in Kibana.

**Comment by Jeffail** [comment]
Hey @bojtirmw, currently we're limited to only strings due to the underlying log interface, there's some work planned to simplify and improve that API for version 4 of Benthos: https://github.com/Jeffail/benthos/issues/589.

However, we aren't necessarily prevented from solving this before v4 as it's possible to implement the improved APIs in a dormant way that wouldn't break backwards compatibility and is accessible specifically by the log processor. The other question is how to expose this in YAML configs, one way would be to introduce a new mapping field that executes bloblang, allowing you to create a fields object with explicit types and coercion, it'd look something like this:

```yaml
pipeline:
  processors:
    - log:
        level: DEBUG
        message: "foobar"
        fields:
          for_example: "an old string based field: ${! error() }"
        fields_mapping: |
          root.count = this.count.number()
```

Which I quite like, we'd need to make it clear in the docs that anything within `fields` is added _after_ the `fields_mapping`.
