### ISSUE TITLE
Multiple Kafka inputs to multiple SQL outputs keeping 1:1 relationship for input:output

### ISSUE THREAD

**Issue by drurenia** [Jeffail/benthos#660]
I'd like to have only one configuration file where I can consume multiple Kafka topics and write each record from a topic to its correspondent database table:

```
Topic A ---------\                                 /---------------- Table A
                 | ----------- Processor A  ------|
Topic B ---------/                                 \----------------- Table B

``` 

I've noticed there is an option using a `broker` which allows us to have multiple inputs and outputs. However, I have not seen a way to make sure inputs from `Topic A` find their way to only `Table A` since none of the patterns available in the output broker gives us a way to consistently route records from an input to a specific output.

Is there a way to achieve that? If not, what would be the recommended way?

**Comment by Jeffail** [comment]
Hey @drurenia, this is actually possible without a broker because the kafka input adds metadata to messages describing the topic they came from: https://www.benthos.dev/docs/components/inputs/kafka#metadata, which you can use within Bloblang expressions of your switch output:

```yaml
kafka:
  addresses:
    - TODO
  topics:
    - "Topic A"
    - "Topic B"
  consumer_group: foo_group

output:
  switch:
    cases:
      - check: '(meta("kafka_topic") | "") == "Topic A"'
        output:
          sql: ...

      - output:
          sql: ...
```

But if you wanted to expand this concept to include more input types you can also add custom metadata for each input of a broker:

```yaml
input:
  broker:
    inputs:
    - kafka: ...
      processors:
        - bloblang: 'meta broker_input = "A"'
    - amqp_0_9: ...
      processors:
        - bloblang: 'meta broker_input = "B"'
```

**Comment by drurenia** [comment]
@Jeffail, thanks for the fast response. That is exactly what I needed. Thank you!

**Comment by drurenia** [comment]
@Jeffail , sorry for reopening this issue. But while trying to achieve the `switch` approach suggested by you, I diverged a little from the example you gave me and tried to use `resources` for each output. Example: 

```yaml
...
output:
  switch:
    cases:
      - check: '(meta("kafka_topic") | "") == "Topic A"'
        output:
           resource: output-resource-a
      - check: '(meta("kafka_topic") | "") == "Topic B"'
        output:
          resource: output-resource-b
```

Is this usage of resources allowed by Benthos?

N.B: I haven't included `output-resource-a` and `output-resource-b` resources for simplicity, but both of them work outside the switch context.
