### ISSUE TITLE
Messages not being dropped for HTTP code specified in drop_on

### ISSUE THREAD

**Issue by gcase555** [Jeffail/benthos#666]
Hello!

I believe we have found a bug but would appreciate some clarification if our configuration is doing what we want here.

We have a simple service that just uses benthos to pull messages from an SQS queue and sends them to a http service via `POST`, the sqs queue also has a deadletter queue for us to store messages as a backup in case we can't process them. 

Desired Behavior:
Our web service returns specific HTTP codes that indicate a message is 'bad' and we want that message to be dropped and NOT retried. According to the documentation https://www.benthos.dev/docs/components/outputs/http_client#drop_on we thought adding the `drop_on` attribute to our `output` would cause messages that receive this http code from our output would be dropped.

Current Behavior:
When a SQS message input is sent to our http service via the `http_client` and the service returns a `429` response code, the message gets put into the deadletter queue and does not get deleted.

Here is our benthos configuration:

``` yaml
http:
  address: 0.0.0.0:4195
  read_timeout: 5s
  root_path: /benthos
  debug_endpoints: false
input:
  type: broker
  broker:
    copies: 1
    inputs:
    - sqs:
        url: ${SQS_URL}
        region: ${SQS_REGION}
buffer:
  type: none
  none: {}
pipeline:
  threads: 1
  processors:
  - type: try
    try:
    - type: json
      json:
        operator: select
        path: payload
  - type: catch
    catch:
    - type: log
      log:
        level: ERROR
        message: "processor-error"
        fields:
          reason: "${!content:0}"
output:
  type: http_client
  http_client:
    drop_on:
    - 400
    - 409
    backoff_on:
    - 429
    basic_auth:
      enabled: false
    headers:
      Content-Type: application/json
    url: ${UPSTREAM_SERVICE_URL}
    verb: POST
logger:
  add_timestamp: true
  json_format: true
  level: INFO
  prefix: benthos
```

Question:
Shouldn't the SQS message get dropped when we use this configuration and NOT be sent to the deadletter queue since we indicated we wanted messages that get a http code `429` response to be dropped? Is this intended behavior or a bug with how the `drop_on` configuration works for the `http_client` component?

**Comment by Jeffail** [comment]
Hey @gcase555, the naming of these fields can be a bit confusing, the field name `drop_on` refers to the HTTP _request_ being dropped, i.e. "if we receive this status code then don't bother trying the HTTP request again, just fail immediately". However, when the request is dropped the _message_ is considered to have failed.

In your case you want to drop the message entirely, which is essentially the outcome that you would get when the request is successful. For that purpose you can use the field `successful_on`, which defines status codes whereby the request should be dropped and should also be considered "dealt with".

From your description it sounds as though the output config you need would be:

```yaml
output:
  type: http_client
  http_client:
    drop_on:
    - 400
    successful_on:
    - 409
    backoff_on:
    - 429
    basic_auth:
      enabled: false
    headers:
      Content-Type: application/json
    url: ${UPSTREAM_SERVICE_URL}
    verb: POST
```

I don't think you're the first to be mislead by the field docs, the description they have is technically correct but it could definitely be improved with some clarification. I also think it might be worth considering renaming them in V4.
