### ISSUE TITLE
Issues assigning metadata in bloblang to an environment variable

### ISSUE THREAD

**Issue by patrobinson** [Jeffail/benthos#672]
Trying to assign an environment variable to a metadata field in bloblang like so:

```
      meta imsometa = env("foo")
      this.meta = meta("imsometa")
```

This fails and we get an error:
```
{"@timestamp":"2021-02-18T16:19:57+11:00","@service":"benthos","level":"ERROR","component":"benthos.pipeline.processor.0","message":"failed to execute mapping query at line 2: metadata value 'imsometa' not found"}
```

Example pipeline:
```
input:
  http_server:
    path: /post
    timeout: 5s
pipeline:
  processors:
  - bloblang: |
      meta imsometa = env("foo")
      this.meta = meta("imsometa")
output:
  type: sync_response
```

**Comment by Jeffail** [comment]
Hey @patrobinson, this is actually a "feature" (albeit a potentially confusing one) where the metadata of the source message is read-only, similar to how the main document structure is. When you assign new metadata values you're adding them to the _new_ document, not the one you're referencing with `meta`.

If you want to assign values that you can also reference again later use variables, in your case it would be something like this:

```yaml
input:
  http_server:
    path: /post
    timeout: 5s
pipeline:
  processors:
  - bloblang: |
      let imsometa = env("foo")
      meta imsometa = $imsometa
      this.meta = $imsometa
output:
  type: sync_response
```

The documentation doesn't seem to mention any of this at all, which is surprising because it's definitely been asked about before.

**Comment by patrobinson** [comment]
That's very confusing 😆 

The actual use case I have is setting a metadata field to use in a later bloblang processor. I'd like to avoid polluting the record itself as it's tricky to strip it out.

```
  processors:
  - bloblang: |
      let imsometa = env("foo")
      meta imsometa = $imsometa
      root = this
  - bloblang: |
      this.meta = meta("imsometa")
```

This doesn't work but this does

```
  processors:
  - bloblang: |
      meta imsometa = "foo"
  - bloblang: |
      this.meta = meta("imsometa")
```

**Comment by Jeffail** [comment]
@patrobinson are you sure that the env var you're querying is populated? The mappings:

```yaml
  processors:
  - bloblang: |
      let imsometa = env("foo")
      meta imsometa = $imsometa
  - bloblang: |
      this.meta = meta("imsometa")
```

Should be fine, as well as:

```coffee
  processors:
  - bloblang: |
      meta imsometa = env("foo")
  - bloblang: |
      this.meta = meta("imsometa")
```
