### ISSUE TITLE
Support Bloblang in Tests

### ISSUE THREAD

**Issue by orsigiorgio** [Jeffail/benthos#681]
Hi @Jeffail it would be great if we could add support for Bloblang in the tests.

Something like this:

```
parallel: true
tests:
  - name: example test
    target_processors: '/pipeline/processors'
    environment: {}
    input_batch:
      - content: 'example content'
        metadata:
          example_key: example metadata value
    output_batches:
      -
        - processors:
           - bloblang: '<some blobbing>'
        - content_equals: example content
          metadata_equals:
            example_key: example metadata value
```
so that we could manipulate the output of a test before matching it to the condition.
