### ISSUE TITLE
http_server input processor path param

### ISSUE THREAD

**Issue by mallikvala** [Jeffail/benthos#691]
hey @Jeffail , trying to add a path parameter to `http_server` input processor, but not able to locate the incoming path parameter in either `meta` or `content` of the message.

### Config:
``` yaml
input:
  http_server:
    path: /{anotherParam}/{differentParam}/post
pipeline:
  processors:
    - bloblang: |
        root.meta = meta()
        root.this = this
output:
  type: sync_response
```

### Request:
``` sh
curl --location --request POST 'http://0.0.0.0:4195/xyz/abc/post?a=b' \
--header 'Content-Type: application/json' \
--data-raw '{
	"key":"value"
}'
```

### Response:

```json
{
    "meta": {
        "Accept": "*/*",
        "Cache-Control": "no-cache",
        "Connection": "keep-alive",
        "Content-Length": "18",
        "Content-Type": "application/json",
        "a": "b",
        "http_server_user_agent": "PostmanRuntime/7.25.0"
    },
    "this": {
        "key": "value"
    }
}
```

Are path params not supported?
