### ISSUE TITLE
Significant performance degradation with `aws_sqs` input compared with `sqs` input

### ISSUE THREAD

**Issue by codecrane** [Jeffail/benthos#694]
It looks like I am getting a significant performance degradation with the config below when I switch to the newer `aws_sqs` input. 

`sqs` input: 120 Messages Per Second, ~600 KB/s
`aws_sqs` input: 16 Messages Per Second, ~83 KB/s

Benthos/Container Version `jeffail/benthos:3.42`

```
    input:
      broker:
       copies: 1
       inputs:
         - sqs:
             url: "https://sqs.us-east-1.amazonaws.com/0000000000/example_ingest_queue"
             region: us-east-1

    metrics:
      cloudwatch:
        namespace: benthos
        path_mapping: |-
          meta namespace = "benthos"
          meta app = "example"
        region: us-east-1
    
    output:
      drop: {}
```

Thanks for Benthos and all it does!
