### ISSUE TITLE
Reject doesn't un-ack SQS messages

### ISSUE THREAD

**Issue by patrobinson** [Jeffail/benthos#697]
The Reject documentation states:
> For inputs that support propagating nacks upstream such as AMQP or NATS the message will be nacked.

I can't tell if SQS is supported or not, but based on looking at the code it behaves the same way as AMQP, in that if `Acknowledge` is called with an error, the message is Unacknowledged.

However this is not the behaviour we see in production. When a message is rejected, Benthos continuously tries to process it over and over again. We expect instead the message to stop being processed and unacknowledged.
This happens with just `reject` as the output and also in a switch with `retry_until_success` set to `false`

**Comment by Jeffail** [comment]
Hey @patrobinson, the Nack behaviour for the SQS inputs to set the visibility timeout to zero, which allows SQS to reroute the message according to your redrive policy (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html). Depending on how the queue is set up it's possible that the messages could be recirculating continuously.

If that's not the case then there's likely a component within Benthos that's forcing the retries, if you could share your config that'd help narrow it down.

**Comment by patrobinson** [comment]
Yes sorry I am using a redrive policy but we saw a message never reach the receive count to trigger it.

I managed to replicate this locally with a config like this:

```
input:
  s3:
    bucket: "${BUCKET}"
    sqs_url: "${SQS_URL}"
    sqs_body_path: Records.*.s3.object.key
    sqs_bucket_path: "${BUCKET}"
    region: "${AWS_REGION}"
    endpoint: "http://localstack:4566"
    force_path_style_urls: true
    download_manager:
      enabled: false
output:
  reject: "processing failed due to: ${! error() }"
```

**Comment by Jeffail** [comment]
Ah I see, I can take a look this evening but it might be a limitation with the `s3` input. However, there's a new refactored version called `aws_s3` which should have much better behaviour: https://www.benthos.dev/docs/components/inputs/aws_s3

The config is slightly different so the equivalent to your example would be:

```yaml
input:
  aws_s3:
    bucket: "${BUCKET}"
    region: "${AWS_REGION}"
    endpoint: "http://localstack:4566"
    force_path_style_urls: true
    codec: all-bytes
    sqs:
      url: "${SQS_URL}"
      key_path: Records.*.s3.object.key
      bucket_path: Records.*.s3.bucket.name
output:
  reject: "processing failed due to: ${! error() }"
```

Let me know if you get a chance to try that one out.
