### ISSUE TITLE
1s limit on reject output

### ISSUE THREAD

**Issue by iluminae** [Jeffail/benthos#704]
Hi there,
I have a config that I am using that is fairly high throughput using pubsub:
```yaml
input:
  gcp_pubsub:
    project: myproj
    subscription: mysubscription
    max_outstanding_messages: 40000
    batching:
      count: 500
      period: "5s"
processors:
- type: somethingThatMightFail
output:
  switch:
    retry_until_success: false
    cases:
    - check: errored()
      output:
        reject: |
          project=${! meta("projectId") } error=${! error() }
    - output:
        drop: {}
```
and sometimes my processor will error out (eg if the database it is talking to is down). When it does error, the error does correctly get applied to the parts and it will fall down into the reject output - but when this happens, I get _exactly_ 1 message/s throughput. I would _expect_ it to nack pubsub and continue along as fast as it can. Where is the 1s coming from here? Note it is still 1s even if I change/remove the batching from the input. I looked at the code for the reject output and its literally just return `errors.New()` so I assume it has something to do with errors propagating to inputs? I have reproduced this 1s limit in your WASM lab with the reject output.

Is there a better way I can be propagating these nacks while still performing the rest of my work as fast as I can?

Thanks!
