### ISSUE TITLE
http_client output not batching

### ISSUE THREAD

**Issue by patrobinson** [Jeffail/benthos#705]
Hi,

This bug is a little odd as it's been biting us a few times. Each time I've managed to fix it (first using the `split` processor, later using the output batching configuration), but now for some reason it seems completely broken.

It seems like the `http_client` output does not batch. This does not affect other outputs, probably because they don't support batches and are always sent individually.

Steps to replicate:
1. Run a fake webserver locally to capture the output `nc -l -p 8008`
2. Start Benthos with the following config
    ```yaml
    input:
      http_server:
        path: /post
        timeout: 5s
    pipeline:
      processors:
        - bloblang: root = this.Records
        - unarchive:
            format: json_array
    output:
      http_client:
        url: http://localhost:8008
        verb: POST
        batching:
          count: 1
          processors:
            - archive:
                format: lines
        headers:
          Content-Type: application/json
    ```
3. Send it some data `curl -sv -F 'foo={"Records":[{"foo":1},{"foo":2}]}' http://localhost:4195/post`
4. Observe the output from netcat
    ```bash
    09:33 $ nc -l -p 8008
    POST / HTTP/1.1
    Host: localhost:8008
    User-Agent: Go-http-client/1.1
    Content-Length: 19
    Content-Type: application/json
    Accept-Encoding: gzip

    {"foo":1}
    {"foo":2}
    ```

```
09:40 $ benthos --version
Version: 3.42.0
Date: 2021-02-22T21:07:33Z
```

**Comment by Jeffail** [comment]
Hey @patrobinson, is your intention to receive two individual HTTP requests, one for `{"foo":1}` and another for `{"foo":2}`?

**Comment by patrobinson** [comment]
@Jeffail yes

**Comment by Jeffail** [comment]
Okay in that case either:

```yaml
input:
  http_server:
    path: /post
    timeout: 5s
pipeline:
  processors:
    - bloblang: root = this.Records
    - unarchive:
        format: json_array
    - split: {}
output:
  http_client:
    url: http://localhost:8008
    verb: POST
    headers:
      Content-Type: application/json
```

Or:

```yaml
input:
  http_server:
    path: /post
    timeout: 5s
pipeline:
  processors:
    - bloblang: root = this.Records
    - unarchive:
        format: json_array
output:
  http_client:
    url: http://localhost:8008
    verb: POST
    headers:
      Content-Type: application/json
  processors:
    - split: {}
```

Should work, I imagine you've already tried:

```yaml
output:
  http_client:
    url: http://localhost:8008
    verb: POST
    batching:
      count: 1
      processors:
        - split: {}
    headers:
      Content-Type: application/json
```

Which won't work as you would expect because the `processors` associated with a batcher can't be used to break out a batch into individual messages. It's working as intended as those processors are meant to be used for compressing a batch into a single entity rather than expanding it out, but obviously that's not clear when it's being run and you're seeing the `split` processor basically being disregarded.

The first thing I can do is add warning logs when batch processors are used to expand into multiple messages, that'll at least make it clear what's happening.

The second annoyance here is that HTTP components use multipart encoding when they dispatch message batches, which at the time of development seemed like the most appropriate thing to do, but I think in reality it's rare that this is actually what developers want.

If instead this was a config field something like `batch_as_multipart` which is set `false` by default then this wouldn't even be an issue in the first place as you wouldn't need to `split` your batch out at all, you could just route them to the output and it would deliver them as individual requests by default.

I can add that `batch_as_multipart` field immediately, but it'll need to be `true` by default until v4 because it'd be a breaking change otherwise.

Does that summary fit your experience? I'm extrapolating based on other questions that have come up in the past.
