### ISSUE TITLE
Mongo output errors inside switch output type

### ISSUE THREAD

**Issue by ilyaglow** [Jeffail/benthos#708]
Hey there,

I tried to use v3.43.0-rc1 version's experimental mongodb output, but seems like it doesn't work with a switch output type.
Each routed record is followed with an error: 
```
{"@timestamp":"2021-03-22T15:25:52+03:00","@service":"benthos","component":"benthos.output.switch.0.output","level":"ERROR","message":"Failed to connect to mongodb: ping failed: context canceled"}
```

Maybe I miss something? The excerpt from yaml:
```yaml
output:
  switch:
    cases:
      - check: meta("route") == "mongo"
        output:
          mongodb:
            url: mongodb://127.0.0.1:27017
            operation: insert-one
            write_concern:
              w_timeout: 60s
            document_map: root = this
            username: ${USER}
            password: ${PASS}
            collection: ${COLL}
            database: test
      - output:
          stdout: {}
```

**Comment by Jeffail** [comment]
Hey @ilyaglow, your output config looks fine, can you give any information about your input?

**Comment by ilyaglow** [comment]
Turns out, this error shows only if case check is never met and input has been closed.

input.jsonl
```json
{"a":"b","bar":"foo"}
{"a":"c","bar":"12345"}
{"a":"d","bar":"0000"}
```

config.yaml:
```yaml
input:
  stdin: {}

pipeline:
  processors:
    - bloblang: |
        meta route = if this.bar.contains("foobar") { "mongo" } else { "stdout" }

output:
  switch:
    cases:
      - check: meta("route") == "mongo"
        output:
          mongodb:
            url: mongodb://127.0.0.1:27017
            operation: insert-one
            write_concern:
              w_timeout: 60s
            document_map: root = this
            username: ${USER}
            password: ${PASSWORD}
            collection: ${COLL}
            database: test
      - output:
          stdout: {}
```
