### ISSUE TITLE
Redpanda Kafka input error log

### ISSUE THREAD

**Issue by nmbryant** [Jeffail/benthos#711]
I setup an example Kafka to Kafka pipeline using docker compose to setup the Benthos containers and a Redpanda container for Kafka. I have been seeing the following error in the log, but the output topic is receiving the message so the Benthos pipeline seems to be working as intended. I don't see this error using the same pipeline and Kafka running locally, so I think it has something to do with Redpanda.

`{"@timestamp":"2021-03-24T13:19:29Z","@service":"benthos","component":"benthos.input","level":"ERROR","message":"Kafka group message recv error: kafka: error while consuming output-testing/0: kafka: insufficient data to decode packet, more bytes expected"}`

The pipeline does seem to be working as expected, so this error is mostly just confusing to see and not an issue with functionality.

**Comment by Jeffail** [comment]
Hey @nmbryant, I believe this is caused by the Sarama client library not ignoring some control messages coming from Redpanda. The fault is harmless and I believe they're working on coordinating with Sarama to get a fix out. I'll keep this open until we can verify the fix.

This might also be related to https://github.com/Shopify/sarama/issues/1888

**Comment by senior7515** [comment]
@nmbryant  - although we were spec'ed correctly - we added a simple counter/translator to https://github.com/vectorizedio/redpanda/pull/1228 - so this should be gone with `v21.4.15` (it *is* still a bug upstream) but you shouldn't see this in the logs. 

@Jeffail feel free to tag me and i'll try to help next time w/ redpanda issues :) - always happy to help benthos.

**Comment by chjdev** [comment]
Hi @Jeffail I've just ran into the same issue.

the data in the (redpanda) kafka topic looks completely normal and i can consume it fine via cli, however when i try consume from it using benthos i get the same error, however nothing is produced to the output:
```
{"@timestamp":"2021-11-18T08:58:55+01:00","@service":"benthos","component":"incoming","level":"ERROR","message":"Kafka group message recv error: kafka: error while consuming xxx/0: kafka: insufficient data to decode packet, more bytes expected"}
```

Here's the config I used to test it, which works fine for other topics:

```yaml
http:
  address: 0.0.0.0:4195
  read_timeout: 5s
  root_path: /benthos
  debug_endpoints: false

input:
  label: incoming
  kafka:
    addresses:
      - "some_broker:31572"
    tls:
      enabled: true
      root_cas_file: /path/to/redpanda/ca.crt
      client_certs:
        - cert_file: /path/to/redpanda/cluster.crt
          key_file: /path/to/redpanda/cluster.key
    sasl:
      mechanism: "SCRAM-SHA-256"
      user: "user"
      password: "password"
    topics: [ "some_topic" ]
    consumer_group: some_consumer_group
    client_id: some_client_id
    checkpoint_limit: 1

buffer:
  type: none
  none: {}

output:
  label: "output"
  stdout:
    codec: lines
```

The specific topic in question was produced via a [meterialize sink](https://materialize.com/docs/sql/create-sink/) which according to @senior7515 should work identically and is tested through integration tests on redpanda's side.

Any idea what might be going on here?

We're running
Benthos version: 3.58.0
Redpanda: v21.9.6
