### ISSUE TITLE
Redis List output cannot process batch messages from kafka

### ISSUE THREAD

**Issue by WaizungTaam** [Jeffail/benthos#713]
I have the following config:
```yaml
input:
  kafka:
    addresses:
      - localhost:9092
    topics:
      - benthos_test
    batching:
      count: 100
      period: 5s

pipeline:
  processors: []

output:
  redis_list:
    url: tcp://localhost:6379
    key: foo_out
    max_in_flight: 10

```
which shall read messages from kafka, and push them into the redis list.

However, when I run with this config (Benthos v3.42.0), and push like 500 messages into the kafka broker, the target redis list only receives 10 messages, and Benthos would just stall. And when I restart Benthos, another 10 messages are pushed into the redis list, and Benthos stalls again.

I have tried replacing the redis_list output with stdout, and everything works fine.

Is there something wrong with this config? Or maybe this is the expected behavior?

**Comment by Jeffail** [comment]
Hey @WaizungTaam, thanks for reporting this. It looks like this is a regression introduced in `v3.42.0` when using an output that publishes messages serially and the messages are batched. There's a mechanism that incorrectly triggers an internal shutdown which causes the stall to occur.

You can temporarily work around this by adding a split processor to break the batches out at the output level:

```yaml
output:
  redis_list:
    url: tcp://localhost:6379
    key: foo_out
    max_in_flight: 10
  processors:
    - split: {}
```

It's not ideal but I should be able to release a fix for this later today, I'm treating this as severe as it impacts a wide range of outputs.
