### ISSUE TITLE
Kafka (redpanda) topics broken when consuming specific partition

### ISSUE THREAD

**Issue by parisholley** [Jeffail/benthos#715]
`Mar 27 22:32:42 redpanda_east_0 rpk[1025740]: INFO  2021-03-27 22:32:42,228 [shard 1] kafka - connection_context.cc:134 - Detected error processing request: std::runtime_error (Unsupported version 0 for offset commit API)
Mar 27 22:32:42 redpanda_east_0 rpk[1025740]: INFO  2021-03-27 22:32:42,841 [shard 1] kafka - connection_context.cc:134 - Detected error processing request: std::runtime_error (Unsupported version 0 for offset fetch API)`

using the legacy syntax works fine:

```yaml
topics: events
partition:1
```

but new syntax throws above errors

```yaml
topics: [ events:1 ]
```

**Comment by parisholley** [comment]
actually, the issue may be related to batching... i have two topics i am monitoring, so I tried breaking up using the legacy syntax like so:

```yaml
input:
  broker:
    batching:
      period: 1s
    inputs:
      - kafka:
          partition: 1
          topic: alpha
          start_from_oldest: false

      - kafka:
          partition: 1
          topic: beta
          start_from_oldest: false
```

the above caused the same problem, but moving batching to input level fixed it:

```yaml
input:
  broker:
    inputs:
      - kafka:
          partition: 1
          topic: alpha
          start_from_oldest: false
          batching:
            period: 1s

      - kafka:
          partition: 1
          topic: beta
          start_from_oldest: false
          batching:
            period: 1s
```
