### ISSUE TITLE
Bloblang errors in 3.43.0 with paths containing dashes (-)

### ISSUE THREAD

**Issue by razor-x** [Jeffail/benthos#723]
1. Create this `config.yaml` and run with 

```sh
echo '{"Metadata":{"job-id":"abc"}}' | benthos -c config.yaml
```

```yaml
input:
  stdin:
    codec: lines

pipeline:
  processors:
    - bloblang: |
        root = this
        meta "a" = this.Metadata."job-id"
    - bloblang: |
        root = this
        meta "b" = json("Metadata.job-id")
    - bloblang: |
        root = this
        meta "c" = this.Metadata.job-id

logger:
  format: classic
```

2. On Benthos 3.42.1 this will succeed but on 3.43.0 it will fail. 
3. If you delete the last bloblang processor `c` from the config then it will work on both versions.

<img width="750" alt="image" src="https://user-images.githubusercontent.com/721372/113520107-b95b9100-9545-11eb-9941-6151f974680b.png">
<img width="671" alt="image" src="https://user-images.githubusercontent.com/721372/113520120-cb3d3400-9545-11eb-9667-7408e3df50a3.png">
