### ISSUE TITLE
File input stuck on empty directory

### ISSUE THREAD

**Issue by hofmannnz** [Jeffail/benthos#725]
Hi,
I want to watch a directory for '*.txt' files and if there are any, process and delete them.
For this I use the read_until (to restart the input) in combination with the file input:
```
...
input:
  read_until:
    check: false
    restart_input: true
    input:
      type: file
      file:
        paths: ['./data/*.txt']
        codec: lines
        delete_on_finish: true
...
```
When I start benthos with the above (shortened) config and the './data' directory exists but is empty, I get the following errors (somewhat expectedly):
`
Failed to connect to file: open ./data/*.txt: no such file or directory
`
However if I then copy some txt file(s) to the './data' directory (with benthos still running), benthos does not pick them up but keeps sending the above message.

My expectation was that benthos should notice the new file and process them according to the pipeline.
Is there a configuration that I'm missing or any other way I can achieve this?
