### ISSUE TITLE
Unable to use benthos test to verify condition when no output is expected

### ISSUE THREAD

**Issue by davidshrive** [Jeffail/benthos#726]
I added some config to my pipelines to catch invalid json messages and was attempting to verify this with a benthos tests. Unfortunately the test always fails. 

```
---
tests:
  - name: valid json test - non json payload dropped
    target_processors: ../../main.yaml#/pipeline/processors
    input_batch:
      - content: "Invalid Json"
```

```
Test 'tests/main/neg_invalid_payload_dropped.yaml' failed
Failures:
--- tests/main/neg_invalid_payload_dropped.yaml ---
valid json test - non json payload dropped [line 3]:
processors resulted in zero output batches
```

**Comment by Jeffail** [comment]
Hey @davidshrive, this is because an example test case is being implicitly parsed when the `output_batches` field is omitted. A short term work around is to define an empty array explicitly with:

```yaml
---
tests:
  - name: valid json test - non json payload dropped
    target_processors: ../../main.yaml#/pipeline/processors
    input_batch:
      - content: "Invalid Json"
    output_batches: []
```

But having implicit test cases is definitely not a desired behaviour so I'll remove them for the next release. This could be considered a "breaking" change, but this is extremely unlikely to be a featured that is relied upon and since this is functionality for unit test execution it is by its own nature covered by tests.
