### ISSUE TITLE
Kafka input not auto-commiting

### ISSUE THREAD

**Issue by WaizungTaam** [Jeffail/benthos#736]
Just upgraded benthos from v3.42.1 to v3.44.0，and when I use kafka as the input, the messages are not commited at all. Here is the config file:
```yaml
input:
  kafka:
    addresses:
      - 127.0.0.1:9092
    topics:
      - benthos_test

pipeline: []

output:
  type: stdout

```
When I restart benthos, all the messages will be delivered again.

I have noticed that v3.43.0 increased the offset commit API of kafka input, and have turned off the `AutoCommit.Enable`. Wonder if there a way to turn auto-commit on?
