### ISSUE TITLE
Please explain how to properly propagate validations errors

### ISSUE THREAD

**Issue by wirtsi** [Jeffail/benthos#740]
Hi

I am trying to build a small http_server that receives JSON data, validates it and a) if validation passes proxies it on to another endpoint. b) if validation fails returns the error and doesn't proxy

```
http:
  enabled: true
  address: 0.0.0.0:4195
  root_path: /
input:
  broker:
    inputs:
      - label: "basket"
        http_server:
          path: /basket
          allowed_verbs:
            - POST
          sync_response:
            headers:
              Content-Type: "application/json"
            status: '${! meta("status_code") }'
pipeline:
  processors:
  - bloblang: |
      meta status_code = "200"
  - switch:
    - check: meta("http_server_request_path") == "/basket"
      processors:
      - json_schema:
            schema_path: "file://./basket.schema.json"
      - catch:
        - log:
            level: ERROR
            message: "Schema validation failed due to: ${!error()}"
        - bloblang: |
            meta status_code = "400"
            root.error = error()
output:
  switch:
    # retry_until_success: false
    cases:
      - check: '!this.exists("error")'
        output:
          http_client:
            url: http://localhost:4195/post
            verb: POST
            rate_limit: ""
            timeout: '5s'
            propagate_response: true
      - output:
          sync_response: {}
```
Now what is weird that
* If I do a request with invalid JSON data it works. Output is
`{"config":{},"error":"(root) sku is required"}
`
* If I do a request with valid data it runs into the http_client output (which fails because the endpoint doesn't exist). Response status is 408

* Now what throws me off is that from **now on** also requests with invalid JSON give me response status 408 and don't seem to be caught by the json_schema validator

Uncommenting the retry_until_success fixes this .. but still, I don't understand this behavior? Anyone got any clues?

Thnx

**Comment by Jeffail** [comment]
Hey @wirtsi, the `propagate_response` field in the `http_client` output doesn't cover when the request fails, as Benthos will still assume that the payload needs to be delivered and cannot be dropped.

When `retry_until_success` is set to `true` (the default), what will happen is because the `http_client` failed the request will be made continuously until success, which never occurs. On the `http_server` end eventually you'll receive a 408 timeout because there's a global `read_timeout` setting that defaults to 5 seconds (https://www.benthos.dev/docs/components/http/about). New requests coming in will also trigger a 408 since the original message is now blocking the pipeline.

When you set `retry_until_success` to `false` the `switch` output will no longer retry the request indefinitely, so when `http_client` fails the error will be immediately returned back to the `http_server` level and the pipeline will be unblocked, so the next request will also go straight through.

You can either set `retry_until_success` to `false` and allow the `http_client` output to set the error returned by `http_server`. Or, alternatively you can configure a fallback output to `http_client` that will set a custom error response using a `try` broker:

```yaml
http:
  enabled: true
  address: 0.0.0.0:4195
  root_path: /
input:
  broker:
    inputs:
      - label: "basket"
        http_server:
          path: /basket
          allowed_verbs:
            - POST
          sync_response:
            headers:
              Content-Type: "application/json"
            status: '${! meta("status_code") }'
pipeline:
  processors:
  - bloblang: |
      meta status_code = "200"
  - switch:
    - check: meta("http_server_request_path") == "/basket"
      processors:
      - json_schema:
          schema_path: "file://./basket.schema.json"
      - catch:
        - log:
            level: ERROR
            message: "Schema validation failed due to: ${!error()}"
        - bloblang: |
            meta status_code = "400"
            root.error = error()
output:
  switch:
    # retry_until_success: false
    cases:
      - check: '!this.exists("error")'
        output:
          try:
            - http_client:
                url: http://localhost:4195/post
                verb: POST
                rate_limit: ""
                timeout: '5s'
                propagate_response: true
            - sync_response: {}
              processors:
                - bloblang: |
                    meta status_code = "400"
                    root.error = "endpoint was unavailable"
      - output:
          sync_response: {}
```

**Comment by wirtsi** [comment]
@Jeffail wicked, thank you very much. If you get it explained as nicely as you did, it all terribly makes sense.
What worked for me (other than retry_until_success) was

```
output:
  switch:
    cases:
      - check: '!this.exists("error")'
        output:
          try:
          - http_client:
              url: http://localhost:4195/post
              verb: POST
              rate_limit: ""
              timeout: '5s'
              propagate_response: true
              copy_response_headers: true
          - type: sync_response # if previous call fails, this is triggered
            processors:
            - bloblang: |
                meta status_code = "400"
                root.error = "Upstream error"
      - output: # flush validation errors back to http_server
          sync_response: {}

```
Got a bit caught why it has to be type: sync_response (and not just sync_response) ... but it works like that, excellent

Thnx again & have a nice weekend

**Comment by wirtsi** [comment]
One last thing

> New requests coming in will also trigger a 408 since the original message is now blocking the pipeline.

So this means that (in the default setting) any time an upstream system barfs the http_server will fail because the pipeline is blocked?

**Comment by Jeffail** [comment]
Yeah part of Benthos delivery guarantees is that messages that cannot be routed due to downstream being unavailable, and also cannot be nacked upstream, will continue to be retried until successful. Therefore in order to prevent more messages from coming in and flooding the memory of the server that also means back pressure must be applied and the input must stop pushing new messages through the system.

However, the `http_server` input does support nacks (by responding with an error code), so in normal operation this back pressure mechanism wouldn't kick in. In your case though the back pressure is because you're using a `switch` output, and that field `retry_until_success` is designed to retry an individual output indefinitely because the same message might've been routed already to another output, so it's a convenient way of preventing duplicate messages when one of the outputs is failing.

**Comment by wirtsi** [comment]
Interesting, wouldn't have thought that this is caused by the switch statement here.

It took me a while to figure out how to "abort" a pipeline in case of validation errors

```
pipeline:
  processors:
  - bloblang: |
      meta status_code = "200"
  - switch:
    - check: meta("http_server_request_path") == "/basket"
      processors:
      - json_schema:
            schema_path: "file://./basket.schema.json"
      - catch:
        - log:
            level: ERROR
            message: "Schema validation failed due to: ${!error()}"
        - bloblang: |
            meta status_code = "400"
            root.error = error()
        - type: sync_response # send back response to http_server
        - bloblang: | # remove data so there is no ouput in case of errors
            root = deleted()
```
This works and is much nicer as I don't have to worry about handling validation errors in the output part of the flow

Thanks again for your help @Jeffail !
