### ISSUE TITLE
Readiness probe fails when using custom inputs with dynamic inputs

### ISSUE THREAD

**Issue by eduardodbr** [Jeffail/benthos#751]
I'm using custom inputs that are configured using dynamic inputs. The inputs work  but then the readiness probe fails with "input not connected". I changed my custom input code to be exactly like this one: https://github.com/benthosdev/benthos-plugin-example/blob/master/input/gibberish.go and the readiness probe keeps failing.

**Comment by Jeffail** [comment]
Hey @eduardodbr, does the readiness probe fail when your config is static like this:

```yaml
input:
  dynamic:
    foo:
      type: yourthing
      plugin: ...
```

And are there any other significant aspects on the config? Like processors or the input being wrapped within another input?

I had a quick poke around and with a dynamic input the connected probe is actually always `true` https://github.com/Jeffail/benthos/blob/master/lib/broker/dynamic_fan_in.go#L123 so this is likely caused by something else in the config.

**Comment by eduardodbr** [comment]
This is my input:

```
input:
  broker:
    inputs:
      - dynamic:
          inputs: {}
          prefix: ""
          timeout: 5s
      - generate:
          mapping: root = {"url":"init"}
          count: 1
```

I thought it was caused by the dynamic input but the problem is caused by the `generate` input. While dynamic inputs are streaming data, the generate input only generates one message and closes, making the readiness probe to fail. Is this expected behavior?
