### ISSUE TITLE
Add Elasticsearch as input

### ISSUE THREAD

**Issue by aksdb** [Jeffail/benthos#764]
## Why?

Elasticsearch is also a pretty data lake. Reading from it to write into other systems can be totally worth it.
Furthermore there are usecases where you need to re-index (while manipulate) data which cannot be done within Elasticsearch, so you need to read from it and write to it again. Or you might want to migrate data from one Elasticsearch instance to another, while performing processing/filtering on it.

## How?

Elasticsearch supports [scroll](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#scroll-search-results) and [search_after](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after) which can be used to traverse large responses (like .... everything from an index or alias).

## Sub-Features

The following settings should (at least) be allowed to pass to the input:

* **Index** (required)
  Name/pattern of the index/indices/aliases to fetch data from.
* **Query** (optional)
  Passes the (JSON) query to the body of the search request. Allows complex Elasticsearch queries.
* **SimpleQuery** (optional)
  Passes the simple lucene style query as `?q=....` parameter to the search request. Allows simple lucene style filtering.
* **Sort** (optional)
  Allows defining a sort order for the data to be processed. Not recommended for large data processing (since it puts a lot of pressure on Elasticsearch), but there are usecases where it's relevant. For example if you want to pipe the data in chronological order (back) into a message broker.

Furthermore it would be nice to be able to access metadata fields returned in the individual `hits` - most importantly the `_index`. That way you can query from an alias spanning multiple indices, manipulate a document, and put it back into the source index (thereby overwriting the initial document).

**Comment by Jeffail** [comment]
Hey @aksdb, I love it, thanks for the well written spec. Another thing we could maybe add later is the ability to use a cache to persist the current position of the iterator (if it's possible to do so).

**Comment by aksdb** [comment]
> Another thing we could maybe add later is the ability to use a cache to persist the current position of the iterator (if it's possible to do so).

That could be problematic, depending on the specific implementation. The deprecated scroll API and the now apparently recommended `search_after` API work with a time limited snapshot. In case of `search_after` it is recommended to use the Point-In-Time API to get a snapshot. This assures that subsequent requests operate on the same state of the database (thereby avoiding that data suddenly is in a different sort order due to changes happening while you iterate over them). You then pass the ID of the Point-In-Time (or in case of the `scroll` API the ID of the cursor) to the next call together with a duration you want the cursor/point-in-time to be extended. Under normal circumstances you would probably use a short duration (like 1 minute) so you have enough time to sift through the next page and then extend it by another minute when you fetch the next, and so on.
I assume you could pass a pretty long time as well, but this will likely negatively impact Elasticsearch (since it somewhere has to keep the old state).

But maybe, in cases where you know your sort order is stable (for example when scrolling through time based events, you can be certain that nothing will suddenly appear in the past), an option might be nice to _not_ use the cursor/point-in-time. Then it would be possible to just cache the last key (which is passed to `search_after`) and use it later, even if a lot of time goes by.

**Comment by jem-davies** [comment]
Potentially one I could pick up.

**Comment by ossie-git** [comment]
@jem-davies Were you able to make any progress on this? Thanks

**Comment by jem-davies** [comment]
> @jem-davies Were you able to make any progress on this? Thanks

No I didn't unfortunately...

**Comment by artemklevtsov** [comment]
Template may be solution.

Example:

`elastic_search.yaml`:

```yaml
name: elastic_search
type: input
description: Чтение данных индекса из Elastic Search

fields:
  - name: url
    type: string
    default: http://elastic.domain.example:9200
  - name: index
    type: string
  - name: query
    type: bloblang
  - name: cache
    type: string
  - name: rate_limit
    type: string

mapping: |
  import "benthos/templates/elastic_search.blobl"
  root = this.apply("input")
```

`elastic_search.blobl`:

```js
map input {
  root.generate.count = 0
  root.generate.interval = "0s"
  root.generate.mapping = null.bloblang(this.query).string()
  root.processors = this.apply("input_processors")
}

map cache_key {
  root = "elastic_search_" + this.query.hash("sha1").encode("hex")
}

map input_processors {
  root = []
  root."-" = this.apply("search_after")
  root."-" = this.apply("log_query")
  root."-" = this.apply("fetch")
  root."-" = this.apply("cache_set")
  root."-".mapping = """
    root = this.hits.hits.or([])
  """
  root."-" = this.apply("sleep")
  root."-".unarchive.format = "json_array"
  root."-".mapping = """
    meta index = this._index
    meta id = this._id
    meta type = this._type
    root = match {
      this.exists("_source") => this._source
      this.exists("fields") => this.fields
    }
  """
}

map log_query {
  root.log.level = "debug"
  root.log.message = "fetch API"
  root.log.fields_mapping = """
    root.offset = this.search_after.or([])
    root.page = counter()
  """
}

map sleep {
  root.switch = []
  root."0".check = "this.length() == 0"
  root."0".processors = []
  root."0".processors."-".sleep.duration = "10s"
}

map cache_set {
  root.cache.resource = this.cache
  root.cache.operator = "set"
  root.cache.key = this.apply("cache_key")
  root.cache.value = "${! this.hits.hits.index(-1).sort.or([]) }"
}

map cache_get {
  root.cache.resource = this.cache
  root.cache.operator = "get"
  root.cache.key = this.apply("cache_key")
}

map fetch {
  root.http.url = "%s/%s*/_search".format(this.url, this.index)
  root.http.verb = "POST"
  root.http.timeout = "60s"
  root.http.headers."Content-Type" = "application/json"
  # root.http.dump_request_log_level = "debug"
  if this.rate_limit != "" {
    root.http.rate_limit = this.rate_limit
  }
}

map search_after {
  root.branch.processors = []
  root.branch.processors."-" = this.apply("cache_get")
  root.branch.result_map = """
    if !errored() {
      meta elastic_offset = this
      root.search_after = this
    }
  """
}
```

`config.yaml`:

```yaml
rate_limit_resources:
  - label: elastic_limit
    local:
      count: 1
      interval: 1s

cache_resources:
  - label: offset_cache
    sql:
      driver: sqlite
      dsn: cache.db
      table: benthos_cache
      key_column: id
      value_column: data
      init_statement: |
        CREATE TABLE IF NOT EXISTS benthos_cache (
          id text,
          data blob,
          PRIMARY KEY (id)
        );
      set_suffix: ON CONFLICT ( id ) DO UPDATE SET data = excluded.data

logger:
  level: debug

input:
  elastic_search:
    url: http://elastic.domain.example:9200
    index: 1c-graylog
    cache: offset_cache
    rate_limit: elastic_limit
    query: |
      #!blobl
      root.size = 1000
      root.sort = [
        { "timestamp": "asc" },
        { "connectID": "asc" },
      ]
      root.query = {
        "bool": {
          "filter": [
            { "term": { "streams": "6351401251da434ee875fc7a" } },
            { "term": { "onecbase": "tb" } },
            { "exists": { "field": "login" } },
            { "exists": { "field": "operation" } },
          ],
          "must_not": [
            { "terms": { "operation": [ "HealthCheck", "AddToApiLog" ] } }
          ],
        }
      }
      root._source = [
        "timestamp",
        "login",
        "azp",
        "operation",
        "success",
        "client",
      ]

output:
  stdout: {}
```

Run:

```sh
redpanda-connect -t "benthos/templates/*.yaml" benthos/config.yaml
```
