### ISSUE TITLE
Add proper argument typing to `sql` components

### ISSUE THREAD

**Issue by geekboood** [Jeffail/benthos#782]
Hi, I found that in the sql plugin, it converts all data to string and then exec the sql query. However, for clickhouse it will report an error. Do you think it is possible to fix this issue?

**Comment by Jeffail** [comment]
Hey @geekboood, unfortunately it looks as though the clickhouse drivers aren't coercing to the correct types during inserts, I've tried a few things out but I also can't find a way of explicitly expressing within an insert query the intent to convert to the correct type.

However, there's a rough plan to improve the `sql` processor and output so that arguments can be typed in your argument mappings, which would bypass this problem. I'll update this issue to cover the new functionality.

**Comment by Jeffail** [comment]
Done: https://github.com/Jeffail/benthos/commit/e57a26254590c4ecc0925d233c1f5237ac5a6665, I've implemented this as a bloblang mapping field which now looks like this:

```yaml
output:
  sql:
    driver: mysql
    data_source_name: foouser:foopassword@tcp(localhost:3306)/foodb
    query: "INSERT INTO footable (foo, bar, baz) VALUES (?, ?, ?);"
    args_mapping: '[ this.document.foo, this.document.bar, meta("kafka_topic") ]'
```
