### ISSUE TITLE
Special character encoding does not seem to be working in version 3.43.0 and higher

### ISSUE THREAD

**Issue by ichiong** [Jeffail/benthos#796]
I have a config that consumes data in JSON format from a Kafka topic and I'm trying to use bloblang methods to process my data for metrics purposes.

Here is my sample JSON data:

```
{
  "application": "awesomeapp",
  "type": "api",
  "metadata": {
    "event.type": "error",
    "event.action": "create_new_content",
    "http.method": "POST",
    "http.status_code": "503",
    "site.url": "http://www.someurl.com"
  }
}
```

According to your documentation [here](https://www.benthos.dev/docs/configuration/field_paths), the `~` and `.` characters have a special meaning in Benthos paths, so we have to encode these characters as `~0` and `~1` when these special characters appear within a key.

However, it seems like with versions 3.43.0 and higher, benthos doesn't seem to recognize these encoded characters. I keep getting lint errors that is preventing me from running my benthos app.

Here is my sample config:

```
input:
  kafka:
    addresses:
      - kafka:9092
    topics:
      - my-topic
    consumer_group: my_consumer_group
    client_id: my_consumer_group
    start_from_oldest: false

pipeline:
  processors:
    - switch:
      - check: this.metadata.event~1type == "error"
        processors:
          - bloblang: |
              root.app = this.application
              root.type = this.type
              root.event_type = this.metadata.event~1type
              root.event_action = this.metadata.event~1action
              root.http_method = this.metadata.http~1method
              root.http_status_code = this.metadata.http~1status_code
              root.url = this.metadata.site~1.url
          - metric:
              type: counter
              name: my_metrics
              labels:
                application: ${! json("app") }
                type: ${! json("type") }
                event_type: ${! json("event_type") }
                event_action: ${! json("event_action") }
                http_method: ${! json("http_method") }
                http_status_code: ${! json("http_status_code") }
                url: ${! json("url") }
      - processors:
          - bloblang: root = deleted()

output:
  drop: {}

metrics:
  influxdb:
    url: http://localhost:8086
    db: metrics
    interval: 30s
```

Here is the output when I run benthos (v3.43.0) to check for linting errors:

```
$ benthos lint config.yml 
config.yml: line 15: line 1 char 20: expected whitespace
  |
1 | this.metadata.event~1type == "error"
  |                    ^---
config.yml: line 19: line 3 char 38: expected line break
  |
3 | root.event_type = this.metadata.event~1type
  |                                      ^---
```

With benthos (v3.42.1), I get no linting errors at all.

Not sure if this is related, but looking through some of the previous commits in this repo in trying to understand what changed from v3.42.1 and v3.43.0, one of the commits that caught my attention was: [`ce25372`](https://github.com/Jeffail/benthos/commit/ce25372905969c4a94630fe53c6747513ce147a0#diff-2935de6f1d3223b3a3fc4cb6f1fbb4f510b8a60513cfa9b385820c3553a06400)

It looks like there were some special characters that got removed for some of the bloblang parser files.

Is the documentation outdated? Are we supposed to query special characters within keys in a new, different way?
