### ISSUE TITLE
Switch output type

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#81]
The idea would be to create an output type that selects the first of a list of outputs where a condition passes. The config spec might look something like this:

``` yaml
type: switch
switch:
- output:
    type: foo
    foo: {}
  condition:
    type: foo
    foo: {}
- output:
    type: bar
    bar: {}
  condition:
    type: bar
    bar: {}
```

**Comment by cludden** [comment]
I like this approach and would be happy to refactor. In light of the change, I'm wondering if the `first_match` config field should be changed to `fallthrough`?

**Comment by cludden** [comment]
also, i would be in favor of making the `switch` output configuration an object in case future use cases require extending the configuration

```yaml
type: switch
switch:
  outputs:
  - output:
      type: foo
      foo: {}
    condition:
      type: foo
      foo: {}
    fallthrough: true
  - output:
      type: bar
      bar: {}
    condition:
      type: bar
      bar: {}
```
