### ISSUE TITLE
Feature: Add compaction_on_read option for memory cache

### ISSUE THREAD

**Issue by hjblom** [Jeffail/benthos#812]
I am busy with a flow where I am required to renew credentials every 15 minutes.

My current approach is to run a processor pipeline on every request, atempting to read from memory, and if the key does not exist, to renew credentials.

```yaml
pipeline:
  processors:
    - resource: get_memory_auth
    - catch:
        - resource: "do_auth_"
        - resource: "set_memory_auth"
        - resource: "get_memory_auth"
```

After reading the documentation more closely, I noticed that compaction only happens on writes, and not reads.

To solve this problem, I would like to add an optional argument `compaction_on_read` to allow for compaction to also happen on read events. This does not break backwards compatibility. The new default memory cache config will then look like this:

```yaml
memory:
  ttl: 300
  compaction_interval: "60s"
  compaction_on_read: false
  init_values: {}
  shards: 1
```

If you are happy with the feature request, I am more than happy to implement it.
