### ISSUE TITLE
Retrieve value from json array element and copy it to the rest of the array

### ISSUE THREAD

**Issue by ericforte** [Jeffail/benthos#828]
Given this JSON array:

[
   {
      "a": "blue",
      "b": "red",
      "c": "green"
   },
   {
      "x": "foo",
      "y": "baz"
   },
   {
      "q": "quux",
      "r": "yaaar"
   }
]

I'm struggling with being able to take the value of "a" (blue) and add that value to the other elements as well, ideally renaming the original, ending up with this:

[
   {
      "Color": "blue",
      "b": "red",
      "c": "green"
   },
   {
      "Color": "blue",
      "x": "foo",
      "y": "baz"
   },
   {
      "Color": "blue",
      "q": "quux",
      "r": "yaaar"
   }
]

I've been playing with Benthos less than a month and having a blast!

**Comment by Jeffail** [comment]
Hey @ericforte, if I've understood correctly then something like this could work as a bloblang mapping:

```yaml
pipeline:
  processors:
    bloblang: |
      let color = this.0.a
      root = this.map_each(ele -> ele.merge({"Color":$color}).without("a"))
```
