### ISSUE TITLE
proposal: refactor conditions to support operator configuration

### ISSUE THREAD

**Issue by cludden** [Jeffail/benthos#84]
I am working on adding additonal operators to both the `metadata` and `jmespath` (which currently does not support operators) conditions. One of my use cases is to match against a long list of enumerations (to go along with the switch output). It currently feels awkward to force config for an `enum` operator into the string `arg` field. I'm proposing changing the way condition configuration is currently implemented to mirror the configuration structure of other benthos components (namely inputs, outputs, and processors). Below is an example to illustrate the proposal:

change this:
```yaml
condition:
  type: metadata
  metadata:
    operator: less_than
    key: foo
    part: 0
    arg: "3"
```

to this:
```yaml
condition:
  type: metadata
  metadata:
    operator: less_than
    key: foo
    part: 0
    less_than: 3
```

The difference may seem subtle, but is better illustrated with more complex (hypothetical) operators:

```yaml
condition:
  type: metadata
  metadata:
    operator: enum
    key: foo
    part: 0
    enum:
      - "a"
      - "very, long"
      - "list"
      - "of"
      - "values!"
```

or

```yaml
condition:
  type: jmespath
  jmespath:
    operator: json_schema
    query: foo
    part: 0
    json_schema:
      type: object
      properties:
        bar:
          type: string
          pattern: date-time
        baz:
          type: integer
          minimum: 5
          exclusiveMinimum: true
        qux:
          type: array
          uniqueItems: true
          items:
            type: string
            enum: ["quux","quz","corge"]
      required:
        - bar
        - baz
```

We could maintain backwards compatibility by continuing to support the `arg` field for existing operators. @Jeffail what are your thoughts?

**Comment by Jeffail** [comment]
Hey @cludden, I'm open to it but would be worried about the rate at which the config spec might grow as we add more operators. As an alternative suggestion, what if we changed the type of `arg` to be an `interface{}`?

Also for the example of adding a `json_schema` operator to `jmespath` I think it might be more generally useful to have something similar to the `process_field` processor for conditions, maybe called something like `check_field`, where the config might look something like this:

``` yaml
condition:
  type: check_field
  check_field:
    path: foo
    conditions:
    - type: json_schema
      json_schema:
        type: object
        ... etc ...
```

That way we could recycle it for doing things like `text` conditions on a JSON field.
