### ISSUE TITLE
String escaped with `tls.root_cas`

### ISSUE THREAD

**Issue by ar3s3ru** [Jeffail/benthos#840]
Opening an issue after #839 

I added some logging for the `tls.Config.RootCAs` field in the `tls.Config.Get()`, and turns out the string contains spaces where newlines should be.

Any ideas @Jeffail?

**Comment by Jeffail** [comment]
Okay so I did a bit of playing around and we need to do some nasty biz but I think it should be solvable. The issue is that you can have raw newlines in the env var but when it gets replaced into YAML it's just a dumb swap out, so you have several options, none of which will work with raw line breaks.

If we have an env var `FOOBAR` containing something like:

```
foo
bar
```

Then this is the result of various YAML configs:

```yaml
test: ${FOOBAR}

# Results in:
test: foo
bar

# Which is broken YAML
```

```yaml
test: "${FOOBAR}"

# Results in:
test: "foo 
bar"

# The newlines within a double quote string are replaced with a space, which isn't what we want (also what you're seeing)
```

```yaml
test: |
  ${FOOBAR}

# Results in:
test: |
  foo 
bar

# Which is broken YAML
```

If you escape the newlines then it should work as long as you use double quotes, i.e. `FOOBAR="foo\nbar"` with a config `test: "${FOOBAR}"` should work. There's probably a unix-fu for escaping newlines, but that's kind of awkward from a user stand point.

However, the good news is that since unescaped newlines in env variables has _never_ been viable we change the behaviour within Benthos and it's not going to break anything for anyone else (I think).

The quick and easy option would be to escape non-escaped newlines in the value, so if you double quote it then you'll get the newlines in the actual value, so:

```yaml
test: "${FOOBAR}"

# Results in:
test: "foo\nbar"
```

I should be able to do that.
