### ISSUE TITLE
Interpolation in http_client and reconnects

### ISSUE THREAD

**Issue by tetsuo** [Jeffail/benthos#844]
I'm piping a CouchDB [changes feed](https://docs.couchdb.org/en/stable/api/database/changes.html) to Benthos in streaming mode.

```
input:
  label: ""
  http_client:
    url: http://localhost:5984/example/_changes?feed=continuous&timeout=2500${! ("&since="+meta("last_seq")) | "" }
    verb: GET
    stream:
      enabled: true
      reconnect: true
      codec: lines
  processors:
    - bloblang: |
        meta last_seq = this.last_seq
```

`timeout` parameter is used for closing a connection if no data is sent for the given milliseconds.

When CouchDB closes the connection it sends one final JSON row which looks like this:

```
{"last_seq":"172-g1AAAACLeJzLYWBgYMpgTmHgzcvPy09JdcjLz8gvLskBCScyJNX___8_K4M5MTgXKMBubGpoaZGYiq4Yh_Y8FiDJ0ACk_kNNiQSbYmBubmpunIyuJwsAZrcq1g","pending":0}
```

The configuration above doesn't seem to work unfortunately. Is it possible to use this `last_seq` value in the`url` parameter? that way I can dynamically set the cursor between reconnects.
