### ISSUE TITLE
Add support to external configurations (Consul, Vault, etc)

### ISSUE THREAD

**Issue by lucasoares** [Jeffail/benthos#851]
Hey!

Big enterprise companies don't rely their configurations on just environment variables.

Would be nice to have something like this:

```yaml
config:
  vault:
    host: ${VAULT_HOST}
    provider: kubernetes
    role: ${VAULT_ROLE}
    service_account_path: ${KUBERNETES_SERVICE_ACCOUNT_PATH}
    keys: /my-app/**
  consul:
    host: ${CONSUL_HOST}
    token: ${consul.token}   # loaded from vault
    keys: /my-app/**

pipeline:
  processors:
    http:
      url: ${properties.from.vault.or.consul}
```

This what my company uses, for example. We prefer storing secrets inside vault instead of kubernetes secrets. The same applies to configs using consul instead of kubernetes config maps.

A nice golang library to deal with configurations is https://github.com/spf13/viper which support to multiple formats (yaml, json, etc) and multi-level configs (get from provider X, if not found get from env X)

They currently don't have support to vault but it can be easily extended to support any provider: https://github.com/spf13/viper/pull/497 https://github.com/spf13/viper/pull/497#issuecomment-613580303

Would be nice to have pipelines configured with dynamic external configuration. Restart and not rebuild/redeploy is the new thing haha

Thanks
