### ISSUE TITLE
New `check_field` condition type

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#88]
It would be useful to have a new `check_field` condition that would work similarly to the `process_field` processor: https://github.com/Jeffail/benthos/tree/master/docs/processors#process_field

The idea is that sometimes we want to resolve a condition on an extracted section of a message. For example, we might want to perform a `text` based `contains` operator on the JSON path `foo.bar` of a message. This would currently require us to do something like copy the value of `foo.bar` into a metadata field and then use a metadata condition instead.

What I'm proposing is we instead have a general `check_field` condition that allows you to reduce the contents of a message before performing a child condition, the boolean result is then returned and the original contents are left unchanged. The config might look like this:

``` yaml
condition:
  type: check_field
  check_field:
    parts: []
    path: foo.bar
    condition:
      type: text
      part: 0
      operator: contains
      arg: foobar
```

In this case `parts` would be used similar to processors, where if it's left empty then the reduction is applied to all message parts. Like all other components this would mean users may still distinguish message parts of a batch by their index if they need to, but others can simply ignore those fields and they behave as expected.
