### ISSUE TITLE
Bulk INSERT for batched SQL output

### ISSUE THREAD

**Issue by wearpants** [Jeffail/benthos#888]
It would be helpful and a major performance win for some databases to stuff the multiple rows in a batch into a single SQL statement, instead of the current approach of executing the same statement multiple times.

This is standard SQL:
```
INSERT INTO conditions
  VALUES
    (NOW(), 'office', 70.0, 50.0),
    (NOW(), 'basement', 66.5, 60.0),
    (NOW(), 'garage', 77.0, 65.2);
```
via https://docs.timescale.com/timescaledb/latest/how-to-guides/write-data/insert/#insert

**Comment by Jeffail** [comment]
Going back down memory lane I think the reason it wasn't implemented like this initially was because the actual statement is a single string, so it's difficult to concat multiple rows without dodgy SQL parsing. Ideally I want to still support adding things like `ON CONFLICT` clauses, so maybe we need a new component with slightly different ergonomics, needs a bit of thinking through but I'm thinking something like this:

```yaml
output:
  sql_insert:
    table: foo
    columns: [ foo, bar, baz ] # optional
    suffix: "" # optional
    prefix: "" # optional
```

Other thing to consider is whether we actually want an explicit `args_mapping` or we just enforce that messages are formatted into an array, which would be:

```yaml

```yaml
output:
  sql_insert:
    table: foo
    columns: [ foo, bar, baz ] # optional
    suffix: "" # optional
    prefix: "" # optional
    args_mapping: |
      root = [ this.foo, meta("bar"), now() ]
```

versus:

```yaml
output:
  sql_insert:
    table: foo
    columns: [ foo, bar, baz ] # optional
    suffix: "" # optional
    prefix: "" # optional
  processors:
    - bloblang: 'root = [ this.foo, meta("bar"), now() ]'
```
