### ISSUE TITLE
NATS Jetstream subjects not interpolated

### ISSUE THREAD

**Issue by mosiman** [Jeffail/benthos#898]
Hi! I think I may have found a bug, but it's also completely possible I've just been messing up this whole time. 

To reproduce this, I've started a simple NATS server: 
```
podman run -p 4222:4222 nats
```

Given this example config (call it `poc.yaml`?):
```
input:
  label: ""
  generate:
    mapping: 'root = {"sub": "foo.bar"}'
    interval: 5s
    count: 5
pipeline:
  processors:
    - bloblang: |
        meta nats_subject = this.sub
output:
  label: ""
  nats_jetstream:
    urls:
      - nats://127.0.0.1:4222
    subject: ${! meta("nats_subject") }
    max_in_flight: 1024
```

I'm not seeing any published messages via `nats sub "foo.bar"`. 

This is what I see when I try to `benthos -c poc.yaml`:

```
{"@timestamp":"2021-10-07T22:19:43-04:00","@service":"benthos","component":"benthos","level":"INFO","message":"Launching a benthos instance, use CTRL+C to close."}
{"@timestamp":"2021-10-07T22:19:43-04:00","@service":"benthos","component":"benthos","level":"INFO","message":"Listening for HTTP requests at: http://0.0.0.0:4195"}
{"@timestamp":"2021-10-07T22:19:43-04:00","@service":"benthos","component":"benthos.output","level":"INFO","message":"Sending NATS messages to subject: ${! meta(\"nats_subject\") }"}
```
If I hardcode the subject to be `foo.bar` then I do see the message published on the subject.

I tried to have a look around but couldn't get my pea brain to figure it how to fix it. If you don't have the bandwidth to tackle it I could try to get by if you pointed me in the right direction. Thanks!
