### ISSUE TITLE
propogating headers from http_client response to http server input

### ISSUE THREAD

**Issue by cabrrtt** [Jeffail/benthos#901]
In the documentation here https://www.benthos.dev/docs/guides/sync_responses#routing-output-responses-back, an illustration is given of Benthos acting as a reverse proxy.

Given 2 benthos processes:

```yaml
input:
  http_server:
    path: /post
    sync_response:
      headers:
        Content-Type: application/json
        blob: fish
output:
  broker:
    pattern: fan_out
    outputs:
    - file:
        path: data.txt
        codec: lines
    - type: sync_response
      processors:
      - text:
          operator: to_upper
```
and
```yaml
http:
  address: 127.0.0.1:4196
input:
  http_server:
    path: /post
output:
  http_client:
    url: http://localhost:4195/post
    verb: POST
    propagate_response: true
```
posting to 4195 with
```
echo {"address": {"city":"london"} } | httpie :4195/post
```
I get back `Content-Type: application/json`

posting to 4196, `Content-Type: application/octet-stream` is returned, and the `Blob: fish` is dropped.

I tried `copy_response_headers: true` but Content-Type remains application/octet-stream. Is it possible to preserve the headers of the response in the proxy configuration?
