### ISSUE TITLE
TLS support for websocket client

### ISSUE THREAD

**Issue by YachikaRalhan** [Jeffail/benthos#923]
Need TLS support for server and client authentication for Websocket connections just like HTTP client has. Something like this in supported fields.
```
   tls:
      enabled: false
      skip_cert_verify: false
      enable_renegotiation: false
      root_cas: ""
      root_cas_file: ""
      client_certs: [] 
```
