### ISSUE TITLE
Multiple input processors. Bug?

### ISSUE THREAD

**Issue by vryazanov** [Jeffail/benthos#936]
Hey, I have a question regarding multiple input processors.
I have a bunch of them configured to listen to different sqs queues, something like that:
```yaml
input_resources:
  - label: queue1
    aws_sqs:
      url: http://localhost:9324/queue/queue1
      endpoint: http://localhost:9324/
  - label: queue2
    aws_sqs:
      url: http://localhost:9324/queue/queue2
      endpoint: http://localhost:9324/

input:
  stdin:
    codec: lines
```
Here input is still `stdin` and when I start benthos - it starts to listen to both `queue1` and `queue2` even if I dont use them directly. Is it expected behavior?
Output:
```benthos --log.level trace -r ./common.yaml -r ./subprocess/jobposting.yaml -c ./workers/http.yaml
{"@timestamp":"2021-11-03T18:25:58+03:00","@service":"benthos","component":"queue1","level":"INFO","message":"Receiving Amazon SQS messages from URL: http://localhost:9324/queue/queue1"}
{"@timestamp":"2021-11-03T18:25:58+03:00","@service":"benthos","component":"queue2","level":"INFO","message":"Receiving Amazon SQS messages from URL: http://localhost:9324/queue/queue2"}
```
