### ISSUE TITLE
Output marking batches is nowhere documented

### ISSUE THREAD

**Issue by jume-dev** [Jeffail/benthos#938]
@Jeffail mentioned on discord:
> if you're sending batches then the socket output assumes you want to preserve them and indicates the end of the batch with an empty line, if you aren't interested in marking the end of batches in your output destination then you can break them out into individual messages with the split processor:
```
output:
  socket:
    network: tcp
    address: TODO
  processors:
    - split: {}
 ```

This seems to be missing in the documentation.
