### ISSUE TITLE
Start tests with -r flag.

### ISSUE THREAD

**Issue by vryazanov** [Jeffail/benthos#942]
Hello, is there a way to write unit tests if configuration uses resources from other files?
so let's imagine a have two files:
1. common.yaml
```yaml
processor_resources:
  - label: test
    noop: {}
```
2. configuration.yaml
```yaml
input:
  - type: stdin
pipeline:
  processors:
    - resource: test
    - bloblang: root = {"hello": "world"}
output:
  - type: stdout
 ```
Documentation says that `test` resource cannot be mocked in unit tests, but at the same time `benthos test` command does not support flag `-r`. Is there a workaround?
