### ISSUE TITLE
Streams mode config resources need better linting, docs need clarifying

### ISSUE THREAD

**Issue by lent85** [Jeffail/benthos#945]
I have the below configuration, which intent to switching the output to AWS S3 or Google Cloud Storage depend on **ARCHIVED_OUT**

```
input:
  nanomsg:
    urls:
      - tcp://*:5556
    bind: true
    socket_type: PULL
    sub_filters: []

pipeline:
  processors:
    ...

output:
  resource: ${ARCHIVED_OUT}

output_resources:
  - label: gcs
    gcp_cloud_storage:
      ...
  - label: s3
    aws_s3:
      ...
```
However, I always got the error _output resource 'gcs' was not found_
Checking the document and see no wrong configuration
https://www.benthos.dev/docs/configuration/resources/#feature-toggling
https://www.benthos.dev/docs/components/outputs/resource/
Using the Benthos version 3.57.0
