### ISSUE TITLE
Problem consuming from redpanda when using materialized sinks using the `reuseTopic` option. (`kafka: insufficient data to decode packet, more bytes expected`)

### ISSUE THREAD

**Issue by chjdev** [Jeffail/benthos#953]
Moving to a new issue from: https://github.com/Jeffail/benthos/issues/711#issuecomment-972643114

we have a topic where the data in (redpanda) kafka looks completely normal and i can consume it fine via cli, however when i try consume from it using benthos i get the same error, however nothing is produced to the output:

```
{"@timestamp":"2021-11-18T08:58:55+01:00","@service":"benthos","component":"incoming","level":"ERROR","message":"Kafka group message recv error: kafka: error while consuming xxx/0: kafka: insufficient data to decode packet, more bytes expected"}
```

Here's the config I used to test it, which works fine for other topics:

```yaml
http:
  address: 0.0.0.0:4195
  read_timeout: 5s
  root_path: /benthos
  debug_endpoints: false

input:
  label: incoming
  kafka:
    addresses:
      - "some_broker:31572"
    tls:
      enabled: true
      root_cas_file: /path/to/redpanda/ca.crt
      client_certs:
        - cert_file: /path/to/redpanda/cluster.crt
          key_file: /path/to/redpanda/cluster.key
    sasl:
      mechanism: "SCRAM-SHA-256"
      user: "user"
      password: "password"
    topics: [ "some_topic" ]
    consumer_group: some_consumer_group
    client_id: some_client_id
    checkpoint_limit: 1

buffer:
  type: none
  none: {}

output:
  label: "output"
  stdout:
    codec: lines
```

The specific topic in question was produced via a meterialize sink (with the reuse topic option enabled) which according to @senior7515 should work identically and is tested through integration tests on redpanda's side. (see original issue)

Any idea what might be going on here?

We're running
Benthos version: 3.58.0
Redpanda: v21.9.6

---

We've prepared a docker-compose that can reproduce the bug here: https://github.com/chjdev/benthos-bug-repro .

What we're observing is if benthos starts immediately, it consumes the messages from the (materialize sink) topic right away, then hits the above error.
However if we delay the start, then it will hit the error first and not consume any messages.
This only seems to happen if we use the topic reuse option of materialize which presumably uses control messages. It might be a red herring but I've also seen that the offsets in the reuse case start at `1` and in the non reuse case at `0`.

![image](https://user-images.githubusercontent.com/973941/142622775-0b9ac1a4-cd97-4ace-9da2-1ca050f00931.png)
