### ISSUE TITLE
Support relative paths in schema_path option for avro processor

### ISSUE THREAD

**Issue by BrenQ** [Jeffail/benthos#954]
Hi, I had a problem when I wanted to set a relative path in the schema_path option within the Avro processor. Only works with an absolute path:

  ```
- avro:
            encoding: binary
            operator: to_json
            schema_path: "file:///Users/xxxx/benthos/streams/schema.avsc" # OPT 1: It works
            schema_path: "file:///schema.avsc" # OPT 2 : It doesn't work
            schema_path: "file://schema.avsc" # OPT 3: It doesn't work
```

Chatting with @Jeffail told me that this is because the file transport does not support relative paths. https://pkg.go.dev/net/http#NewFileTransport. I saw that this is currently used to access files in the implementation. It would be great to add this support or document the limitations. Thanks!
