### ISSUE TITLE
timestamp_mapping to kafka_timestamp_unix make data lost

### ISSUE THREAD

**Issue by Sisphyus** [Jeffail/benthos#956]
my config.yaml

```
input:
  broker:
    inputs:
      - kafka:
          addresses:
            - "xxxx:9092"
            - "xxxx:9092"
          topics:
            - "downsampling_produce"
          sasl:
            mechanism: "SCRAM-SHA-512"
            user: "xxx"
            password: "xxx"
          target_version: "2.5.1"
          consumer_group: "remote_write_consumer"
          batching:
            count: 20
        processors:
          - group_by_value:
              value: ${! meta("kafka_key") }

buffer:
  system_window:
    timestamp_mapping: root = meta("kafka_timestamp_unix").number()
    size: 5s
    allowed_lateness: 1s

pipeline:
  threads: 4
  processors:
    - log:
        message: 'key:  ${! meta("kafka_key")}, value: ${! content() } }'
    - bloblang: |

        root.key = meta("kafka_key")

        root.value = this

        root.timestamp = meta("kafka_timestamp_unix").number()

        #root = if batch_index() != 0 { deleted() }

output:
  label: ""
  stdout:
    codec: lines
logger:
  level: INFO
  format: json
  add_timestamp: false
  static_fields:
    '@service': benthos
```

my producer code
```
func Produce()  {
	producer, err := newProducer()
	if err != nil {
		panic(err)
	}
	//messages := make([]*sarama.ProducerMessage, 0)
	for i := 1; i < 100; i++ {
		v1 := strconv.Itoa(i%2)
		v2 := strconv.Itoa(i)
		_, _, err = producer.SendMessage(prepareMessage("downsampling_produce", v1, v2))
		if err != nil {
			fmt.Println(err)
		}
	}
	wait()
}

func prepareMessage(topic, key, value string) *sarama.ProducerMessage {
	msg := &sarama.ProducerMessage{
		Topic:     topic,
		Partition: -1,
		Key: sarama.StringEncoder(key),
		Value:     sarama.StringEncoder(value),
		Timestamp: time.Now(),
	}

	return msg
}

```

my benthos version 
```
Version: 3.58.0
Date: 2021-11-02T19:41:43Z
```

the program output（can see some data lost, and after disable timestamp_mapping to kafka_timestamp_unix, no data lost）
![image](https://user-images.githubusercontent.com/22763940/142890526-fb1d3414-6725-4997-85a6-cb2317b0d3d0.png)

another point of confusion is why after canceling the batch setting of kafka, the aggregated data of each window becomes only one, such as one window every five seconds. These five seconds are just a simple wait, and no new data will come in, even though  The timestamp meets the requirements.
