### ISSUE TITLE
Can't use base URL with path for schema_registry_decode

### ISSUE THREAD

**Issue by mdowds** [Jeffail/benthos#957]
Hi, thanks for maintaining this library!

If you use a base URL for `schema_registry_decode` with a path component, it gets ignored when benthos makes requests to Schema Registry.

For example, with the config
```yaml
pipeline:
  processors:
  - schema_registry_decode:
      url: "http://localhost:8080/apis/ccompat/v6"
```
a request is made to `http://localhost:8080/schemas/ids/1` rather than `http://localhost:8080/apis/ccompat/v6/schemas/ids/1` to get the schema.

I'm happy to open a PR if this seems like a valid bug.
