### ISSUE TITLE
Output sync_response barfs with a static input file list

### ISSUE THREAD

**Issue by wirtsi** [Jeffail/benthos#962]
Hey Ash,

I came across something weird when using the sync_response output.

What I have:

```
http:
  enabled: true
  address: 0.0.0.0:4195
  root_path: /
input:
  resource: customer_extension_input
pipeline:
  processors:
    - json_schema:
        schema_path: "file://./schemas/customer_extension.json"
      label: json_schema
    - catch:
        - log:
            level: ERROR
            message: "Schema validation failed due to: ${!error()}"
        - bloblang: |
            root.errors = [{"code": "InvalidJsonInput", "message": error()}]
output:
  type: sync_response
```

where customer_extensions_input is either
```
input_resources:
  - label: customer_extension_input
    http_server:
      path: /customer
      allowed_verbs:
        - POST
      timeout: 20s
      sync_response:
        headers:
          Content-Type: "application/json"
```
or
```
input_resources:
  - label: customer_extension_input
    file:
      paths:
        - ./resources/customer/create_payload.json
        - ./resources/customer/update_payload.json
        - ./resources/customer/broken_payload.json
        - ./resources/customer/exists_payload.json
      codec: all-bytes
```

So my idea was that during development I can feed in static payload files and don't have to fiddle around with curl calls to the http_server.

When running my pipeline with the static file input, benthos goes into an endless loop. Output is

```
Create customer e3439098-7c32-4341-b36b-5e74764348de"}
{"@timestamp":"2021-11-23T10:09:48+01:00","@service":"benthos","component":"benthos.output","level":"ERROR","message":"Failed to send message to sync_response: result store not found within batch context"}
```
which keeps on repeating.

Moving sync_response into the processors fixes the issue ... but I still think that this should work. I have written some tests that also use the canned payloads, there it seems to work fine.

Bests & thanks a lot in advance for your help

wirtsi

**Comment by Jeffail** [comment]
Hey @wirtsi, this is because when your input is `file` there's no where for the sync response output to write the data, and since dropping data is avoided by default you enter an unending retry loop until intervention. There are two ways around this.

1. Change the `sync_response` output for `drop` using resources, allowing your local example to intentionally discard the data
2. Configure a fallback output that'll activate when the sync data can't be sent anywhere:
```yaml
output:
  fallback:
    - sync_response: {}
    - drop: {}
```
That'll mean data continues flowing when the sync responses can't be routed (you'll still get error logs though). However, this option also means a configuration error in your production config might go unnoticed as the default behaviour of your pipeline will be to discard the data for any reason.
