### ISSUE TITLE
Lint errors could give hints on indentation problems

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#985]
For example, with the following config:

```yaml
output:
  switch:
    retry_until_success: false
    cases:
      - check: errored() && meta().error_count.number() > 100
        processors:
          - log:
              level: DEBUG
              message: 'dropping message due to error_count over threshold.'
        output:
          drop: {}
```

We give the error `field processors not recognised`, it'd be much more useful if we could detect the fields of siblings and the parent in order to give a message like `field processors not recognised, consider moving it within the field "output"`.
