### ISSUE TITLE
bug: nats input 'loses' some messages in a burst

### ISSUE THREAD

**Issue by nwest1** [Jeffail/benthos#99]
Steps to reproduce:
- configure nats input
- utilizing `github.com/nats-io/go-nats/examples` run something like this:
```
./nats-pub -s nats://localhost:4222 out.test blahlblahblah &
./nats-pub -s nats://localhost:4222 out.test blahlblahblah &
./nats-pub -s nats://localhost:4222 out.test blahlblahblah &
./nats-pub -s nats://localhost:4222 out.test blahlblahblah &
./nats-pub -s nats://localhost:4222 out.test blahlblahblah &
./nats-pub -s nats://localhost:4222 out.test blahlblahblah &
./nats-pub -s nats://localhost:4222 out.test blahlblahblah &
./nats-pub -s nats://localhost:4222 out.test blahlblahblah &
./nats-pub -s nats://localhost:4222 out.test blahlblahblah &
./nats-pub -s nats://localhost:4222 out.test blahlblahblah &
./nats-pub -s nats://localhost:4222 out.test blahlblahblah &
./nats-pub -s nats://localhost:4222 out.test blahlblahblah &
./nats-pub -s nats://localhost:4222 out.test blahlblahblah &
./nats-pub -s nats://localhost:4222 out.test blahlblahblah &
./nats-pub -s nats://localhost:4222 out.test blahlblahblah &
```
- note that not all messages are processed.

**Comment by nwest1** [comment]
Sure! I'm running it in a docker compose with nats hooked up to an external kafka cluster.

```yaml
http:
  address: localhost:4195
  read_timeout_ms: 5000
  root_path: /benthos
  debug_endpoints: false
input:
  type: nats
  nats:
    subject: out.*
    urls:
    - nats://nats:4222
buffer:
  type: none
  none: {}
pipeline:
  processors: 
    - type: mainflux
output:
  type: kafka
  kafka:
    ack_replicas: false
    addresses:
    - kafka-broker-url:9093
    client_id: benthos_kafka_output
    compression: none
    key: ""
    max_msg_bytes: 1e+06
    round_robin_partitions: false
    target_version: 1.0.0
    timeout_ms: 5000
    tls:
      client_certs: 
        - cert_file: /cert.pem
          key_file: /key.pem
      enabled: true
      root_cas_file: /chain.pem
      skip_cert_verify: false
    topic: benthos_out
resources:
  caches: {}
  conditions: {}
logger:
  prefix: benthos
  level: INFO
  add_timestamp: true
  json_format: true
```

```yaml
version: "3"

services:

   nats:
     image: nats:1.1.0
     container_name: nats
     restart: on-failure

  benthos-writer:
    image: jeffail/benthos:latest
    container_name: benthos-kafka-writer
    expose:
      - 4195
    restart: on-failure
    ports:
      - 4195:4195
    volumes:
    - /work/cert.pem:/cert.pem
    - /work/key.pem:/key.pem
    - /work/chain.pem:/chain.pem
    - /work/benthos.yaml:/benthos.yaml
```

**Comment by nwest1** [comment]
Here's a better setup (and without my custom processor - sorry about that.)

benthos.yaml
```
http:
  address: localhost:4195
  read_timeout_ms: 5000
  root_path: /benthos
  debug_endpoints: false
input:
  type: nats
  nats:
    subject: out.*
    queue: "senml"
    urls:
    - nats://nats:4222
buffer:
  type: none
  none: {}
pipeline:
  processors: 
  - type: text
    text:
      operator: append
      value: ".append"
  threads: 4 # have been adjusting this...
output:
  type: nats
  nats:
    subject: testout
    urls:
    - nats://nats:4222
resources:
  caches: {}
  conditions: {}
logger:
  prefix: benthos
  level: ALL
  add_timestamp: true
  json_format: true
```

docker-compose
```
version: "3"

services:

  nats:
    image: nats:1.1.0
    restart: on-failure
    ports:
     - 4222:4222
     - 6222:6222
     - 8222:8222

  benthos-writer:
    image: jeffail/benthos:latest
    ports:
      - 4195:4195
    volumes:
    - ./benthos.yaml:/benthos.yaml
```

**Comment by Jeffail** [comment]
Hey @nwest1, I can reproduce this by hitting NATS with a large burst of data. It looks as though they are being intentionally dropped by NATS when the Benthos consumer is busy. It helps to add more consumers in a broker:

``` yaml
input:
  type: broker
  broker:
    copies: 10
    inputs:
    - type: nats
      nats:
        subject: out.*
        queue: "senml"
        urls:
          - nats://nats:4222
```

Other than this I'm not sure what we can do on the Benthos side. It's a pub/sub at-most-once queue so you don't have a guarantee of message delivery, which in the case of short bursts is where you're most likely to see the messages being dropped.
